In [1]:
import pandas as pd

In [6]:
data = pd.read_fwf('SFMC_PBD_Orders_20191025.txt')

In [7]:
data

,RECSEQ\tEMPPID\tORDER_NO\tORDER_DATE\tPAYMENT_TYPE\tPAYMENT_DESC\tAMOUNT_RECEIV\tNO_LINE_ITEMS\tORDER_TYPE\tOPERATOR_ID\tDISCOUNT_RATE\tMEMBER_FLAG\tSHIP_HAND_CHG,SHIP_HAND_TAX,INSERT_DTM,UPDATE_DTM,ORDCHANNEL,STCUSTID,BTCUSTID,ORDTDOL,ORDITEMQTY,ORDCOGS,ORDCOST,CATALOGID,PROMOCD,ORDSOURCE
0,0000000001\t0000035361\t45207100\t2008/04/28 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000002\t0000035361\t45208638\t2008/05/05 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0000000003\t0000035361\t45290071\t2009/03/13 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0000000004\t0000035361\t45367061\t2010/01/22 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0000000005\t0000035361\t45370633\t2010/02/09 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587525,0000587526\t0005259764\t46019911\t2018/11/13 0...,18230.00\t0.00,UUV\tUUVV21,UUVV218UU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587526,0000587527\t0005259764\t46162176\t2019/10/10 0...,18\t18986.50\t0,00\tUUV\tUUV,419\tUUVV41,UUV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587527,0000587528\t0005259800\t46167925\t2019/10/24 0...,837.04\t9\t703.,1\t133.73\tT,H\tTHHA13\tT,HA13THH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587528,0000587529\t0005260295\t46028447\t2018/12/04 0...,441.82\t6\t381,20\t60.62\tC,X\tCIX\tCIXC,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587529,0000587530\t0005260295\t46164863\t2019/10/15 0...,1.72\t60.21\tTH,M\tTHOA10B,HOA10BTHOM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN