In [9]:
import pandas as pd

In [10]:
med_words = ['cancer', 'cardiology', 'neurology', 'family care', 'pulmonary', 'anesthesia', 'orthope', 'urgent care', 'allergy', 'kidney', 'surgery', 'hosp', 'mri', 'throat', 'dentist', 'med', 'clinic', 'health', 'gastroenter','anesthesiologist','patient','physician','surgeon','doctor','hospital', 'md', 'medical', 'pediatrics', 'm.d.']

In [6]:
WRONG = pd.read_csv('WRONG.csv')

In [45]:
def analyze_numbers(dataframe):
    
    
    address_match = 0
    city_match = 0
    zipcode_match = 0
    healthcount = 0
    mailcount = 0
    connectcount = 0
    portcount = 0
    novalidcount = 0
    unknowncount = 0
    disconnectedcount = 0
    voipcount = 0
    wirelesscount = 0
    no_address_count = 0
    no_date_count = 0
    business_count = 0
    residential_count = 0
    low_count = 0
    high_count = 0
    med_count = 0
    first_name_match = 0
    last_name_match = 0 
    workplace_match = 0
    state_match = 0
    no_name = 0
        


    for row in dataframe.itertuples():
        if row.Address == row.OFFICE_ADDRESS_LINE_2:
            address_match += 1
        if row.City == row.OFFICE_ADDRESS_CITY:
            city_match += 1
        if str(row.OFFICE_ADDRESS_ZIP) in str(row.Zipcode):
            zipcode_match += 1
        
        if row.State == row.OFFICE_ADDRESS_STATE:
            state_match += 1
        
        if str(row.PHYSICIAN_LAST_NAME).lower() in str(row.Name).lower():
            last_name_match +=1
        if str(row.PHYSICIAN_FIRST_NAME).lower() in str(row.Name).lower():
            first_name_match +=1
        
        if str(row.OFFICE_ADDRESS_LINE_1).lower() in str(row.Name).lower():
            workplace_match += 1

        healthy = False
        for word in med_words:
            if word in str(row.Name).lower():
                healthy = True
        if healthy == True:    
            healthcount += 1

        if 'IsMailable' in str(row.Notes):
            mailcount += 1
        if 'IsConnected' in str(row.Notes):
            connectcount += 1
        if 'IsPorted' in str(row.Notes):
            portcount += 1
        if 'NotValid' in str(row.Notes):
            novalidcount += 1
        if 'IsUnknownContact' in str(row.Notes):
            unknowncount += 1
        if 'IsPossibleDisconnected' in str(row.Notes):
            disconnectedcount += 1
        if 'IsPossiblePortableVOIP' in str(row.Notes):
            voipcount += 1
        if 'IsWireless' in str(row.Notes):
            wirelesscount += 1

        if row.Address == 'None':
            no_address_count += 1
        if row.Date == 'None':
            no_date_count += 1
        if row.PhoneType == 'BUSINESS':
            business_count += 1
        if row.PhoneType == 'RESIDENTIAL':
            residential_count += 1
        if row.QualityScore == 'LOW':
            low_count += 1
        if row.QualityScore == 'HIGH':
            high_count += 1
        if row.QualityScore == 'MED':
            med_count += 1
        if row.Name =='None':
            no_name += 1

    new_dict = {
        'Address Matches': address_match,
        'City Matches': city_match,
        'ZipCode Matches': zipcode_match,
        'No Address': no_address_count,
        'No Date': no_date_count,
        'Relevant Name': healthcount,
        'Business Phone': business_count,
        'Residential Phone': residential_count,
        'Low Quality': low_count,
        'Medium Quality': med_count,
        'High Quality': high_count,
        'Mailable': mailcount,
        'Connected': connectcount,
        'Ported': portcount,
        'Not Valid': novalidcount,
        'Unknown Contact': unknowncount,
        'Possibly Disconnected': disconnectedcount,
        'Possibly Portable VOIP': voipcount,
        'Wireless': wirelesscount,
        'First Name Match':first_name_match,
        'Last Name Match':last_name_match,
        'Workplace Match': workplace_match,
        'State Match': state_match, 
        'No Name': no_name
        }
        
    return(new_dict)

In [32]:
analyze_numbers(WRONG)

{'Address Matches': 5,
 'City Matches': 11,
 'ZipCode Matches': 0,
 'No Address': 9,
 'No Date': 22,
 'Relevant Name': 27,
 'Business Phone': 44,
 'Residential Phone': 4,
 'Low Quality': 12,
 'Medium Quality': 4,
 'High Quality': 34,
 'Mailable': 38,
 'Connected': 37,
 'Ported': 28,
 'Not Valid': 0,
 'Unknown Contact': 0,
 'Possibly Disconnected': 1,
 'Possibly Portable VOIP': 6,
 'Wireless': 0,
 'First Name Match': 3,
 'Last Name Match': 2,
 'Workplace Match': 0,
 'State Match': 20,
 'No Name': 0}

In [18]:
WRONG['Name']

0                                   ELIZABETH A HIGGINS
1                                      EMORY UNIVERSITY
2                                        OSF ST FRANCIS
3                          COASTAL FAMILY HEALTH CENTER
4       SUN CITIES MEDICAL GROUP PC PHYSICIANS SURGEONS
5                               PERSPECTUS ARCHITECTURE
6                      MIDWEST CENTER FOR WOMENS HEALTH
7      RONALD MCDONALD HOUSE OF NASHVILLE PUBLIC SOCIAL
8                     IU PSYCHIATRIC MANAGEMENT DOCTORS
9           FIRST COAST PRIMARY CARE PHYSICIANS GENERAL
10        WILSON MEDICAL CENTER WILSON ENT SINUS CENTER
11                    CRISP REGIONAL HOSPITAL HOSPITALS
12           GORDONCONWELL THEOLOGICAL SEMINARY SCHOOLS
13         SOUTHERN ASSOCIATION OF COLLEGES AND SCHOOLS
14                      CENTEGRA PRIMARY CARE ALGONQUIN
15                                      NY,PRESBYTERIAN
16                              MCCLELLAN PATRICK J DDS
17               RAFAEL MORESCHI MD PHYSICIANS SURGEONS
18    MEDICAL COLLEGE OF WISCONSIN APPOINTMENT SERVICES
19                        ASTARIS LLC PLANTS CARONDELET
20                                      PRICE TIMOTHY A
21                                           E JALILIAN
22                                      CROUSE HOSPITAL
23                               MICRO MEDIA NEWSPAPERS
24         NICOLE DMD BESU MDS DENTIST PERIODONTIST GUM
25                         TEXAS ONCOLOGY FRISCO STNBRR
26                         FAMCAR CLINIC OF NORTH TEXAS
27          UNIVERSITY OF TEXAS MEDICAL BRANCH THE UTMB
28          COPY PRO INC SOFTWARE CD ROM SALES SERVICES
29                LAURIE BERRY PA C PHYSICIANS SURGEONS
30                                       PETER J KARRAS
31    NEWARK CITY BOARD OF EDUCATION EDUCATIONAL SER...
32                        INTEGRITY ROOFING & EXTERIORS
33                        INTEGRITY ROOFING & EXTERIORS
34                        INTEGRITY ROOFING & EXTERIORS
35                                  DELROSARIO MARIA MD
36                                              UNIV MN
37      NONA M CRAIG MD PHYSICIANS SURGEONS DERMATOLOGY
38         ESSENTIA HEALTH PEDIATRICSHEMATOLOGYONCOLOGY
39       PROVIDENCE SACRED HEART MEDICAL CENTER DOCTORS
40                                            KYU H KIM
41              ROGER M THOMPSON MD PHYSICIANS SURGEONS
42                                       CA PAC MED CTR
43            DYKE VAN AESTHETICS MD PHYSICIANS GENERAL
44            WARM SPRINGS HEALTH WELLNESS CENTER RADIO
45          SURGICAL SPECIALTY CTRNE PA MEDICAL CENTERS
46                                      355 LEXINGTON A
47     KAISER PERMANENTE MEDICAL CENTERSO SAN FRANCISCO
48                                        U C I MED CTR
49                      LAHEY CLINIC APPOINTMENT OFFICE
Name: Name, dtype: object

In [20]:
CONN = pd.read_csv('CONNECTED.csv')
DIS = pd.read_csv('DISCONNECTED.csv')
con = pd.read_csv('../Finality/connected_base.csv')
di = pd.read_csv('../Finality/disconnected_base.csv')
CONNECTED = pd.merge(con, CONN, on='OFFICE_TELEPHONE')
DISCONNECTED = pd.merge(di, DIS, on='OFFICE_TELEPHONE')

In [50]:
analyze_numbers(DIS)

{'Address Matches': 10,
 'City Matches': 39,
 'ZipCode Matches': 31,
 'No Address': 39,
 'No Date': 53,
 'Relevant Name': 44,
 'Business Phone': 72,
 'Residential Phone': 19,
 'Low Quality': 52,
 'Medium Quality': 14,
 'High Quality': 25,
 'Mailable': 62,
 'Connected': 39,
 'Ported': 47,
 'Not Valid': 1,
 'Unknown Contact': 8,
 'Possibly Disconnected': 27,
 'Possibly Portable VOIP': 5,
 'Wireless': 2,
 'First Name Match': 9,
 'Last Name Match': 16,
 'Workplace Match': 8,
 'State Match': 74,
 'No Name': 9}

In [49]:
DIS = DIS.fillna("None")

In [30]:
CONNECTED[['State', 'OFFICE_ADDRESS_STATE']]

   State OFFICE_ADDRESS_STATE
0     NJ                   NJ
1     MI                   MI
2     NY                   NY
3     IA                   IA
4     MT                   MT
5     MO                   MO
6     OH                   OH
7     AZ                   AZ
8     KY                   KY
9     MA                   MA
10    PA                   PA
11    NM                   NM
12    MS                   MS
13    MS                   MS
14    NH                   NH
15    NJ                   NJ
16    PA                   PA
17    MN                   MN
18    TN                   TN
19    NV                   NV
20    VA                   VA
21    NY                   NY
22    FL                   FL
23    MI                   MI
24    OH                   OH
25    IN                   IN
26    MA                   MA
27    VT                   VT
28    VA                   VA
29    CA                   CA
30    TX                   TX
31    TX                   TX
32    SC                   SC
33    SC                   SC
34    AR                   AR
35    TX                   TX
36    NY                   NY
37    CA                   CA
38    CA                   CA
39    NJ                   NJ
40    AZ                   AZ
41    ND                   ND
42  None                   MI
43    GA                   GA
44    WI                   WI
45    CA                   CA
46    TX                   TX
47    CA                   CA
48    NH                   NH
49    MN                   MN