In [1]:
import pandas as pd
import getphone_functions10 as g

In [3]:
info = pd.read_csv('../../AMAIA/GetPhoneInfo_batch_sample_info.csv')

In [164]:
INFO = info[info['COMMENTS'].isin(['NOT IN SERVICE', 'FAX MODEM'])]

In [165]:
RESULTS = pd.read_csv('get_phone_batch_output.csv')

In [166]:
merged = pd.merge(INFO, RESULTS, left_on='OFFICE_TELEPHONE', right_on='phone')

In [25]:
wrong = pd.read_csv('all_wrong.csv')

In [26]:
wrong=wrong.fillna('None')

AttributeError: 'Pandas' object has no attribute 'ContactSICDesc'

In [168]:
merged = merged.fillna('None')

In [67]:
def analyze_numbers(dataframe):
    
    address_match = 0
    city_match = 0
    zipcode_match = 0
    healthcount = 0
    mailcount = 0
    connectcount = 0
    portcount = 0
    unknowncount = 0
    disconnectedcount = 0
    voipcount = 0
    wirelesscount = 0
    no_address_count = 0
    no_date_count = 0
    business_count = 0
    residential_count = 0
    low_count = 0
    high_count = 0
    med_count = 0
    first_name_match = 0
    last_name_match = 0 
    workplace_match = 0
    state_match = 0
    no_name = 0
    tiny_count =0 


    for row in dataframe.itertuples():
        gpi_add = g.translate_addr(str(row.ContactAddressOut))
        ws_add = g.translate_addr(str(row.OFFICE_ADDRESS_LINE_2))
        if gpi_add != 'NONE':
            if gpi_add in ws_add or ws_add in gpi_add:
                address_match += 1
        if str(row.OFFICE_ADDRESS_CITY) in str(row.ContactCityOut):
            city_match += 1
        if g.clean_zipcode(row.OFFICE_ADDRESS_ZIP) == g.clean_zipcode(row.ContactZipOut):
            zipcode_match += 1

        if row.ContactStateOut == row.OFFICE_ADDRESS_STATE:
            state_match += 1

        if str(row.PHYSICIAN_LAST_NAME).lower() in str(row.ContactNameOut).lower():
            last_name_match +=1
        if str(row.PHYSICIAN_LAST_NAME).lower() in str(row.ContactNameOut).lower() or str(row.OFFICE_ADDRESS_LINE_1).lower() in str(row.ContactNameOut).lower():
            tiny_count += 1
        if str(row.PHYSICIAN_FIRST_NAME).lower() in str(row.ContactNameOut).lower():
            first_name_match +=1

        if str(row.OFFICE_ADDRESS_LINE_1).lower() in str(row.ContactNameOut).lower():
            workplace_match += 1
#         if str(row.OFFICE_ADDRESS_LINE_1).lower() not in str(row.ContactNameOut).lower():
#             print (f'{row.OFFICE_ADDRESS_LINE_1} is not {row.ContactNameOut}')
        if is_healthy(row.ContactNameOut)==True: 
            healthcount += 1
                
            

        if 'IsMailable' in str(row.NoteDescriptions):
            mailcount += 1
        if 'IsConnected' in str(row.NoteDescriptions):
            connectcount += 1
        if 'IsPorted' in str(row.NoteDescriptions):
            portcount += 1
        if 'IsUnknownContact' in str(row.NoteDescriptions):
            unknowncount += 1
        if 'IsPossibleDisconnected' in str(row.NoteDescriptions):
            disconnectedcount += 1
#             if is_healthy(row.ContactNameOut)==True:  
#                 print(row.ContactNameOut)
        if 'IsPossiblePortableVOIP' in str(row.NoteDescriptions):
            voipcount += 1
        if 'IsWireless' in str(row.NoteDescriptions):
            wirelesscount += 1

        if row.ContactAddressOut == 'None':
            no_address_count += 1
        if row.DateOfPorting == 'None':
            no_date_count += 1
        if row.ContactPhoneType == 'BUSINESS':
            business_count += 1
        if row.ContactPhoneType == 'RESIDENTIAL':
            residential_count += 1
        if row.ContactQualityScore == 'LOW':
            low_count += 1
        if row.ContactQualityScore == 'HIGH':
            high_count += 1
        if row.ContactQualityScore == 'MED':
            med_count += 1
        if row.ContactNameOut =='None':
            no_name += 1

    new_dict = {
        'Address Matches': address_match,
        'City Matches': city_match,
        'ZipCode Matches': zipcode_match,
        'No Address': no_address_count,
        'No Date': no_date_count,
        'Relevant Name': healthcount,
        'Business Phone': business_count,
        'Residential Phone': residential_count,
        'Low Quality': low_count,
        'Medium Quality': med_count,
        'High Quality': high_count,
        'Mailable': mailcount,
        'Connected': connectcount,
        'Ported': portcount,
        'Unknown Contact': unknowncount,
        'Possibly Disconnected': disconnectedcount,
        'Possibly Portable VOIP': voipcount,
        'Wireless': wirelesscount,
        'First Name Match':first_name_match,
        'Last Name Match':last_name_match,
        'Workplace Match': workplace_match,
        'State Match': state_match, 
        'No Name': no_name,
        'New Count': tiny_count
#         'disconnected':rpv_disconnected
        }
        
    return(new_dict)

In [68]:
wron = analyze_numbers(wrong)

In [29]:
def is_healthy(name):
    healthy = False
    for word in med_words:
        if word in str(name).lower():
            healthy = True
    return(healthy)

In [30]:
from med_words4 import med_words

In [35]:
wrong

,PHYSICIAN_ME_NUMBER,PHYSICIAN_FIRST_NAME,PHYSICIAN_LAST_NAME,OFFICE_ADDRESS_LINE_1,OFFICE_ADDRESS_LINE_2,OFFICE_ADDRESS_CITY,OFFICE_ADDRESS_STATE,OFFICE_ADDRESS_ZIP,OFFICE_TELEPHONE,ProviderNameOut,ContactNameOut,ContactAddressOut,ContactCityOut,ContactStateOut,ContactZipOut,ContactPhoneType,ContactQualityScore,DateOfPorting,NoteDescriptions
0,2701030926,ADAM,STREBECK,DEPT OF PATHOLOGY,1300 S MONTGOMERY AVE,SHEFFIELD,AL,35660,6017039632,TELEPAK NTWKS - MS,RUSH MEDICAL GROUP OB GYN,1800 12TH ST,MERIDIAN,MS,39301-4158,BUSINESS,LOW,8/22/2018,"IsMailable,IsPorted,IsPossibleDisconnected,INF"
1,51705830049,AFSANEH,KHALILI,None,4400 DUCKHORN DR,SACRAMENTO,CA,95834,7075840672,MPOWER COMM - CA,SANTA ROSA MEMORIAL HOSPITAL,None,SANTA ROSA,CA,95401,BUSINESS,LOW,8/12/2015,"IsPorted,IsPossibleDisconnected,INF"
2,3548840961,ANNA,HOLNESS,None,41 E POST RD,WHITE PLAINS,NY,10601,9146811158,CABLEVSN LGHTPATH NY,WHITE PLAINS HOSPITAL CENTER DAVIS AV AT E POST,41 E POST RD,WHITE PLAINS,NY,10601-4607,BUSINESS,LOW,4/23/2015,"IsMailable,IsPorted"
3,1201021614,CHARLES,PROCTER,None,3193 HOWELL MILL RD NW STE 125,ATLANTA,GA,30327,4704194380,COMCAST PHONE - GA,CHARLES D PROCTER JR MD,None,None,None,None,UNKNOWN,MED,8/14/2017,IsPorted
4,1606891594,CATHERINE,HOFER,None,629 W 9TH ST,SIOUX FALLS,SD,57104,6053393378,MIDCONTINENT COM SD,DESTINY FAMILY MEDICAL CLINIC PHYSICIANS SURGEONS,1417 S MINNESOTA AVE,SIOUX FALLS,SD,57105-1715,BUSINESS,HIGH,11/21/2011,"IsMailable,IsConnected,IsPorted"
5,401111026,CHRISTOPHER,MCCLINTON,HIGHLANDS ONCOLOGY GROUP,808 S 52ND ST,ROGERS,AR,72758,9135883610,SOUTHWESTERN BELL,KU MED CTR,None,LENEXA,KS,66215,BUSINESS,LOW,None,None
6,65401030411,DAVID,AFRAM,None,20 HOSPITAL DR,LOGAN,WV,25601,3048311670,LUMOS NETWORKS-VA,LOGAN REGIONAL,20 HOSPITAL DR,LOGAN,WV,25601-3452,BUSINESS,LOW,11/9/2006,"IsMailable,IsPorted"
7,2576120438,DOUGLAS,KELLEY,None,5450 FORT ST,TRENTON,MI,48183,7346713883,BROADWING COMM - MI,OAKWOOD SOUTHSHORE MEDICAL CENTER EMERGENCY ROOM,5450 FORT ST,TRENTON,MI,48183-4601,BUSINESS,HIGH,2/5/2014,"IsMailable,IsConnected,IsPorted"
8,2416120717,EBEN,LICHTMAN,None,170 MANNING DR 3RD FL,CHAPEL HILL,NC,27514,9199664431,INTERMEDIA COMM - NC,UNC HOSPITALS UNC HEALTH CARE,170 MANNING DR,CHAPEL HILL,NC,27514-4221,BUSINESS,LOW,3/1/2017,"IsMailable,IsPorted"
9,518861158,ERIC,WALL,CHILDREN'S HOSPITAL MED CTR,3333 BURNET AVE,CINCINNATI,OH,45229,5136364785,CBTS TECH SOL LLC-OH,PEDIATRIC ORTHOPAEDICS DEVELOPMENTAL HEALTH,None,CORRVILLE,OH,45219,BUSINESS,HIGH,4/23/2019,"IsConnected,IsPorted"
10,3509940711,ALEX,KANG,None,6714 BEACH B LVD,BUENA PARK,CA,90621,5628686256,FRONTIER CALIFORNIA,MESSIAH MEDICAL CENTER CLINICS MEDICAL,11832 ROSECRANS AVE,NORWALK,CA,90650-4107,BUSINESS,HIGH,None,"IsMailable,IsConnected"
11,514960356,ALMA,MALDONADO,None,3838 SHERMAN DR STE 7,RIVERSIDE,CA,92503,5596554942,PACIFIC BELL,MENDOTA UNIFIED SCHOOL DISTRICT DISTRICT OFFICE,115 MCCABE AVE,MENDOTA,CA,93640-2000,BUSINESS,HIGH,None,"IsMailable,IsConnected"
12,6701780050,CLAUS,HAMANN,LANDMARK HEALTH,1400 COMPUTER DR STE 301,WESTBOROUGH,MA,1581,2079922601,OXFORD NETWORKS-ME,EXTENDED CARE SERVICES HOME HEALTH CARE SERVICES,1012 UNION ST STE 1,BANGOR,ME,04401-3058,BUSINESS,LOW,4/3/2014,"IsMailable,IsPorted,IsPossibleDisconnected,INF"
13,515030603,CARLOS,RODRIGUEZ,STAR VIEW ADOLESCENT CENTER,4025 W 226TH ST,TORRANCE,CA,90505,3237792871,PACIFIC BELL,MARILY STERLING,None,None,None,None,RESIDENTIAL,LOW,None,None
14,2878670364,DAVID,JAMES,None,10501 E 91ST ST,TULSA,OK,74133,9187493399,SOUTHWESTERN BELL,DAVID S JAMES DO PHYSICIANS GENERAL,3345 S HARVARD AVE,TULSA,OK,74135-1812,BUSINESS,HIGH,None,"IsMailable,IsConnected"
15,4204801822,EFRAIN,PADILLA,None,162 CALLE JOSE RODRIGUEZ IRIZ,ARECIBO,PR,612,7878787726,LIBERTY CABLEVSN-PR,SEGUNDO GONZALEZ,244 PO BOX,ARECIBO,PR,00613-0244,RESIDENTIAL,LOW,5/16/2016,"IsMailable,IsPorted,IsPossibleDisconnected,INF"
16,2416840833,JOHN,SALVATO,PEDIATRIC SUBSPECIALITY,1600 EUREKA RD,ROSEVILLE,CA,95661,2076201430,BIDDEFORD INTERNT ME,MAINE CENTER DEVELOPMENTAL BEHAVIORAL PEDIATRICS,269 OLD BELGRADE RD,AUGUSTA,ME,04330-8055,BUSINESS,HIGH,1/5/2007,"IsMailable,IsConnected,IsPorted"
17,401951385,JACQUELINE,HOWARD,None,2851 S PARKER RD STE 444,AURORA,CO,80014,3033572540,"AIRUS, INC. - CO",MERCY DIVINE,None,None,None,None,RESIDENTIAL,MED,8/20/2019,IsPorted
18,511020751,KENDRA,BERGSTROM,None,4225 ROOSEVELT WAY NE FL 4,SEATTLE,WA,98105,2062327546,"ONVOY, LLC - WA",ISLAND DERMATOLOGY PHYSICIANS SURGEONS,8435 SE 68TH ST STE 118,MERCER ISLAND,WA,98040-5249,BUSINESS,HIGH,11/20/2018,"IsMailable,IsConnected,IsPorted"
19,4202980151,JERRY,LEON,URB COSTA CARIBE,1253 CALLE DON QUIJOTE,PONCE,PR,716,7878435420,LIBERTY CABLEVSN-PR,CARRERAS EMMA LOU MD,None,PONCE,PR,717,BUSINESS,LOW,7/14/2016,IsPorted
20,30803803079,JOSE,ORTIZ,VISTA BAHIA,251 PASEO DEL PUERTO,PENUELAS,PR,624,7872576965,PUERTO RICO TEL CO,JOSE R ORTIZ,OE6 CALLE 514,CAROLINA,PR,00982-1812,RESIDENTIAL,LOW,None,"IsMailable,IsPossibleDisconnected,INF"
21,26418910011,JULIANA,MILLAN,DEPARTMENT OF VETERANS AFFAIRS OUTPATIEN,8601 UNIVERSITY EAST DR,CHARLOTTE,NC,28213,8573644153,VERIZON NEW ENGLAND,None,None,None,None,None,None,None,3/12/2005,"IsPorted,IsUnknownContact"
22,3840991988,KARL,KULIKOWSKI,DEPARTMENT OF ANESTHESIOLOGY,24 HOSPITAL AVE,DANBURY,CT,6810,2037397433,TELEPORT COMM AM-CT,WESTERN CONNECTICUT IMAGING,21 ELM ST,NEW MILFORD,CT,06776-2915,BUSINESS,LOW,4/24/2018,"IsMailable,IsPorted"
23,4504080183,LINDSAY,COLEMAN,STE 1,1410 BLANDING ST,COLUMBIA,SC,29201,8032542394,BELLSOUTH SO BELL,DARRELL BOYKIN,240 STONERIDGE DR STE 304,COLUMBIA,SC,29210-8013,RESIDENTIAL,LOW,None,IsMailable
24,64914794909,MANUEL,RODRIGUEZ-ZAYAS,None,3084 AVE FAGOT URB SANTA CLARA,PONCE,PR,716,7879840992,PUERTO RICO TEL CO,RODRIGUEZ ZAYAS MANUEL,1 URB SANTA CLARA CAL,PONCE,PR,715,BUSINESS,HIGH,7/28/2017,"IsConnected,IsPorted"
25,2878151618,KENDALL,JOHNSON,STE 450,6675 HOLMES RD,KANSAS CITY,MO,64131,8162767650,SOUTHWESTERN BELL,RESEARCH MEDICAL CENTER BROOKSIDE CAMPUS,None,KANSAS CITY,MO,64110,BUSINESS,LOW,None,None
26,64954010021,MARIO,AZUERO GOMEZ,None,1607 S OLD MISSOURI RD,SPRINGDALE,AR,72764,4794633000,WINDSTREAM COMM AR,WA REG MED CTR,3336 N FUTRALL DR,FAYETTEVILLE,AR,72703-4057,BUSINESS,LOW,5/24/2019,"IsMailable,IsPorted"
27,4109980736,RYAN,LEWIS,ATTN: CHIEF MEDICAL OFFICER,11506 S STATE ST,DRAPER,UT,84020,4356281641,VERACITY COMMS - UT,SOUTHWEST SURGICAL ASSOCIATES JOHN T MILLER MD,1490 E FOREMASTER DR STE 200,SAINT GEORGE,UT,84790-4496,BUSINESS,HIGH,1/25/2011,"IsMailable,IsConnected,IsPorted"
28,2312952877,SCOTT,RIISE,60 MDG/SGHQ,101 BODIN CIR,TRAVIS AFB,CA,94535,7074237372,TELEPORT COM SANFRAN,TRAVIS AFB,101 BODIN CIR,TRAVIS AFB,CA,94535-1809,BUSINESS,LOW,8/27/2004,"IsMailable,IsPorted,IsPossibleDisconnected,INF"
29,3875150617,EUGENIA,ANYANWU,None,1941 EAST RD,HOUSTON,TX,77054,7134862570,LEVEL 3 COMM - TX,UT HEALTH,None,None,None,None,BUSINESS,MED,11/10/2017,"IsConnected,IsPorted,IsPossiblePortableVOIP"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,3501681139,JEREMY,WALETZKY,None,1330 NEW HAMPSHIRE AVE NW STE 113,WASHINGTON,DC,20036,2024630220,COMCAST PHONE - VA,PRICE TIMOTHY A,1330 NEW HAMPSHIRE AVE NW STE 121,WASHINGTON,DC,20036,BUSINESS,HIGH,5/26/2017,"IsMailable,IsConnected,IsPorted"
160,2802090890,LALEH,JALILIAN,None,None,None,None,None,4032887939,TELUS COMM INC,E JALILIAN,92-4936 DALTON DR NW,CALGARY,AB,T3A 2,RESIDENTIAL,HIGH,None,IsConnected
161,3515690459,LINDA,PIER,None,800 IRVING AVE,SYRACUSE,NY,13210,3157012550,NORTHLAND NETWORKS,CROUSE HOSPITAL,None,SYRACUSE,NY,13202,BUSINESS,LOW,3/22/2018,IsPorted
162,3607120951,ADAM,NARDINI,DEPT FAMILY MEDICINE,200 HAWKINS DR,IOWA CITY,IA,52242,7326577344,COMCAST BUS COMM-NJ,MICRO MEDIA NEWSPAPERS,15 UNION AVE,LAKEHURST,NJ,8733,BUSINESS,HIGH,11/21/2011,"IsMailable,IsConnected,IsPorted"
163,4201080822,JAVIER,MENDEZ,OFFICE PARK I,349 AVE HOSTOS STE 102D,MAYAGUEZ,PR,680,2396593053,LEVEL 3 COMM - FL,NICOLE DMD BESU MDS DENTIST PERIODONTIST GUM,4955 CASTELLO DR,NAPLES,FL,34103,BUSINESS,HIGH,2/20/2015,"IsMailable,IsConnected,IsPorted,IsPossiblePort..."
164,1803101252,MEGHAN,REICKS,None,5236 W UNIVERSITY DR STE 1700,MCKINNEY,TX,75071,2144915858,MCLEODUSA TEL - TX,TEXAS ONCOLOGY FRISCO STNBRR,None,None,None,None,UNKNOWN,MED,9/6/2009,IsPorted
165,70401890180,TAIMUR,BUTT,None,1650 EBER RD STE E,HOLLAND,OH,43528,9725391600,FRONTIER COMM OF TX,FAMCAR CLINIC OF NORTH TEXAS,4320 WINDSOR CENTRE TRL STE 300,FLOWER MOUND,TX,75028,BUSINESS,HIGH,None,"IsMailable,IsConnected"
166,90207900094,GOKHAN,KILIC,DEPARTMENT OF OBSTETRICS AND GYNECOLOGY,301 UNIVERSITY BLVD,GALVESTON,TX,77555,4097729507,SOUTHWESTERN BELL,UNIVERSITY OF TEXAS MEDICAL BRANCH THE UTMB,301 UNIVERSITY BLVD,GALVESTON,TX,77555,BUSINESS,HIGH,None,"IsMailable,IsConnected"
167,2834821471,VERA,TORP,None,3851 SHAW RIDGE RD,SAN DIEGO,CA,92130,9256891200,COMCAST PHONE - CA,COPY PRO INC SOFTWARE CD ROM SALES SERVICES,2500 DEAN LESHER DR STE A,CONCORD,CA,94520,BUSINESS,HIGH,11/24/2014,"IsMailable,IsConnected,IsPorted"
168,1201010400,PHILLIP,PATTERSON,VETERANS AFFAIRS HOSPITAL,1970 ROANOKE BLVD,SALEM,VA,24153,5407723530,LUMOS NETWORKS INC.,LAURIE BERRY PA C PHYSICIANS SURGEONS,1802 BRAEBURN DR,SALEM,VA,24153,BUSINESS,HIGH,9/28/2006,"IsMailable,IsConnected,IsPorted"
169,4804990891,SHAILAJA,PHILIP,CHILDREN'S MEDICAL CENTER,1935 MEDICAL DISTRICT DR,DALLAS,TX,75235,2175287541,AMERITECH ILLINOIS,PETER J KARRAS,1025 S 6TH ST,SPRINGFIELD,IL,62703,RESIDENTIAL,HIGH,None,"IsMailable,IsConnected"
170,3841952129,SAMUEL,CARRUTH,PARK AVENUE PEDIATRIC ASSO,2 CEDAR ST RM 901,NEWARK,NJ,7102,9737337360,MCI WORLDCOM COMM NJ,NEWARK CITY BOARD OF EDUCATION EDUCATIONAL SER...,2 CEDAR ST,NEWARK,NJ,7102,BUSINESS,HIGH,2/24/2016,"IsMailable,IsConnected,IsPorted"
171,1201950208,PATRICIA,HARWELL,None,None,None,None,None,8885795910,Service Management System (SMS/800),INTEGRITY ROOFING & EXTERIORS,None,None,None,None,BUSINESS,LOW,None,IsTollFreeNumber
172,3845830532,TERRY,LINVILLE,None,None,None,None,None,8885795910,Service Management System (SMS/800),INTEGRITY ROOFING & EXTERIORS,None,None,None,None,BUSINESS,LOW,None,IsTollFreeNumber
173,4203970035,MARISOL,PABON,None,None,None,None,None,8885795910,Service Management System (SMS/800),INTEGRITY ROOFING & EXTERIORS,None,None,None,None,BUSINESS,LOW,None,IsTollFreeNumber
174,5104091671,KATE,SCHOOLWERTH,L-579 OHSU,3181 SW SAM JACKSON PARK RD,PORTLAND,OR,97239,5087559535,XO MASSACHUSETTS,DELROSARIO MARIA MD,330 GROVE ST,WORCESTER,MA,1605,BUSINESS,HIGH,12/15/2016,"IsMailable,IsConnected,IsPorted"
175,3547890981,NIMI,SINGH,None,717 DELAWARE ST SE STE 1 # 383,MINNEAPOLIS,MN,55414,6126264260,ALLSTREAM,UNIV MN,717 DELAWARE ST SE STE 1,MINNEAPOLIS,MN,55414,None,LOW,8/26/2014,"IsMailable,IsPorted"
176,4178070059,DAVID,MANN,None,None,None,None,None,8475590090,COMCAST PHONE-IL,NONA M CRAIG MD PHYSICIANS SURGEONS DERMATOLOGY,1220 MEADOW RD,NORTHBROOK,IL,60062,BUSINESS,LOW,9/18/2015,"IsMailable,IsPorted"
177,70402861221,AQEEL,AHMED,None,240 W FIRST ST,EDISON,NJ,8820,7013648900,CONSOLIDATED COMMS,ESSENTIA HEALTH PEDIATRICSHEMATOLOGYONCOLOGY,3902 13TH AVE S,FARGO,ND,58103,BUSINESS,HIGH,None,"IsMailable,IsConnected"
178,4177040351,KRISTIN,MELNICK,None,2315 8TH ST,LEWISTON,ID,83501,5094743131,"XO WASHINGTON, INC.",PROVIDENCE SACRED HEART MEDICAL CENTER DOCTORS,101 W 8TH AVE,SPOKANE,WA,99204,BUSINESS,HIGH,11/17/2004,"IsMailable,IsConnected,IsPorted"
179,74801950225,MARIA FE,VILLOSIS,None,None,None,None,None,8187864910,PACIFIC BELL,KYU H KIM,15243 VANOWEN ST,VAN NUYS,CA,91405,RESIDENTIAL,HIGH,None,"IsMailable,IsConnected"
180,3901881595,ROGER,THOMPSON,None,608 NW 9TH ST STE 5100,OKLAHOMA CITY,OK,73102,7326710860,LEVEL 3 COMM - NJ,ROGER M THOMPSON MD PHYSICIANS SURGEONS,140 TINDALL RD,MIDDLETOWN,NJ,7748,BUSINESS,HIGH,1/12/2018,"IsMailable,IsConnected,IsPorted,IsPossiblePort..."
181,502090909,YU,XIE,None,127 S SAN VICENTE BLVD RM A3308,LOS ANGELES,CA,90048,4156001051,PACIFIC BELL,CA PAC MED CTR,2340 CLAY ST,SAN FRANCISCO,CA,94115,BUSINESS,LOW,None,IsMailable
182,2879850781,SUSAN,VAN DELLEN,None,940 RIVER CENTRE DR,PORT HURON,MI,48060,4809485045,QWEST CORPORATION,DYKE VAN AESTHETICS MD PHYSICIANS GENERAL,5206 N SCOTTSDALE RD,PARADISE VALLEY,AZ,85253,BUSINESS,HIGH,5/5/2005,"IsMailable,IsConnected,IsPorted"
183,1205880743,STEVEN,RUDD,THE RADIOLOGY CENTER,736 PAGE AVE,LYNDHURST,NJ,7071,5415531196,QWEST CORPORATION,WARM SPRINGS HEALTH WELLNESS CENTER RADIO,1270 KOT NUM RD,WARM SPRINGS,OR,97761,BUSINESS,HIGH,None,IsConnected
184,4114810253,KIM,HANLON,None,None,None,None,None,5703317615,COMCAST PHONE - PA,SURGICAL SPECIALTY CTRNE PA MEDICAL CENTERS,190 WELLES ST STE 150,KINGSTON,PA,18704,BUSINESS,HIGH,10/31/2016,"IsMailable,IsConnected,IsPorted"
185,91502740429,MOHAMED,EL MOUELHI,None,1 HEALTH PLZ BLDG 435-1182,EAST HANOVER,NJ,7936,6462274900,BROADVIEW NTWKS - NY,355 LEXINGTON A,None,NEW YORK,NY,10016,BUSINESS,MED,2/24/2005,"IsConnected,IsPorted"
186,5002830177,ROSS,DYKSTRA,KAISER PERMANENTE MED CENTER,1200 EL CAMINO REAL,S SAN FRAN,CA,94080,6507422000,PACIFIC BELL,KAISER PERMANENTE MEDICAL CENTERSO SAN FRANCISCO,1200 EL CAMINO REAL,SOUTH SAN FRANCISCO,CA,94080,BUSINESS,HIGH,None,"IsMailable,IsConnected"
187,3503060344,MICHAEL,MIRHADI,MARSHALL HOSP,1100 MARSHALL WAY,PLACERVILLE,CA,95667,7144565705,PACIFIC BELL,U C I MED CTR,None,ORANGE,CA,92856,BUSINESS,MED,None,IsConnected
188,511920078,AELIZABETH,BRICE,CAPE COD HOSPITAL,27 PARK ST,HYANNIS,MA,2601,7817448000,VERIZON NEW ENGLAND,LAHEY CLINIC APPOINTMENT OFFICE,None,BURLINGTON,MA,1803,BUSINESS,HIGH,None,IsConnected

In [69]:
# data = pd.read_csv('infinite_csvs.csv')
# connect = data[data['COMMENTS'].isin(['COMPLETE'])]
# connect=connect.fillna('None')


conn = analyze_numbers(connect)

In [47]:
connect = connect.drop_duplicates()

In [52]:
connect.shape[0]

445

In [53]:
wrong.shape[0]

189

In [75]:
working = pd.DataFrame({'Wrong': wron, 'Connected':conn})

In [76]:
working['Wrong %'] = working['Wrong']/wrong.shape[0]*100
working['Connected %'] = working['Connected']/connect.shape[0]*100

In [77]:
working

                        Wrong  Connected    Wrong %  Connected %
Address Matches            47        225  24.867725    50.561798
Business Phone            166        372  87.830688    83.595506
City Matches               77        351  40.740741    78.876404
Connected                 124        311  65.608466    69.887640
First Name Match           11         74   5.820106    16.629213
High Quality              113        277  59.788360    62.247191
Last Name Match             8         74   4.232804    16.629213
Low Quality                60        119  31.746032    26.741573
Mailable                  143        347  75.661376    77.977528
Medium Quality             15         43   7.936508     9.662921
New Count                  10         90   5.291005    20.224719
No Address                 37         88  19.576720    19.775281
No Date                    64        166  33.862434    37.303371
No Name                     1          6   0.529101     1.348315
Ported                    125        279  66.137566    62.696629
Possibly Disconnected      15         14   7.936508     3.146067
Possibly Portable VOIP     12         19   6.349206     4.269663
Relevant Name             134        330  70.899471    74.157303
Residential Phone          17         56   8.994709    12.584270
State Match               123        422  65.079365    94.831461
Unknown Contact             1          6   0.529101     1.348315
Wireless                    0          1   0.000000     0.224719
Workplace Match             2         16   1.058201     3.595506
ZipCode Matches            66        319  34.920635    71.685393

In [ ]:
no_address_match = 0
no_city_match = 0
no_zipcode_match = 0
unknowncount = 0
disconnectedcount = 0
no_first_name_match = 0
no_last_name_match = 0 
no_workplace_match = 0
no_state_match = 0

In [153]:
def check_variables(row,variable_pair):
    
    address_no_match = True
    zipcode_no_match = False
    city_no_match = False
    unknowncount = False
    disconnectedcount = False
    no_first_name_match = False
    no_last_name_match = False
    no_workplace_match = False
    state_no_match = False

    gpi_add = g.translate_addr(str(row.ContactAddressOut))
    ws_add = g.translate_addr(str(row.OFFICE_ADDRESS_LINE_2))
    if gpi_add != 'NONE':
        if gpi_add in ws_add or ws_add in gpi_add:
            address_no_match = False
    if g.clean_zipcode(row.OFFICE_ADDRESS_ZIP) != g.clean_zipcode(row.ContactZipOut):
        zipcode_no_match = True
    if 'IsUnknownContact' in str(row.NoteDescriptions):
        unknowncount = True
    if 'IsPossibleDisconnected' in str(row.NoteDescriptions):
        disconnectedcount = True
        
    if str(row.OFFICE_ADDRESS_CITY) not in str(row.ContactCityOut):
        city_no_match = True

    if row.ContactStateOut != row.OFFICE_ADDRESS_STATE:
        state_no_match = True

    if str(row.PHYSICIAN_LAST_NAME).lower() not in str(row.ContactNameOut).lower():
        no_last_name_match = True
    if str(row.PHYSICIAN_FIRST_NAME).lower() not in str(row.ContactNameOut).lower():
        no_first_name_match = True

    if str(row.OFFICE_ADDRESS_LINE_1).lower() not in str(row.ContactNameOut).lower():
        no_workplace_match = True
        
    new_dict = {
        'Address Mismatches': address_no_match,
        'ZipCode Mismatches': zipcode_no_match,
        'Unknown Contact': unknowncount,
        'Possibly Disconnected': disconnectedcount,
        'City Mismatches': city_no_match,
        'First Name Mismatch':no_first_name_match,
        'Last Name Mismatch':no_last_name_match,
        'Workplace Mismatch': no_workplace_match,
        'State Mismatch': state_no_match, 
        }
    conclusion = False
    if new_dict[variable_pair[0]]==True or new_dict[variable_pair[1]]==True:
        if new_dict[variable_pair[2]]==True and new_dict[variable_pair[3]]==True:
                conclusion=True
    return(conclusion)

In [79]:
def try_variables(pair_list, df):
    list_of_dicts =[]
    for pair in pair_list:
        new_dict={}
        new_dict['Pair']=pair
        count = 0 
        for row in df.itertuples():
#             if row.status=='disconnected' or row.status=='disconnected-70':
            if check_variables(row, pair)==True:
                count += 1
        new_dict['Count']=count
        list_of_dicts.append(new_dict)
    return(list_of_dicts)

In [80]:
variables = ['Address Mismatches','ZipCode Mismatches','Unknown Contact','Possibly Disconnected','City Mismatches','First Name Mismatch','Last Name Mismatch','Workplace Mismatch','State Mismatch']

In [81]:
pair_list = []
for variable in variables:
    print(variable)
    variable1=variable
    variables.remove(variable1)
    for v in variables:
        variable2 = v
        pair = (variable1, variable2)
        pair_list.append(pair)

Address Mismatches
Unknown Contact
City Mismatches
Last Name Mismatch
State Mismatch

In [154]:
new_wrong_pairs = try_variables(new_pairs, wrong)

In [155]:
new_connected_pairs = try_variables(new_pairs, connect)

In [156]:
new_wrong_df = pd.DataFrame(new_wrong_pairs)
new_connected_df = pd.DataFrame(new_connected_pairs)
new_merged = pd.merge(new_wrong_df, new_connected_df, on='Pair', suffixes = ('_wrong', '_connected'))
new_merged.sort_values(by = ['Count_wrong'], ascending=False)

,Count_wrong,Pair,Count_connected
0,134,"(Address Mismatches, ZipCode Mismatches, Last ...",191
3,108,"(Last Name Mismatch, Workplace Mismatch, City ...",77
2,107,"(Last Name Mismatch, Workplace Mismatch, ZipCo...",72
1,105,"(City Mismatches, State Mismatch, Last Name Mi...",81
4,66,"(Last Name Mismatch, Workplace Mismatch, State...",23
5,66,"(Last Name Mismatch, Workplace Mismatch, Addre...",23

In [157]:
new_merged['Wrong %'] = new_merged['Count_wrong']/wrong.shape[0]*100
new_merged['Connected %'] = new_merged['Count_connected']/connect.shape[0]*100

In [158]:
new_merged.sort_values(by = ['Connected %'])

,Count_wrong,Pair,Count_connected,Wrong %,Connected %
4,66,"(Last Name Mismatch, Workplace Mismatch, State...",23,34.920635,5.168539
5,66,"(Last Name Mismatch, Workplace Mismatch, Addre...",23,34.920635,5.168539
2,107,"(Last Name Mismatch, Workplace Mismatch, ZipCo...",72,56.613757,16.179775
3,108,"(Last Name Mismatch, Workplace Mismatch, City ...",77,57.142857,17.303371
1,105,"(City Mismatches, State Mismatch, Last Name Mi...",81,55.555556,18.202247
0,134,"(Address Mismatches, ZipCode Mismatches, Last ...",191,70.899471,42.921348

In [94]:
pair_list

[('Address Mismatches', 'ZipCode Mismatches'),
 ('Address Mismatches', 'Unknown Contact'),
 ('Address Mismatches', 'Possibly Disconnected'),
 ('Address Mismatches', 'City Mismatches'),
 ('Address Mismatches', 'First Name Mismatch'),
 ('Address Mismatches', 'Last Name Mismatch'),
 ('Address Mismatches', 'Workplace Mismatch'),
 ('Address Mismatches', 'State Mismatch'),
 ('Unknown Contact', 'ZipCode Mismatches'),
 ('Unknown Contact', 'Possibly Disconnected'),
 ('Unknown Contact', 'City Mismatches'),
 ('Unknown Contact', 'First Name Mismatch'),
 ('Unknown Contact', 'Last Name Mismatch'),
 ('Unknown Contact', 'Workplace Mismatch'),
 ('Unknown Contact', 'State Mismatch'),
 ('City Mismatches', 'ZipCode Mismatches'),
 ('City Mismatches', 'Possibly Disconnected'),
 ('City Mismatches', 'First Name Mismatch'),
 ('City Mismatches', 'Last Name Mismatch'),
 ('City Mismatches', 'Workplace Mismatch'),
 ('City Mismatches', 'State Mismatch'),
 ('Last Name Mismatch', 'ZipCode Mismatches'),
 ('Last Name Mismatch', 'Possibly Disconnected'),
 ('Last Name Mismatch', 'First Name Mismatch'),
 ('Last Name Mismatch', 'Workplace Mismatch'),
 ('Last Name Mismatch', 'State Mismatch'),
 ('State Mismatch', 'ZipCode Mismatches'),
 ('State Mismatch', 'Possibly Disconnected'),
 ('State Mismatch', 'First Name Mismatch'),
 ('State Mismatch', 'Workplace Mismatch')]

In [146]:
new_pairs = [('Address Mismatches', 'ZipCode Mismatches', 'Last Name Mismatch', 'Workplace Mismatch'),
 ('City Mismatches', 'State Mismatch', 'Last Name Mismatch', 'Workplace Mismatch'),
 ('Last Name Mismatch', 'Workplace Mismatch', 'ZipCode Mismatches', 'City Mismatches'),
 ('Last Name Mismatch', 'Workplace Mismatch', 'City Mismatches', 'Address Mismatches'),
 ('Last Name Mismatch', 'Workplace Mismatch', 'State Mismatch', 'ZipCode Mismatches'),
 ('Last Name Mismatch', 'Workplace Mismatch', 'Address Mismatches', 'State Mismatch')]

In [7]:
data = pd.read_csv('numbers_and_scores.csv')

In [8]:
data = data.fillna('None')

In [11]:
def variable_breakdown(dataframe):
    
    LIST_OF_DICTS = []
    
    
    for row in dataframe.itertuples():

        address_no_match = 1
        zipcode_no_match = 0
        city_no_match = 0
        unknowncount = 0
        disconnectedcount = 0
        no_first_name_match = 0
        no_last_name_match = 0
        no_workplace_match = 0
        state_no_match = 0
        
        low_quality = 0
        no_date  = 0
        not_relevant = 0
        not_high_quality = 0
        not_mailable = 0 
        residential = 0
        no_name = 0 
        no_address = 0 
        not_connected = 0
        not_ported = 0 
        inf = 0 
        

        gpi_add = g.translate_addr(str(row.ContactAddressOut))
        ws_add = g.translate_addr(str(row.OFFICE_ADDRESS_LINE_2))
        if gpi_add != 'NONE':
            if gpi_add in ws_add or ws_add in gpi_add:
                address_no_match = 0
        if g.clean_zipcode(row.OFFICE_ADDRESS_ZIP) != g.clean_zipcode(row.ContactZipOut):
            zipcode_no_match = 1
        if 'IsUnknownContact' in str(row.NoteDescriptions):
            unknowncount = 1
        if 'IsPossibleDisconnected' in str(row.NoteDescriptions):
            disconnectedcount = 1

        if str(row.OFFICE_ADDRESS_CITY) not in str(row.ContactCityOut):
            city_no_match = 1

        if row.ContactStateOut != row.OFFICE_ADDRESS_STATE:
            state_no_match = 1

        if str(row.PHYSICIAN_LAST_NAME).lower() not in str(row.ContactNameOut).lower():
            no_last_name_match = 1
        if str(row.PHYSICIAN_FIRST_NAME).lower() not in str(row.ContactNameOut).lower():
            no_first_name_match = 1

        if str(row.OFFICE_ADDRESS_LINE_1).lower() not in str(row.ContactNameOut).lower():
            no_workplace_match = 1
            
        if g.is_healthy(row.ContactNameOut)==False: 
            not_relevant = 1
                
            

        if 'IsMailable' not in str(row.NoteDescriptions):
            not_mailable = 1
        if 'IsConnected' not in str(row.NoteDescriptions):
            not_connected = 1
        if 'IsPorted' not in str(row.NoteDescriptions):
            not_ported = 1

        if row.ContactAddressOut == 'None':
            no_address = 1
        if row.DateOfPorting == 'None':
            no_date = 1

        if row.ContactPhoneType == 'RESIDENTIAL':
            residential = 1
        if row.ContactQualityScore == 'LOW':
            low_quality = 1
        if row.ContactQualityScore != 'HIGH':
            not_high_quality = 1

        if row.ContactNameOut =='None':
            no_name = 1
                
        if 'INF' in str(row.NoteDescriptions):
            inf = 1


        new_dict = {
            'OFFICE_TELEPHONE': row.OFFICE_TELEPHONE,
            'AddressMismatch': address_no_match,
            'ZipCodeMismatch': zipcode_no_match,
            'UnknownContact': unknowncount,
            'PossiblyDisconnected': disconnectedcount,
            'CityMismatch': city_no_match,
            'FirstNameMismatch':no_first_name_match,
            'LastNameMismatch':no_last_name_match,
            'WorkplaceMismatch': no_workplace_match,
            'StateMismatch': state_no_match, 
            'NoAddress': no_address,
            'NoDate': no_date,
            'IrrelevantName': not_relevant,
            'ResidentialPhone': residential,
            'LowQuality': low_quality,
            'NotHighQuality': not_high_quality,
            'NotMailable': not_mailable,
            'NotConnected': not_connected,
            'NotPorted': not_ported,
            'NoName': no_name,
            'INF': inf,
            'Label': row.COMMENTS,
            'Score': row.pred_probability,
            'Class': row.pred_class,
            'ME': row.ppd_me,
            'Description': row.pe_description
            }

        LIST_OF_DICTS.append(new_dict)

    return(LIST_OF_DICTS)

In [13]:
BOOF = variable_breakdown(data)

In [14]:
FOOB = pd.DataFrame(BOOF)
FOOB.to_csv('scored_numbers.csv')

In [203]:
merged = merged.fillna('None')
numbers = variable_breakdown(merged)
numbers_df = pd.DataFrame(numbers)

In [204]:
wrong = wrong.fillna('None')
wrong_variables = variable_breakdown(wrong)

In [205]:
wrong_variables_df = pd.DataFrame(wrong_variables)

In [202]:
numbers_df.groupby('AddressMismatch').sum()

,CityMismatch,FirstNameMismatch,INF,IrrelevantName,LastNameMismatch,LowQuality,NoAddress,NoDate,NoName,NotConnected,NotHighQuality,NotMailable,NotPorted,OFFICE_TELEPHONE,PossiblyDisconnected,ResidentialPhone,StateMismatch,UnknownContact,WorkplaceMismatch,ZipCodeMismatch
AddressMismatch,,,,,,,,,,,,,,,,,,,,
0,4,75,27,25,67,54,0,70,0,54,54,0,70,620410058979,27,12,0,0,104,0
1,243,340,85,217,320,203,167,226,40,249,300,170,226,2254985346414,85,91,105,32,364,316

In [208]:
connect.fillna('None')
connect_variables = variable_breakdown(connect)
connect_variables_df = pd.DataFrame(connect_variables)
connect_variables_df.groupby('AddressMismatch').sum()

,CityMismatch,FirstNameMismatch,INF,IrrelevantName,LastNameMismatch,LowQuality,NoAddress,NoDate,NoName,NotConnected,NotHighQuality,NotMailable,NotPorted,OFFICE_TELEPHONE,PossiblyDisconnected,ResidentialPhone,StateMismatch,UnknownContact,WorkplaceMismatch,ZipCodeMismatch
AddressMismatch,,,,,,,,,,,,,,,,,,,,
0,17,178,9,45,177,49,0,76,0,49,49,0,76,1287725472951,9,29,0,0,213,1
1,77,193,5,67,194,70,88,90,6,85,119,98,90,1255719067684,5,27,23,6,216,125

In [137]:
connect_sample = connect_variables_df.sample(189)

In [209]:
all_variables = pd.concat([connect_variables_df, wrong_variables_df])

In [161]:
all_variables.to_csv('wrong_and_connect2.csv', index = False)

In [210]:
all_variables2 = pd.concat([all_variables, numbers_df])
all_variables2.to_csv('wrong_and_connect4.csv', index = False)

In [211]:
all_variables2

,AddressMismatch,CityMismatch,FirstNameMismatch,INF,IrrelevantName,LastNameMismatch,LowQuality,NoAddress,NoDate,NoName,...,NotMailable,NotPorted,OFFICE_TELEPHONE,PossiblyDisconnected,ResidentialPhone,StateMismatch,UnknownContact,WorkplaceMismatch,ZipCodeMismatch,label
0,1,1,1,0,0,1,0,1,0,0,...,1,0,6233123020,0,0,1,0,1,1,connected
1,1,1,1,0,1,1,0,1,0,0,...,1,0,4707323585,0,1,1,0,1,1,connected
2,0,0,1,0,1,1,0,0,0,0,...,0,0,5594326212,0,0,0,0,0,0,connected
3,1,1,1,0,1,1,0,1,0,0,...,1,0,4143261514,0,1,1,0,1,1,connected
4,1,0,1,0,0,1,0,0,1,0,...,0,1,3527428830,0,0,0,0,1,0,connected
5,1,0,1,0,0,1,0,0,1,0,...,0,1,3527428830,0,0,0,0,1,0,connected
6,0,0,1,0,1,1,1,0,1,0,...,0,1,3522735670,0,0,0,0,1,0,connected
7,0,0,1,0,0,1,0,0,0,0,...,0,0,3034445110,0,0,0,0,1,0,connected
8,0,0,1,0,0,1,0,0,0,0,...,0,0,3034445110,0,0,0,0,1,0,connected
9,0,0,1,0,0,1,0,0,0,0,...,0,0,6038801590,0,0,0,0,1,0,connected
10,0,0,1,0,0,1,0,0,0,0,...,0,0,6038801590,0,0,0,0,1,0,connected
11,0,0,0,0,0,0,0,0,1,0,...,0,1,9417921717,0,0,0,0,1,0,connected
12,1,0,1,0,0,1,1,1,0,0,...,1,0,4143894900,0,0,0,0,1,1,connected
13,1,0,1,0,0,1,1,1,0,0,...,1,0,4143894900,0,0,0,0,1,1,connected
14,1,1,1,0,1,1,0,1,1,1,...,1,1,7183342483,0,0,1,1,1,1,connected
15,1,1,1,0,1,1,0,1,1,1,...,1,1,7183342483,0,0,1,1,1,1,connected
16,1,0,0,0,0,0,0,0,1,0,...,0,1,8138778665,0,0,0,0,1,0,connected
17,1,0,1,0,0,0,0,0,0,0,...,0,0,2053132650,0,0,0,0,1,0,connected
18,1,0,1,0,0,0,0,0,0,0,...,0,0,2053132650,0,0,0,0,1,0,connected
19,1,0,1,0,1,1,1,1,0,0,...,1,0,9738424272,0,0,0,0,1,0,connected
20,1,0,1,0,1,1,1,1,0,0,...,1,0,9738424272,0,0,0,0,1,0,connected
21,1,0,1,1,0,1,1,1,0,0,...,1,0,6059776842,1,0,0,0,1,1,connected
22,0,0,1,0,1,1,1,0,0,0,...,0,0,3605765060,0,0,0,0,1,0,connected
23,0,0,1,0,0,0,0,0,0,0,...,0,0,5614951337,0,0,0,0,1,0,connected
24,1,1,1,0,0,1,0,1,0,0,...,1,0,6166857450,0,0,1,0,1,1,connected
25,1,1,0,0,1,1,1,1,1,0,...,1,1,7878201763,0,1,0,0,1,1,connected
26,1,1,0,0,1,1,1,1,1,0,...,1,1,7878201763,0,1,0,0,1,1,connected
27,0,0,0,1,0,1,1,0,0,0,...,0,0,5178874305,1,0,0,0,0,0,connected
28,1,0,0,0,0,0,0,0,0,0,...,0,0,5133210833,0,0,0,0,1,0,connected
29,1,0,0,0,0,0,0,0,1,0,...,0,1,5184827964,0,0,0,0,1,1,connected
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,1,1,1,0,1,1,1,0,0,0,...,0,0,6176672300,0,1,1,0,1,1,wrong
469,1,0,1,0,0,1,0,0,0,0,...,0,0,8123332731,0,0,0,0,1,1,wrong
470,1,0,1,0,0,1,1,0,1,0,...,0,1,5175481246,0,0,0,0,1,0,wrong
471,1,0,1,0,1,1,1,0,0,0,...,0,0,3172780944,0,0,0,0,1,0,wrong
472,1,1,1,0,1,1,1,0,0,0,...,0,0,2124551010,0,0,1,0,1,1,wrong
473,1,1,1,0,0,1,0,1,0,0,...,1,0,5136244565,0,0,1,0,1,1,wrong
474,1,1,1,0,1,1,1,1,0,0,...,1,0,3035303755,0,1,0,0,1,1,wrong
475,1,1,1,0,0,1,0,1,0,0,...,1,0,6169138650,0,0,0,0,1,1,wrong
476,0,0,1,0,0,1,0,0,0,0,...,0,0,3176310420,0,0,0,0,1,0,wrong
477,1,1,1,0,1,1,0,1,0,0,...,1,0,6032772200,0,0,1,0,1,1,wrong
478,1,1,1,0,1,1,0,1,1,1,...,1,1,8589665674,0,0,1,1,1,1,wrong
479,0,0,0,0,0,0,0,0,1,0,...,0,1,8083732167,0,0,0,0,1,0,wrong
480,1,1,0,1,0,0,1,0,1,0,...,0,1,6265715955,1,0,0,0,1,1,wrong
481,1,1,0,0,0,0,0,0,1,0,...,0,1,2145538545,0,0,1,0,1,1,wrong
482,1,1,0,0,0,0,1,0,1,0,...,0,1,3149189111,0,0,1,0,1,1,wrong
483,1,0,1,1,0,1,1,0,0,0,...,0,0,4028846700,1,0,0,0,1,1,wrong
484,1,1,1,1,1,1,1,0,1,0,...,0,1,2055531687,1,1,0,0,1,1,wrong
485,1,0,1,0,1,1,0,1,0,0,...,1,0,6195166606,0,0,0,0,1,1,wrong
486,1,1,1,1,0,1,1,0,1,0,...,0,1,5098354672,1,0,0,0,1,1,wrong
487,1,1,1,0,1,1,1,0,1,0,...,0,1,9498244356,0,0,0,0,1,1,wrong
488,1,0,1,0,0,1,1,0,0,0,...,0,0,5023579729,0,0,0,0,0,1,wrong
489,0,0,0,0,1,1,1,0,0,0,...,0,0,3056432283,0,0,0,0,1,0,wrong
490,1,0,1,0,1,0,1,0,1,0,...,0,1,4144755550,0,0,0,0,1,0,wrong
491,1,0,1,0,0,1,0,0,0,0,...,0,0,7312560526,0,0,0,0,1,0,wrong
492,0,1,1,0,0,1,0,0,0,0,...,0,0,9096520220,0,0,0,0,1,0,wrong
493,0,1,1,0,0,1,1,0,1,0,...,0,1,4137474170,0,0,0,0,1,0,wrong
494,1,1,0,0,1,0,0,0,0,0,...,0,0,3256911053,0,1,0,0,1,1,wrong
495,1,1,1,0,1,0,0,0,1,0,...,0,1,2156724726,0,0,0,0,1,1,wrong
496,0,0,1,0,0,1,0,0,0,0,...,0,0,5123418001,0,0,0,0,1,0,wrong
497,1,0,0,1,1,0,1,0,1,0,...,0,1,6153271711,1,1,0,0,1,1,wrong

In [ ]:
            
    low_quality = 0
        no_date  = 0
        no_relevant = 0
        not_high_quality = 0
        not_mailable = 0 
        residential = 0
        no_name = 0 
        no_address = 0 
        not_connected = 0
        not_ported = 0 
        inf = 0
    
    if g.is_healthy(row.ContactNameOut)==False: 
                healthcount = 1
                
            

            if 'IsMailable' not in str(row.NoteDescriptions):
                not_mailable = 1
            if 'IsConnected' not in str(row.NoteDescriptions):
                not_connected = 1
            if 'IsPorted' not in str(row.NoteDescriptions):
                not_ported = 1

            if row.ContactAddressOut == 'None':
                no_address = 1
            if row.DateOfPorting == 'None':
                no_date = 1

            if row.ContactPhoneType == 'RESIDENTIAL':
                residential = 1
            if row.ContactQualityScore == 'LOW':
                low_quality = 1
            if row.ContactQualityScore != 'HIGH':
                not_high_quality = 1

            if row.ContactNameOut =='None':
                no_name = 1
                
            if 'INF' in str(row.NoteDescriptions):
                inf = 1

    new_dict = {
        'NoAddress': no_address_count,
        'NoDate': no_date_count,
        'IrrelevantName': healthcount,
        'ResidentialPhone': residential_count,
        'LowQuality': low_count,
        'NotHighQuality': high_count,
        'NotMailable': mailcount,
        'NotConnected': connectcount,
        'NotPorted': portcount,
        'NoName': no_name,
        'INF': inf
        }
        
    return(new_dict)