In [1]:
import pandas as pd

In [3]:
connected_new = pd.read_csv('getphone_connected_rpv.csv')
disconnected_new = pd.read_csv('getphone_disconnected_rpv.csv')
already_done = pd.read_csv('already_done.csv')

In [86]:
med_words = ['oncology','primary care','radiology','pathology','pathologists','glaucoma','cancer', 'cardiology', 'neurology', 'family care', 'pulmonary', 'anesthesia', 'orthope', 'urgent care', 'allergy', 'kidney', 'surgery', 'hosp', 'mri', 'throat', 'dentist', 'med', 'clinic', 'health', 'gastroenter','anesthesiologist','patient','physician','surgeon','doctor','hospital', 'md', 'medical', 'pediatrics', 'm.d.']

In [74]:
def clean_zipcode(zipcode):
    zipcode=str(zipcode)
    zipcode = zipcode.replace(".0","")
    if len(zipcode)==3:
        zipcode = "00"+zipcode
    if len(zipcode)==4: 
        zipcode = "0"+zipcode
    else:
        zipcode = zipcode[0:5]
    return(zipcode)

In [88]:
connected_new = connected_new.fillna('None')
analyze_numbers(connected_new)

SANTODMNGO DR
None
None
MIKA SINANAN
None
RANDOLPH R FACS EVANS
LYNN M GAUFIN
WSUPG
MCKESSON CORPORATION
None
VELASCO JUAN C
JOHNS HOPKINS H
FAISON, SARAH
SEDA RODRIGUEZ JAFFED
KAISER PERMANEN
NEW ENGLAND EYE
None
MAENZA, SARI DEBRA
CAROLINA N CALL
FLORIDA STATE OF AGRICULTURE & CONSUMER SERVICES
NORTHERN INYO H
C JORGE
477047E3VU37800
JOHNS HOPKINS H
None
THE ANGELES CLI
P RIO
HARRY H POTE
US GOVERNMENT
LEHIGH VLLY
THE VILLA AT MIDDLETON VILLAGE NURSING HOMES LIFE
None
MICHELLE MORINGLANE
MARTHA A MICHEL
ANITA CHERIYAN
HOWARD UNIV
V UTMB
CRISTOJOHN SAMUEL DR
ESTHETICA OF NEWPORT BEACH
None
KAISER PERMANEN
NW MEMORIAL HOS
None
TAYYAB DIWAN
DUKE UNIVERSITY
LINDA KATELL
JARED LEWIS
KUSUM BHANDARI
None
IU HLTH BLOOMIN
SC EASTCONWAY
GRECO GIAMPAOLO

{'Address Matches': 39,
 'City Matches': 79,
 'ZipCode Matches': 62,
 'No Address': 46,
 'No Date': 56,
 'Relevant Name': 84,
 'Business Phone': 104,
 'Residential Phone': 16,
 'Low Quality': 44,
 'Medium Quality': 18,
 'High Quality': 64,
 'Mailable': 89,
 'Connected': 77,
 'Ported': 80,
 'Not Valid': 0,
 'Unknown Contact': 10,
 'Possibly Disconnected': 8,
 'Possibly Portable VOIP': 1,
 'Wireless': 0,
 'First Name Match': 18,
 'Last Name Match': 17,
 'Workplace Match': 5,
 'State Match': 109,
 'No Name': 10}

In [87]:
def analyze_numbers(dataframe):
    
    
    address_match = 0
    city_match = 0
    zipcode_match = 0
    healthcount = 0
    mailcount = 0
    connectcount = 0
    portcount = 0
    novalidcount = 0
    unknowncount = 0
    disconnectedcount = 0
    voipcount = 0
    wirelesscount = 0
    no_address_count = 0
    no_date_count = 0
    business_count = 0
    residential_count = 0
    low_count = 0
    high_count = 0
    med_count = 0
    first_name_match = 0
    last_name_match = 0 
    workplace_match = 0
    state_match = 0
    no_name = 0
        


    for row in dataframe.itertuples():
        if str(row.Address) in str(row.OFFICE_ADDRESS_LINE_2) or str(row.OFFICE_ADDRESS_LINE_2) in str(row.Address):
            address_match += 1
        if str(row.OFFICE_ADDRESS_CITY) in str(row.City):
            city_match += 1
        if clean_zipcode(row.OFFICE_ADDRESS_ZIP) == clean_zipcode(row.Zipcode):
            zipcode_match += 1
        
        if row.State == row.OFFICE_ADDRESS_STATE:
            state_match += 1
        
        if str(row.PHYSICIAN_LAST_NAME).lower() in str(row.Name).lower():
            last_name_match +=1
        if str(row.PHYSICIAN_FIRST_NAME).lower() in str(row.Name).lower():
            first_name_match +=1
        
        if str(row.OFFICE_ADDRESS_LINE_1).lower() in str(row.Name).lower():
            workplace_match += 1

        healthy = False
        for word in med_words:
            if word in str(row.Name).lower():
                healthy = True
        if healthy == True:    
            healthcount += 1
        if healthy == False:
            print(f'{row.Name}')

        if 'IsMailable' in str(row.Notes):
            mailcount += 1
        if 'IsConnected' in str(row.Notes):
            connectcount += 1
        if 'IsPorted' in str(row.Notes):
            portcount += 1
        if 'NotValid' in str(row.Notes):
            novalidcount += 1
        if 'IsUnknownContact' in str(row.Notes):
            unknowncount += 1
        if 'IsPossibleDisconnected' in str(row.Notes):
            disconnectedcount += 1
        if 'IsPossiblePortableVOIP' in str(row.Notes):
            voipcount += 1
        if 'IsWireless' in str(row.Notes):
            wirelesscount += 1

        if row.Address == 'None':
            no_address_count += 1
        if row.Date == 'None':
            no_date_count += 1
        if row.PhoneType == 'BUSINESS':
            business_count += 1
        if row.PhoneType == 'RESIDENTIAL':
            residential_count += 1
        if row.QualityScore == 'LOW':
            low_count += 1
        if row.QualityScore == 'HIGH':
            high_count += 1
        if row.QualityScore == 'MED':
            med_count += 1
        if row.Name =='None':
            no_name += 1

    new_dict = {
        'Address Matches': address_match,
        'City Matches': city_match,
        'ZipCode Matches': zipcode_match,
        'No Address': no_address_count,
        'No Date': no_date_count,
        'Relevant Name': healthcount,
        'Business Phone': business_count,
        'Residential Phone': residential_count,
        'Low Quality': low_count,
        'Medium Quality': med_count,
        'High Quality': high_count,
        'Mailable': mailcount,
        'Connected': connectcount,
        'Ported': portcount,
        'Not Valid': novalidcount,
        'Unknown Contact': unknowncount,
        'Possibly Disconnected': disconnectedcount,
        'Possibly Portable VOIP': voipcount,
        'Wireless': wirelesscount,
        'First Name Match':first_name_match,
        'Last Name Match':last_name_match,
        'Workplace Match': workplace_match,
        'State Match': state_match, 
        'No Name': no_name
        }
        
    return(new_dict)

In [89]:
disconnected_new = disconnected_new.fillna('None')
analyze_numbers(disconnected_new)

PHX CHILDRENS H
MATTHEW TROUARD
JOE DR GOCHOCO PLLC
DONALD A MCEACHERN
ADAPT OF TEXAS
SAEED M AWAN
LEE STRATTON
GILBREATH & PARK
SUSAN NAKAMURA
None
ALTA VIEW EYE CARE CENTER
STEVEN Y PARK
LANDRYS
TAT S RITHAPORN
TWIN CITIES,MN
HERBERT NORTON
JOSE IGLESIAS
None
SANDOVAL JAIME DAVID
MCREYNOLDS EDWA
HLTH & HUMAN SV
ALDO J SURACI
LARRY BRUNO
MARY LEE
NEVADA STATE BANK
ROBBIE BRAND
None
ASSOCIATED CHES
MARIA PEREZ
COMMUNITY RADIOLOGY ASSOCIATES INC
JOHNS HOPKINS H
PARADISE MASSAGE AND SKIN CARE MASSAGE THERAPISTS
ERIKA MILES
KEITH D LOBEL
E SW
None
FLORIDA STATE OF
B HENDRIK

{'Address Matches': 16,
 'City Matches': 37,
 'ZipCode Matches': 26,
 'No Address': 19,
 'No Date': 62,
 'Relevant Name': 35,
 'Business Phone': 49,
 'Residential Phone': 18,
 'Low Quality': 38,
 'Medium Quality': 6,
 'High Quality': 25,
 'Mailable': 53,
 'Connected': 30,
 'Ported': 11,
 'Not Valid': 0,
 'Unknown Contact': 4,
 'Possibly Disconnected': 23,
 'Possibly Portable VOIP': 0,
 'Wireless': 0,
 'First Name Match': 14,
 'Last Name Match': 23,
 'Workplace Match': 4,
 'State Match': 62,
 'No Name': 4}

In [90]:
def is_healthy(name):
    med_words = ['oncology','primary care','radiology','pathology','pathologists','glaucoma','cancer', 'cardiology', 'neurology', 'family care', 'pulmonary', 'anesthesia', 'orthope', 'urgent care', 'allergy', 'kidney', 'surgery', 'hosp', 'mri', 'throat', 'dentist', 'med', 'clinic', 'health', 'gastroenter','anesthesiologist','patient','physician','surgeon','doctor','hospital', 'md', 'medical', 'pediatrics', 'm.d.']
    healthy = False
    for word in med_words:
        if word in str(name).lower():
            healthy = True   
    return(healthy)

def variable_breakdown(dataframe):
    
    LIST_OF_DICTS = []
    
    
    for row in dataframe.itertuples():

        address_match = 0
        city_match = 0
        zipcode_match = 0
        health = 0
        mail = 0
        connect = 0
        port = 0
        novalid = 0
        unknown = 0
        disconnected = 0
        voip = 0
        wireless = 0
        address = 0
        date = 0
        business = 0
        residential = 0
        low = 0
        high = 0
        med = 0
        first_name_match = 0
        last_name_match = 0 
        workplace_match = 0
        state_match = 0

        if str(row.Address) in str(row.OFFICE_ADDRESS_LINE_2) or str(row.OFFICE_ADDRESS_LINE_2) in str(row.Address):
            address_match += 1
        if str(row.OFFICE_ADDRESS_CITY) in str(row.City):
            city_match += 1
        if clean_zipcode(row.OFFICE_ADDRESS_ZIP) == clean_zipcode(row.Zipcode):
            zipcode_match += 1      
        if row.State == row.OFFICE_ADDRESS_STATE:
            state_match += 1

        
        if str(row.PHYSICIAN_LAST_NAME).lower() in str(row.Name).lower():
            last_name_match =1
        if str(row.PHYSICIAN_FIRST_NAME).lower() in str(row.Name).lower():
            first_name_match =1

        if is_healthy(row.Name) == True:  
            health = 1

        if 'IsMailable' in str(row.Notes):
            mail = 1
        if 'IsConnected' in str(row.Notes):
            connect = 1
        if 'IsPorted' in str(row.Notes):
            port = 1
        if 'NotValid' in str(row.Notes):
            novalid = 1
        if 'IsUnknownContact' in str(row.Notes):
            unknown = 1
        if 'IsPossibleDisconnected' in str(row.Notes):
            disconnected = 1
        if 'IsPossiblePortableVOIP' in str(row.Notes):
            voip = 1
        if 'IsWireless' in str(row.Notes):
            wireless = 1

        if row.Address == 'None':
            address = 1
        if row.Date == 'None':
            date = 1
        if row.PhoneType == 'BUSINESS':
            business = 1
        if row.PhoneType == 'RESIDENTIAL':
            residential = 1
        if row.QualityScore == 'LOW':
            low = 1
        if row.QualityScore == 'HIGH':
            high = 1
        if row.QualityScore == 'MED':
            med = 1

        if str(row.OFFICE_ADDRESS_LINE_1).lower() in str(row.Name).lower():
            workplace_match = 1

        new_dict = {
            'OFFICE_TELEPHONE': row.OFFICE_TELEPHONE,
            'Address Match': address_match,
            'City Match': city_match,
            'ZipCode Match': zipcode_match,
            'State Match': state_match,
            'No Address': address,
            'No Date': date,
            'Relevant Name': health,
            'Business Phone': business,
            'Residential Phone': residential,
            'Low Quality': low,
            'Medium Quality': med,
            'High Quality': high,
            'Mailable': mail,
            'Connected': connect,
            'Ported': port,
            'Unknown Contact': unknown,
            'Possibly Disconnected': disconnected,
            'Possibly Portable VOIP': voip,
            'First Name Match':first_name_match,
            'Last Name Match':last_name_match,
            'Workplace Match': workplace_match
            }

        LIST_OF_DICTS.append(new_dict)

    return(LIST_OF_DICTS)

In [50]:
dis_break = variable_breakdown(disconnected_new)
conn_break = variable_breakdown(connected_new)
dis_df = pd.DataFrame(dis_break)
con_df = pd.DataFrame(conn_break)

In [52]:
dis_df.to_csv('new_getphone_disconnect_breakdown.csv', index=False)
con_df.to_csv('new_getphone_connect_breakdown.csv', index=False)

In [41]:
disconnected_new.iloc[:,10:19]

,OFFICE_ADDRESS_LINE_2,OFFICE_ADDRESS_CITY,OFFICE_ADDRESS_STATE,OFFICE_ADDRESS_ZIP,Address,City,Date,Name,Notes
0,725 S ATLANTIC BLVD STE 355,MONTEREY PARK,CA,91754,725 S ATLANTIC BLVD APT B,MONTEREY PARK,None,THOMAS M LIN MD PHYSICIANS SURGEONS,"IsMailable,IsConnected"
1,350 W THOMAS RD,PHOENIX,AZ,85013,None,PHOENIX,None,PHX CHILDRENS H,IsConnected
2,900 MOUNT ROYAL BLVD STE 2,PITTSBURGH,PA,15223,8400 PERRY HWY,PITTSBURGH,None,NARAYANAN KRISHNA MD,"IsMailable,IsPossibleDisconnected,INF"
3,4758 RIDGE RD,CLEVELAND,OH,44144,10184 SANDSTONE TRL,COLUMBIA STATION,None,PHYSICIANS EDGE,"IsMailable,IsPossibleDisconnected,INF"
4,2701 E ELVIRA RD,TUCSON,AZ,85756,2026 E KLEINDALE RD,TUCSON,None,MATTHEW TROUARD,"IsMailable,IsConnected"
5,1900 E TAHQUITZ CANYON WAY STE A2,PALM SPRINGS,CA,92262,1900 E TAHQUITZ CANYON WAY STE A2,PALM SPRINGS,None,FRAGEN RONALD A MD A MEDICAL CORP,"IsMailable,IsConnected"
6,2002 N STOCKTON HILL RD STE 102,KINGMAN,AZ,86401,2002 N STOCKTON HILL RD STE 102,KINGMAN,None,JOE DR GOCHOCO PLLC,"IsMailable,IsConnected"
7,1511 TAMIAMI TRL S,VENICE,FL,34285,1511 TAMIAMI TRL S STE 201,VENICE,None,DONALD A MCEACHERN,"IsMailable,IsPossibleDisconnected,INF"
8,2300 W WHITE AVE STE 104,MCKINNEY,TX,75071,800 W AIRPORT FWY,IRVING,None,ADAPT OF TEXAS,"IsMailable,IsPossibleDisconnected,INF"
9,1 INGALLS DR,HARVEY,IL,60426,1020 OAKWOOD DR,WESTMONT,None,SAEED M AWAN,"IsMailable,IsPossibleDisconnected,INF"
10,5850 HERITAGE LANDING DR,EAST SYRACUSE,NY,13057,5850 HERITAGE LANDING DR,EAST SYRACUSE,None,CNY CHILD NEUROLOGY ASSOCIATES PHYSICIANS SURG...,"IsMailable,IsConnected"
11,404 MAINE ST,LAWRENCE,KS,66044,404 MAINE ST,LAWRENCE,2014-05-16,REED MEDICAL GROUP,"IsMailable,IsPorted,IsPossibleDisconnected,INF"
12,1705 E 19TH ST STE 302,TULSA,OK,74104,900 W FOX ST,TAHLEQUAH,None,LEE STRATTON,IsMailable
13,1225 WILSHIRE BLVD,LOS ANGELES,CA,90017,102 SCOTT ST,UKIAH,None,GILBREATH & PARK,"IsMailable,IsPossibleDisconnected,INF"
14,101 THE CITY DR S BLDG 10,ORANGE,CA,92868,810 E 21ST ST,SANTA ANA,None,SUSAN NAKAMURA,IsMailable
15,999 E BASSE RD STE 103,SAN ANTONIO,TX,78209,None,None,None,ALLERGY ASSOCIATES-SN ANTONIO,None
16,1811 156TH AVE NE STE 5,BELLEVUE,WA,98007,1811 156TH AVE NE STE 5,BELLEVUE,None,GAN FAMILY PRACTICE DR PHYSICIANS SURGEONS,"IsMailable,IsPossibleDisconnected,INF"
17,2121 NE 139TH ST STE 100,VANCOUVER,WA,98686,1498 SE TECH CENTER PL STE 100,VANCOUVER,2011-02-19,AETHENA GYNECOLOGY ASSOCIATES PHYSICIANS SURGEONS,"IsMailable,IsConnected,IsPorted"
18,4714 MARGARETE DR SW,DECATUR,AL,35603,1900 FLINT RD SE,DECATUR,None,ANESTHESIA SERV,"IsMailable,IsPossibleDisconnected,INF"
19,831 W MORGAN ST,RALEIGH,NC,27603,None,None,2008-06-09,None,"IsPorted,IsUnknownContact"
20,9450 S 1300 E FL 2,SANDY,UT,84094,9720 S 1300 E STE E210,SANDY,2001-12-21,ALTA VIEW EYE CARE CENTER,"IsMailable,IsPorted"
21,800 ROSE ST DEPT OB-GYN,LEXINGTON,KY,40536,None,LEXINGTON,None,UNIVERSITY OF KENTUCKY HOSPITAL WILSON EMERY A,IsConnected
22,610 N LINCOLN AVE,URBANA,IL,61801,None,CHAMPAIGN,None,CARLE CLINIC ASSOCIATION,IsConnected
23,41 VIXEN RD,TRUMBULL,CT,6611,1450 BARNUM AVE STE 105,BRIDGEPORT,2016-09-09,ANTON V CHINNIAH N MD PHYSICIANS SURGEONS,"IsMailable,IsConnected,IsPorted"
24,11515 EL CAMINO REAL STE 110,SAN DIEGO,CA,92130,12501 EL CAMINO REAL UNIT D,SAN DIEGO,None,STEVEN Y PARK,IsMailable
25,8333 NAAB RD STE 400,INDIANAPOLIS,IN,46260,4001 W GOELLER BLVD STE A,COLUMBUS,None,VASCULAR PARTNERS PHYSICIANS SURGEONS,"IsMailable,IsConnected"
26,409 E 14TH ST STE D,NEW YORK,NY,10009,409 E 14TH ST STE D,NEW YORK,None,COYNE JOHN A MD OFC PHYSICIANS SURGEONS,"IsMailable,IsConnected"
27,None,None,None,None,2500 ALHAMBRA AVE,MARTINEZ,None,CONTRA COSTA COUNTY OF MEDICAL STAFF OFFICE,"IsMailable,IsConnected"
28,95 MADISON AVE STE 204,MORRISTOWN,NJ,7960,150 N FINLEY AVE,BASKING RIDGE,2016-09-27,JACQUELINE BLANK DO PHYSICIANS SURGEONS,"IsMailable,IsConnected,IsPorted"
29,8360 SIERRA MEADOWS BLVD,NAPLES,FL,34113,None,NAPLES,2007-11-05,ANCHOR HEALTH CENTERS,"IsConnected,IsPorted"
...,...,...,...,...,...,...,...,...,...
43,1060 E FOOTHILL BLVD STE 102,UPLAND,CA,91786,1060 E FOOTHILL BLVD STE 102,UPLAND,None,SHAIKLEY MD INC,"IsMailable,IsPossibleDisconnected,INF"
44,101 W 8TH AVE,SPOKANE,WA,99204,2003 KOOTENAI HEALTH WAY,COEUR D ALENE,None,KOOTENAI MEDICA,IsMailable
45,929 GESSNER RD STE 2000,HOUSTON,TX,77024,1640 NORFOLK ST,HOUSTON,None,MCREYNOLDS EDWA,"IsMailable,IsPossibleDisconnected,INF"
46,BUILDING 10CRC RM 3-388,BETHESDA,MD,20892,None,GLEN ECHO,None,HLTH & HUMAN SV,None
47,824 ANDERSON ST,DURHAM,NC,27705,511 RUIN CREEK RD STE 104,HENDERSON,None,SERAFIN PLASTIC SURGERY,"IsMailable,IsPossibleDisconnected,INF"
48,214 OCEAN ST,LYNN,MA,1902,214 OCEAN ST,LYNN,None,ALLERGY MEDICAL ASSOCIATES OF NORTH SHORE INC,"IsMailable,IsConnected"
49,3501 JOHNSON ST,HOLLYWOOD,FL,33021,3501 JOHNSON ST,HOLLYWOOD,None,MEMORIAL HOSPITAL,"IsMailable,IsConnected"
50,970 S ACADIA RD STE C,THIBODAUX,LA,70301,970 S ACADIA RD,THIBODAUX,None,BRAUD MARIA MD,"IsMailable,IsPossibleDisconnected,INF"
51,10000 MIDLANTIC DR STE 420E,MOUNT LAUREL,NJ,8054,140 N SHERMAN CT,HAZLETON,2001-01-11,ALDO J SURACI,"IsMailable,IsConnected,IsPorted"
52,2901 OHIO BLVD,TERRE HAUTE,IN,47803,518 S 24TH ST,TERRE HAUTE,None,LARRY BRUNO,"IsMailable,IsPossibleDisconnected,INF"
53,800 WESTCHESTER AVE STE N511,RYE BROOK,NY,10573,548 WESTCHESTER AVE,PORT CHESTER,2016-09-13,MARY LEE,"IsMailable,IsConnected,IsPorted"
54,21 BRENDAN WAY,GREENVILLE,SC,29615,None,SENECA,None,MEDICAL MANAGEMENT SERVICES INC,"IsPossibleDisconnected,INF"
55,1206 S MARYLAND PKWY,LAS VEGAS,NV,89104,None,NORTH LAS VEGAS,None,NEVADA STATE BANK,None
56,2002 MEDICAL PKWY STE 120,ANNAPOLIS,MD,21401,None,BARSTOW,None,ROBBIE BRAND,"IsPossibleDisconnected,INF"
57,1650 COCHRANE CIR,FT CARSON,CO,80913,None,None,None,None,IsUnknownContact
58,2525 SOUTHEAST BLVD,SALEM,OH,44460,166 VINE ST,SALEM,None,FAMILY HEALTH CARE OF COLUMBIANA COUNTY INC,"IsMailable,IsPossibleDisconnected,INF"
59,1955 W FRYE RD,CHANDLER,AZ,85224,None,MESA,None,ASSOCIATED CHES,None
60,4400 INTERSTATE HIGHWAY 30 W STE 110,GREENVILLE,TX,75402,None,GREENVILLE,None,HUNT REG MED CT,None
61,9985 SIERRA AVE DEPT IM,FONTANA,CA,92335,8929 OLEANDER AVE,FONTANA,None,MARIA PEREZ,"IsMailable,IsConnected"
62,46B THOMAS JOHNSON DR STE 100,FREDERICK,MD,21702,10801 LOCKWOOD DR STE 140,SILVER SPRING,None,COMMUNITY RADIOLOGY ASSOCIATES INC,"IsMailable,IsPossibleDisconnected,INF"
63,107 BEACON RD,BALTIMORE,MD,21220,107 BEACON RD,MIDDLE RIVER,None,MIDDLE RIVER FAMILY PRACTICE PHYSICIANS SURGEONS,"IsMailable,IsConnected"
64,1901 RESEARCH BLVD STE 350,ROCKVILLE,MD,20850,600 N WOLFE ST,BALTIMORE,None,JOHNS HOPKINS H,IsMailable
65,6411 FANNIN ST,HOUSTON,TX,77030,7400 FANNIN ST STE 850,HOUSTON,2004-11-04,E RUSSELL WEIDMAN DR PHYSICIANS GENERAL,"IsMailable,IsConnected,IsPorted"
66,2426 LEE HWY STE 200,BRISTOL,VA,24202,605 BAXTER ST,JOHNSON CITY,None,PARADISE MASSAGE AND SKIN CARE MASSAGE THERAPISTS,"IsMailable,IsConnected"
67,2868 E LISMORE RD,DULUTH,MN,55804,2868 E LISMORE RD,DULUTH,None,ERIKA MILES,"IsMailable,IsPossibleDisconnected,INF"
68,110 E MEDICAL LN STE 140,WEST COLUMBIA,SC,29169,100 SUNSET BLVD APT 403,WEST COLUMBIA,None,KEITH D LOBEL,"IsMailable,IsConnected"
69,2400 S AVENUE A,YUMA,AZ,85364,None,YUMA,None,E SW,IsConnected
70,234 GOODMAN ST,CINCINNATI,OH,45219,None,None,2016-05-17,None,"IsPorted,IsUnknownContact"
71,1530 LEE BLVD STE 1400,LEHIGH ACRES,FL,33936,None,LEHIGH ACRES,None,FLORIDA STATE OF,None
72,265 POSADA LN STE C,TEMPLETON,CA,93465,292 POSADA LN STE D,TEMPLETON,None,B HENDRIK,IsMailable

In [51]:
dis_df

,Address Match,Business Phone,City Match,Connected,First Name Match,High Quality,Last Name Match,Low Quality,Mailable,Medium Quality,...,OFFICE_TELEPHONE,Ported,Possibly Disconnected,Possibly Portable VOIP,Relevant Name,Residential Phone,State Match,Unknown Contact,Workplace Match,ZipCode Match
0,0,1,1,1,1,1,1,0,1,0,...,6265769929,0,0,0,1,0,1,0,0,1
1,0,1,1,1,0,0,0,0,0,1,...,6025460935,0,0,0,0,0,1,0,0,0
2,0,1,1,0,1,0,1,1,1,0,...,4123643117,0,1,0,1,0,1,0,0,0
3,0,1,0,0,0,0,0,1,1,0,...,4402368484,0,1,0,1,0,1,0,0,0
4,0,0,1,1,0,1,1,0,1,0,...,5203225418,0,0,0,0,1,1,0,0,0
5,1,1,1,1,1,1,1,0,1,0,...,7603271226,0,0,0,1,0,1,0,0,1
6,1,1,1,1,0,1,1,0,1,0,...,9287184375,0,0,0,0,0,1,0,0,1
7,0,0,1,0,1,0,0,1,1,0,...,9414972138,0,1,0,0,1,1,0,0,1
8,0,1,0,0,0,0,0,1,1,0,...,9725547131,0,1,0,0,0,1,0,0,0
9,0,0,0,0,0,0,1,1,1,0,...,6307898030,0,1,0,0,1,1,0,0,0
10,1,1,1,1,0,1,0,0,1,0,...,3154462985,0,0,0,1,0,1,0,0,1
11,1,1,1,0,0,0,0,1,1,0,...,7858423635,1,1,0,1,0,1,0,0,1
12,0,0,0,0,0,0,0,1,1,0,...,9184564503,0,0,0,0,1,1,0,0,0
13,0,1,0,0,0,0,1,1,1,0,...,7074627040,0,1,0,0,0,1,0,0,0
14,0,0,0,0,0,0,1,1,1,0,...,7146342322,0,0,0,0,1,1,0,0,0
15,0,0,0,0,0,0,0,0,0,1,...,2108216688,0,0,0,1,0,0,0,0,0
16,1,1,1,0,0,0,1,1,1,0,...,4257478950,0,1,0,1,0,1,0,0,1
17,0,1,1,1,0,1,0,0,1,0,...,3606937878,1,0,0,1,0,1,0,0,0
18,0,1,1,0,0,0,0,1,1,0,...,2563530626,0,1,0,1,0,1,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,7572955979,1,0,0,0,0,0,1,0,0
20,0,1,1,0,0,0,0,1,1,0,...,8015720631,1,0,0,0,0,1,0,0,1
21,0,1,1,1,1,1,0,0,0,0,...,8593235410,0,0,0,1,0,1,0,0,0
22,0,1,0,1,0,0,0,0,0,1,...,2173835159,0,0,0,1,0,1,0,1,0
23,0,1,0,1,1,1,1,0,1,0,...,2033341932,1,0,0,1,0,1,0,0,0
24,0,0,1,0,0,0,1,1,1,0,...,8584812651,0,0,0,0,1,1,0,0,1
25,0,1,0,1,0,1,0,0,1,0,...,8123422100,0,0,0,1,0,1,0,0,0
26,1,1,1,1,1,1,1,0,1,0,...,2124752880,0,0,0,1,0,1,0,0,1
27,0,1,0,1,0,1,0,0,1,0,...,9253705110,0,0,0,1,0,0,0,0,0
28,0,1,0,1,1,1,1,0,1,0,...,9083404609,1,0,0,1,0,1,0,0,0
29,0,1,1,1,0,0,0,0,0,1,...,2394036375,1,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,1,1,1,0,0,0,1,1,1,0,...,9099828941,0,1,0,1,0,1,0,0,1
44,0,1,0,0,0,0,0,1,1,0,...,2086663378,0,0,0,1,0,0,0,0,0
45,0,1,1,0,0,0,0,1,1,0,...,7135283430,0,1,0,0,0,1,0,0,0
46,0,1,0,0,0,0,0,1,0,0,...,3014516955,0,0,0,0,0,1,0,0,0
47,0,1,0,0,0,0,1,1,1,0,...,9192207711,0,1,0,1,0,1,0,0,0
48,1,1,1,1,0,1,0,0,1,0,...,7815956800,0,0,0,1,0,1,0,0,0
49,1,1,1,1,0,1,0,0,1,0,...,9549622445,0,0,0,1,0,1,0,0,1
50,0,1,1,0,1,0,1,1,1,0,...,9854471216,0,1,0,1,0,1,0,0,1
51,0,0,0,1,0,1,0,0,1,0,...,5704506333,1,0,0,0,1,0,0,0,0
52,0,0,1,0,1,0,0,1,1,0,...,8122355180,0,1,0,0,1,1,0,0,1
53,0,0,0,1,0,1,1,0,1,0,...,9149330016,1,0,0,0,1,1,0,0,1
54,0,1,0,0,0,0,0,1,0,0,...,8648820226,0,1,0,1,0,1,0,0,0
55,0,1,0,0,0,0,0,1,0,0,...,7026366360,0,0,0,0,0,1,0,0,0
56,0,0,0,0,0,0,0,1,0,0,...,7602561414,0,1,0,0,1,0,0,0,0
57,0,0,0,0,0,0,0,0,0,0,...,7195244051,0,0,0,0,0,0,1,1,0
58,0,1,1,0,0,0,0,1,1,0,...,3303373500,0,1,0,1,0,1,0,0,1
59,0,1,0,0,0,0,0,1,0,0,...,4809817033,0,0,0,0,0,1,0,0,0
60,0,1,1,0,0,0,0,1,0,0,...,9034087780,0,0,0,1,0,1,0,0,0
61,0,0,1,1,0,1,0,0,1,0,...,9098238609,0,0,0,0,1,1,0,0,1
62,0,1,0,0,0,0,0,1,1,0,...,3015930724,0,1,0,0,0,1,0,0,0
63,1,1,0,1,0,1,0,0,1,0,...,4106869019,0,0,0,1,0,1,0,0,1
64,0,1,0,0,0,0,0,1,1,0,...,4109555607,0,0,0,0,0,1,0,0,0
65,0,1,1,1,0,1,0,0,1,0,...,7137911874,1,0,0,1,0,1,0,0,0
66,0,1,0,1,0,1,0,0,1,0,...,4239263472,0,0,0,0,0,0,0,0,0
67,1,0,1,0,1,0,1,1,1,0,...,2185255185,0,1,0,0,1,1,0,0,1
68,0,0,1,1,0,1,1,0,1,0,...,8037945084,0,0,0,0,1,1,0,0,1
69,0,0,1,1,0,0,0,0,0,1,...,9283445550,0,0,0,0,1,1,0,0,0
70,0,0,0,0,0,0,0,0,0,0,...,5135844936,1,0,0,0,0,0,1,0,0
71,0,1,1,0,0,0,0,1,0,0,...,2393688039,0,0,0,0,0,1,0,0,1
72,0,0,1,0,0,0,0,1,1,0,...,8054343211,0,0,0,0,1,1,0,0,1