In [2]:
import pandas as pd

In [3]:

npi = pd.read_csv('../../Data/DataGov.csv')

C:\Users\vigrose\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\vigrose\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
new_file[new_file.NPI.isin(npi.NPI)==False].drop_duplicates('NPI')

,prvdr_id,frst_nm,mid_nm,lst_nm,adrs_id,adr_ln_1,adr_ln_2,cty,st,zip,org_pac_id,phn_numbr,NPI
17,42100430,CARMEN,M,JIMENEZ,CO805251542FO1800XSTXX300,1800 STOVER ST,NaN,FORT COLLINS,CO,805251542,NaN,9.703801e+09,1578840864
19,42100463,DANACIA,M,JONES,OR970801494GR2850XRDXX500,2850 SE POWELL VALLEY RD,NaN,GRESHAM,OR,970801494,2.441440e+08,5.036665e+09,1851315329
39,42100760,JOHN,NaN,CHIARO,OH448705390SA2500XRDXX400,2500 W STRUB RD,NaN,SANDUSKY,OH,448705390,2.769386e+09,4.196266e+09,1508863630
40,42100786,JENNIFER,A,CENTORE LOBER,IL602023454EV800XXSTXX303,800 AUSTIN ST,Suite 363,EVANSTON,IL,602023454,2.860397e+09,7.734278e+09,1932198322
65,42101180,WARREN,J,SANDLER,FL334333430BO7000XRDXX501,7000 W PALMETTO PARK RD,SUITE 210,BOCA RATON,FL,334333430,NaN,5.617030e+09,1316934474
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3091803,9931539897,JENNA,M,WILLIAMS,GA317926676TH100XXDRXX301,100 MIMOSA DR,2ND,THOMASVILLE,GA,317926676,6.103131e+09,2.295510e+09,1093349805
3091804,9931539921,LAUREN,ANNETTE,JOHNSON,MN553372537BU14101DRXX300,14101 FAIRVIEW DR,NaN,BURNSVILLE,MN,553372537,1.951213e+09,6.122735e+09,1184252900
3091808,9931539939,CASSANDRA,MARIE,RIVERS,MA010894620WE928XXSTXX300,928 RIVERDALE ST,NaN,WEST SPRINGFIELD,MA,10894620,2.264595e+09,8.663893e+09,1679108252
3091809,9931539954,VINNETTE,A,FISHER,NY105301811HA359XXAVEX400,359 N CENTRAL AVE,NaN,HARTSDALE,NY,105301811,5.193030e+09,9.144482e+09,1023642980
3091811,9931539970,ERIC,NaN,PETERS,NY147601100OL1XXXXDRXX401,1 LEO MOSS DR,SUITE 4308,OLEAN,NY,147601100,3.375455e+09,7.163738e+09,1225419237

In [4]:
new_file.columns = [c.replace(' ','') for c in new_file.columns.values]

In [5]:
len(new_file)

3091812

In [12]:
new_file.drop_duplicates('NPI')

,prvdr_id,frst_nm,mid_nm,lst_nm,adrs_id,adr_ln_1,adr_ln_2,cty,st,zip,org_pac_id,phn_numbr,NPI
0,42100026,PETER,K,FUNG,CA906404314MO101XXBLVD403,101 E BEVERLY BLVD,SUITE 103,MONTEBELLO,CA,906404314,7.517858e+09,3.237281e+09,1871519561
2,42100042,BIJAN,NaN,HAGHIGHI,CA926634162NE1XXXXDRXX300,1 HOAG DR,NaN,NEWPORT BEACH,CA,926634162,1.456312e+09,9.498911e+09,1790868909
3,42100117,DAVID,NaN,GRIFFIN,SC296075253GR104XXDRXX303,104 INNOVATION DR,SUITE 2000,GREENVILLE,SC,296075253,6.608827e+09,8.646036e+09,1508823618
5,42100133,JEFFREY,M,SPEAR,AR728012724RU1808XSTXX400,1808 W MAIN ST,NaN,RUSSELLVILLE,AR,728012724,2.466365e+09,5.019683e+09,1477528776
6,42100190,JOHN,D,VERBRUGGE,MI495032560GR100XXNEXX300,100 MICHIGAN NE,NaN,GRAND RAPIDS,MI,495032560,1.951404e+09,6.163912e+09,1154338044
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3091803,9931539897,JENNA,M,WILLIAMS,GA317926676TH100XXDRXX301,100 MIMOSA DR,2ND,THOMASVILLE,GA,317926676,6.103131e+09,2.295510e+09,1093349805
3091804,9931539921,LAUREN,ANNETTE,JOHNSON,MN553372537BU14101DRXX300,14101 FAIRVIEW DR,NaN,BURNSVILLE,MN,553372537,1.951213e+09,6.122735e+09,1184252900
3091808,9931539939,CASSANDRA,MARIE,RIVERS,MA010894620WE928XXSTXX300,928 RIVERDALE ST,NaN,WEST SPRINGFIELD,MA,10894620,2.264595e+09,8.663893e+09,1679108252
3091809,9931539954,VINNETTE,A,FISHER,NY105301811HA359XXAVEX400,359 N CENTRAL AVE,NaN,HARTSDALE,NY,105301811,5.193030e+09,9.144482e+09,1023642980
3091811,9931539970,ERIC,NaN,PETERS,NY147601100OL1XXXXDRXX401,1 LEO MOSS DR,SUITE 4308,OLEAN,NY,147601100,3.375455e+09,7.163738e+09,1225419237

In [6]:
new_file.columns

Index(['prvdr_id', 'frst_nm', 'mid_nm', 'lst_nm', 'adrs_id', 'adr_ln_1',
       'adr_ln_2', 'cty', 'st', 'zip', 'org_pac_id', 'phn_numbr', 'NPI'],
      dtype='object')