In [1]:
from datamart import get_datamart_results
import pyodbc
import pandas as pd

In [10]:
username = 'vigrose'
password = 'Hufflepuff10946'

In [11]:
q = "DSN=eprdods; UID={}; PWD={}".format(username, password)
ODS = pyodbc.connect(q)

In [13]:
iqvia_query = \
        """ 
        SELECT DISTINCT 
        B.BUSINESS_NAME,
        B.DBA_NAME,
        P.ME
        FROM 
        ODS.ODS_IMS_BUSINESS B, ODS.SAS_ODS_IMS_PROVIDER_AFFIL A, ODS.ODS_IMS_PROFESSIONAL P
        WHERE  
        B.IMS_ORG_ID = A.IMS_ORG_ID
        AND
        A.PROFESSIONAL_ID = P.PROFESSIONAL_ID
        AND
        P.CURRENT_BATCH_FLAG='Y'
        AND
        A.CURRENT_BATCH_FLAG='Y'
        AND
        B.CURRENT_BATCH_FLAG='Y'
        ;
        """

In [15]:
iqvia = pd.read_sql(con=ODS, sql=iqvia_query)

In [9]:
cred = get_datamart_results((1,2,3,4,5,6,7,8,9,10,11,12), (2019,2020))

1123417
145052
846436
144478

In [84]:
iqvia.groupby('BUSINESS_NAME').count()['ME'].sort_values(ascending=False)[300:350]

BUSINESS_NAME
ROPER SAINT FRANCIS HEALTHCARE                                            1101
THE RICHARD M ROSS HEART HOSPITAL                                         1099
OVERLOOK MEDICAL CENTER                                                   1094
NORTH SHORE MEDICAL CENTER, INC                                           1091
HILL PHYSICIANS MEDICAL GROUP                                             1090
MEDICAL CITY CHILDRENS HOSPITAL                                           1090
SUNRISE HOSPITAL AND MEDICAL CENTER, LLC                                  1089
SISTERS OF CHARITY HOSPITAL                                               1087
JERSEY SHORE UNIVERSITY MEDICAL CENTER                                    1085
LEGACY EMANUEL MEDICAL CENTER                                             1083
SAINT MARY MEDICAL CENTER                                                 1081
NOVANT HEALTH PRESBYTERIAN MEDICAL CENTER                                 1080
SANFORD BROADWAY MEDICAL CENTER                                           1078
MULTICARE TACOMA GENERAL HOSPITAL                                         1078
SHARP METROPOLITAN MEDICAL CAMPUS                                         1077
UNIVERSITY OF MARYLAND SAINT JOSEPH MEDICAL CENTER                        1076
KETTERING MEDICAL CENTER                                                  1076
KAISER PERMANENTE SACRAMENTO MEDICAL CENTER                               1071
ADVENTHEALTH PEPIN HEART INSTITUTE                                        1070
MICHAEL E DEBAKEY VA MEDICAL CENTER                                       1065
BETHESDA NORTH HOSPITAL                                                   1065
UNIVERSITY OF IOWA ROY J AND LUCILLE A CARVER COLLEGE OF MEDICINE         1064
ENGLEWOOD HOSPITAL ASSOCIATION                                            1062
SAINT ROSE DOMINICAN HOSPITALS ROSE DE LIMA CAMPUS                        1060
JW RUBY MEMORIAL HOSPITAL                                                 1059
MORTON PLANT HOSPITAL                                                     1057
SAINT JOSEPHS HOSPITAL CANCER INSTITUTE                                   1057
LAHEY CLINIC HOSPITAL, INC                                                1056
CARILION ROANOKE MEMORIAL HOSPITAL                                        1056
KAISER PERMANENTE SANTA CLARA MEDICAL CENTER                              1056
THE BRENNER CHILDRENS HOSPITAL                                            1053
MATTEL CHILDRENS HOSPITAL UNIVERSITY OF CALIFORNIA LOS ANGELES            1052
RADY CHILDRENS HOSPITAL AND HEALTH CENTER                                 1052
OUR LADY OF THE LAKE HOSPITAL, INC                                        1052
NORTH CAROLINA CANCER HOSPITAL                                            1049
KAISER PERMANENTE RICHMOND MEDICAL CENTER                                 1047
GOOD SAMARITAN HOSPITAL MEDICAL CENTER                                    1047
EDWARD HOSPITAL                                                           1047
MAYO EUGENIO LITTA CHILDRENS HOSPITAL                                     1047
ADVOCATE LUTHERAN GENERAL HOSPITAL                                        1043
METROHEALTH SYSTEM                                                        1039
BUFFALO GENERAL MEDICAL CENTER                                            1038
FRESNO COMMUNITY HOSPITAL AND MEDICAL CENTER                              1032
THE CHILDRENS MERCY HOSPITAL                                              1031
CHRISTIANACARE WILMINGTON HOSPITAL                                        1031
GRANT MEDICAL CENTER                                                      1030
SAINT LUKES HOSPITAL                                                      1028
CAL CARE IPA                                                              1027
CROZER CHESTER MEDICAL CENTER                                             1025
RONALD MCDONALD CHILDRENS HOSPITAL OF LOYOLA UNIVERSITY MEDICAL CENTER    1022
Name: ME, dtype: int64

In [49]:
CRED = cred.groupby('CUSTOMER_NAME').count()[['ME']].sort_values(ascending=False, by='ME')

In [38]:
cred[cred.CUSTOMER_NAME=='CareMore Medical Group']

Empty DataFrame
Columns: [FULL_DT, ME, PARTY_ID, ORDER_NBR, ORDER_PRODUCT_ID, ORDER_PHYSICIAN_HIST_KEY, CUSTOMER_KEY, CUSTOMER_NBR, CUSTOMER_ISELL_LOGIN, CUSTOMER_NAME, CUSTOMER_TYPE_DESC, CUSTOMER_TYPE, CUSTOMER_CATEGORY_DESC]
Index: []

In [44]:
CRED_CUST = cred.sort_values('CUSTOMER_NAME')['CUSTOMER_NAME'].unique()

In [48]:
CRED_CUST[1000:1050]

array(['Cape Fear Valley Medical Center', 'Cape Regional Medical Center',
       'Cape Surgery Center Llc', 'Capital Asc', 'Capital Bluecross',
       'Capital City Surgery Center',
       "Capital District Physicians' Health Plan",
       'Capital Health System', 'Capital Nephrology Access Center',
       'Capital Orthopaedic Surgery Center',
       'Capital Region  Ambulatory Surgery Ctr.',
       'Capital Region Medical Center',
       'Capital Surgery And Laser Center',
       'Capitol Vein And Laser Center', 'Captain James A. Lovell',
       'Captial District Psychiatric Center',
       'Carbon-Schuylkill Endoscopy Center',
       'Cardiac Cath Lab Of Bryan/College Station',
       'Cardiac Cath Lab Of Ft. Worth',
       'Cardiac Cath Lab Of Idaho Falls, Llc',
       'Cardiac Cath Lab Of Kingwood, Lp', 'Cardiff Bay Center, Llc',
       'Cardiology Center Of Amarillo, Llp',
       'Cardiovascular Care Providers, Inc.',
       'Cardiovascular Inst Of The South (Apmc)',
       'Cardiovascular Institute Of Central Florida',
       'Cardiovascular Surgical Suites, Llc', 'Care 1st Health Plan',
       'Care Alliance Health Services', 'Care Dimensions',
       'Care For The Bay Area', 'Care For The Homeless', 'Care Ohio Inc',
       'Care Stl Health', 'Care To Care', 'Careconnect Health, Inc.',
       'Careerbuilder Employment Screening',
       'Carefirst Bluecross Blueshield Community Health Plan District Of Columbia',
       'Carehere, Llc', 'Carelink Of Jackson', 'Carenet Of Lancaster',
       'Careplex Orthopaedic Ambulatory Surgery Center',
       'Carepoint Health', 'Carereview',
       'Cares, Center For Ambulatory Resources', 'Caresource',
       'Careteam Plus', 'Carient Heart And Vascular Pc',
       'Carilion Centralized Verification Services',
       'Carillon Nursing & Rehabilitation Center'], dtype=object)

In [73]:
pp = pd.read_csv("../../Data/MasterfileCore/Program Personnel table - Active.csv", sep='|', error_bad_lines=False, encoding='latin', low_memory=False)

b'Skipping line 8397: expected 35 fields, saw 36\nSkipping line 31221: expected 35 fields, saw 52\nSkipping line 51840: expected 35 fields, saw 57\nSkipping line 51876: expected 35 fields, saw 44\n'

In [69]:
file = "../../Data/MasterfileCore/Program Personnel table - Active.txt"

In [76]:
cols = pd.read_csv(file, nrows=31221).columns 
df = pd.read_csv(file, usecols=cols, encoding='latin')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4624, saw 2

In [82]:
pp[31215:31250]

,pgm_id,pers_type,aamc_id,pers_name_sfx,pers_name_last,pers_name_first,pers_name_mid,pers_deg1,pers_deg2,pers_deg3,...,prev_director_first,prev_director_md,prev_director_sfx,acgme_verified,approval_date,why_change,subscribe,diff_name,email_notify,me.
31215,2204321269,R,NaN,NaN,Henault,Andrea,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31216,2204511271,B,NaN,NaN,Wehunt,Michelle,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31217,2204511271,D,12190200,NaN,Lenhard,Matthew,J,MD,NaN,NaN,...,Kerry,M,NaN,N,NaN,2.0,NaN,0.0,Y,NaN
31218,2204511271,R,NaN,NaN,Wehunt,Michelle,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31219,2204511272,B,NaN,NaN,Nickols,Hope,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31220,2204511272,D,14470842,NaN,Isham,Katheryn,D,MD,NaN,NaN,...,Sharon,D,NaN,N,NaN,1.0,NaN,0.0,Y,NaN
31221,2204511272,K,NaN,NaN,Nickols,Hope,NaN,BS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
31222,2204511272,P,NaN,NaN,Nickols,Hope,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31223,2204511272,R,NaN,NaN,Nickols,Hope,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31224,2204521270,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31225,2204521270,D,10168973,NaN,Goodier,Christopher,G,MD,NaN,NaN,...,Ashlyn,H,NaN,N,NaN,1.0,NaN,0.0,Y,NaN
31226,2204521270,K,NaN,NaN,Westbury,Stacey,L,BA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
31227,2204521270,P,NaN,NaN,Livingston,Stacey,L,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31228,2204521270,R,NaN,NaN,Livingston,Stacey,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31229,2204700362,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31230,2204700362,D,10917699,NaN,Brown,Douglas,H,MD,NaN,NaN,...,Douglas,H,NaN,N,NaN,2.0,NaN,0.0,Y,NaN
31231,2204700362,K,NaN,NaN,Underwood,Pamela,J,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
31232,2204700362,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31233,2204700362,P,NaN,NaN,Brown,Douglas,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31234,2204700362,R,NaN,NaN,Underwood,Pamela,J,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31235,2204700363,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31236,2204700363,D,15394303,NaN,Ling,Frank,W,MD,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,Y,NaN
31237,2204700363,K,NaN,NaN,Katzarkov,Roumiana,NaN,MA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
31238,2204700363,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31239,2204700363,P,NaN,NaN,Katzarkov,Roumiana,NaN,NaN,MA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31240,2204700363,R,NaN,NaN,Katzarkov,Roumiana,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31241,2204711275,B,NaN,NaN,Smith,Ashley,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31242,2204711275,D,10798491,NaN,Kimball,Kristopher,NaN,MD,NaN,NaN,...,Nikki,B,NaN,N,NaN,2.0,NaN,0.0,Y,NaN
31243,2204711275,K,NaN,NaN,Reed,Lindsey,B,MBA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
31244,2204711275,P,NaN,NaN,Reed,Lindsey,B.,MBA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31245,2204711275,R,NaN,NaN,Reed,Lindsey,Beth,NaN,MBA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31246,2204721274,B,NaN,NaN,Scott,Pamela,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
31247,2204721274,D,15257521,NaN,Dizon,Arthur,M,MD,NaN,NaN,...,C,David,NaN,N,NaN,2.0,NaN,0.0,Y,NaN
31248,2204721274,K,NaN,NaN,Barnett,Paula,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
31249,2204721274,P,NaN,NaN,Barnett,Paula`,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN

In [75]:
pp[51835:]

,pgm_id,pers_type,aamc_id,pers_name_sfx,pers_name_last,pers_name_first,pers_name_mid,pers_deg1,pers_deg2,pers_deg3,...,prev_director_first,prev_director_md,prev_director_sfx,acgme_verified,approval_date,why_change,subscribe,diff_name,email_notify,me.
51835,4090540062,R,NaN,NaN,Pourat,Penny,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
51836,ai,Kristin,S,NaN,N,NaN,2,NaN,0,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51837,4090540063,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
51838,4090540063,P,NaN,NaN,Beizai,Kristin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
51839,4090540063,R,NaN,NaN,Beizai,Kristin,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65610,9995600184,B,NaN,NaN,Gladney,Tina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
65611,9995600184,D,15091268,NaN,Darisetty,Sriram,NaN,MD,NaN,NaN,...,Kesavan,NaN,NaN,N,NaN,2.0,NaN,0.0,Y,NaN
65612,9995600184,K,NaN,NaN,Gladney,Tina,NaN,BBA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,Y,NaN
65613,9995600184,P,NaN,NaN,Gladney,Tina,NaN,BBA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
65614,9995600184,R,NaN,NaN,Gladney,Tina,NaN,BBA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN