In [1]:
import pandas as pd
import useful_functions as use
from fuzzywuzzy import fuzz

C:\Users\vigrose\AppData\Local\Continuum\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [6]:
npi_folder = '../../Data/NPI/'
npi_file = use.get_newest(npi_folder, 'npidata')

In [3]:
def is_a_match(thing_1, thing_2, threshold):
    if thing_1 == thing_2:
        match = True
    elif thing_1 in thing_2:
        match = True
    elif thing_2 in thing_1:
        match = True
    elif fuzz.ratio(thing_1, thing_2)>threshold:
        match = True
    else:
        match = False
    return(match)

In [4]:
bad_cols = ['Entity Type Code',
 'Replacement NPI',
 'Employer Identification Number (EIN)',
  'NPI Deactivation Reason Code',
 'NPI Deactivation Date',
 'NPI Reactivation Date',
 'Healthcare Provider Taxonomy Code_1',
 'Provider License Number_1',
 'Provider License Number State Code_1',
 'Healthcare Provider Primary Taxonomy Switch_1',
 'Healthcare Provider Taxonomy Code_2',
 'Provider License Number_2',
 'Provider License Number State Code_2',
 'Healthcare Provider Primary Taxonomy Switch_2',
 'Healthcare Provider Taxonomy Code_3',
 'Provider License Number_3',
 'Provider License Number State Code_3',
 'Healthcare Provider Primary Taxonomy Switch_3',
 'Healthcare Provider Taxonomy Code_4',
 'Provider License Number_4',
 'Provider License Number State Code_4',
 'Healthcare Provider Primary Taxonomy Switch_4',
 'Healthcare Provider Taxonomy Code_5',
 'Provider License Number_5',
 'Provider License Number State Code_5',
 'Healthcare Provider Primary Taxonomy Switch_5',
 'Healthcare Provider Taxonomy Code_6',
 'Provider License Number_6',
 'Provider License Number State Code_6',
 'Healthcare Provider Primary Taxonomy Switch_6',
 'Healthcare Provider Taxonomy Code_7',
 'Provider License Number_7',
 'Provider License Number State Code_7',
 'Healthcare Provider Primary Taxonomy Switch_7',
 'Healthcare Provider Taxonomy Code_8',
 'Provider License Number_8',
 'Provider License Number State Code_8',
 'Healthcare Provider Primary Taxonomy Switch_8',
 'Healthcare Provider Taxonomy Code_9',
 'Provider License Number_9',
 'Provider License Number State Code_9',
 'Healthcare Provider Primary Taxonomy Switch_9',
 'Healthcare Provider Taxonomy Code_10',
 'Provider License Number_10',
 'Provider License Number State Code_10',
 'Healthcare Provider Primary Taxonomy Switch_10',
 'Healthcare Provider Taxonomy Code_11',
 'Provider License Number_11',
 'Provider License Number State Code_11',
 'Healthcare Provider Primary Taxonomy Switch_11',
 'Healthcare Provider Taxonomy Code_12',
 'Provider License Number_12',
 'Provider License Number State Code_12',
 'Healthcare Provider Primary Taxonomy Switch_12',
 'Healthcare Provider Taxonomy Code_13',
 'Provider License Number_13',
 'Provider License Number State Code_13',
 'Healthcare Provider Primary Taxonomy Switch_13',
 'Healthcare Provider Taxonomy Code_14',
 'Provider License Number_14',
 'Provider License Number State Code_14',
 'Healthcare Provider Primary Taxonomy Switch_14',
 'Healthcare Provider Taxonomy Code_15',
 'Provider License Number_15',
 'Provider License Number State Code_15',
 'Healthcare Provider Primary Taxonomy Switch_15',
 'Other Provider Identifier_1',
 'Other Provider Identifier Type Code_1',
 'Other Provider Identifier State_1',
 'Other Provider Identifier Issuer_1',
 'Other Provider Identifier_2',
 'Other Provider Identifier Type Code_2',
 'Other Provider Identifier State_2',
 'Other Provider Identifier Issuer_2',
 'Other Provider Identifier_3',
 'Other Provider Identifier Type Code_3',
 'Other Provider Identifier State_3',
 'Other Provider Identifier Issuer_3',
 'Other Provider Identifier_4',
 'Other Provider Identifier Type Code_4',
 'Other Provider Identifier State_4',
 'Other Provider Identifier Issuer_4',
 'Other Provider Identifier_5',
 'Other Provider Identifier Type Code_5',
 'Other Provider Identifier State_5',
 'Other Provider Identifier Issuer_5',
 'Other Provider Identifier_6',
 'Other Provider Identifier Type Code_6',
 'Other Provider Identifier State_6',
 'Other Provider Identifier Issuer_6',
 'Other Provider Identifier_7',
 'Other Provider Identifier Type Code_7',
 'Other Provider Identifier State_7',
 'Other Provider Identifier Issuer_7',
 'Other Provider Identifier_8',
 'Other Provider Identifier Type Code_8',
 'Other Provider Identifier State_8',
 'Other Provider Identifier Issuer_8',
 'Other Provider Identifier_9',
 'Other Provider Identifier Type Code_9',
 'Other Provider Identifier State_9',
 'Other Provider Identifier Issuer_9',
 'Other Provider Identifier_10',
 'Other Provider Identifier Type Code_10',
 'Other Provider Identifier State_10',
 'Other Provider Identifier Issuer_10',
 'Other Provider Identifier_11',
 'Other Provider Identifier Type Code_11',
 'Other Provider Identifier State_11',
 'Other Provider Identifier Issuer_11',
 'Other Provider Identifier_12',
 'Other Provider Identifier Type Code_12',
 'Other Provider Identifier State_12',
 'Other Provider Identifier Issuer_12',
 'Other Provider Identifier_13',
 'Other Provider Identifier Type Code_13',
 'Other Provider Identifier State_13',
 'Other Provider Identifier Issuer_13',
 'Other Provider Identifier_14',
 'Other Provider Identifier Type Code_14',
 'Other Provider Identifier State_14',
 'Other Provider Identifier Issuer_14',
 'Other Provider Identifier_15',
 'Other Provider Identifier Type Code_15',
 'Other Provider Identifier State_15',
 'Other Provider Identifier Issuer_15',
 'Other Provider Identifier_16',
 'Other Provider Identifier Type Code_16',
 'Other Provider Identifier State_16',
 'Other Provider Identifier Issuer_16',
 'Other Provider Identifier_17',
 'Other Provider Identifier Type Code_17',
 'Other Provider Identifier State_17',
 'Other Provider Identifier Issuer_17',
 'Other Provider Identifier_18',
 'Other Provider Identifier Type Code_18',
 'Other Provider Identifier State_18',
 'Other Provider Identifier Issuer_18',
 'Other Provider Identifier_19',
 'Other Provider Identifier Type Code_19',
 'Other Provider Identifier State_19',
 'Other Provider Identifier Issuer_19',
 'Other Provider Identifier_20',
 'Other Provider Identifier Type Code_20',
 'Other Provider Identifier State_20',
 'Other Provider Identifier Issuer_20',
 'Other Provider Identifier_21',
 'Other Provider Identifier Type Code_21',
 'Other Provider Identifier State_21',
 'Other Provider Identifier Issuer_21',
 'Other Provider Identifier_22',
 'Other Provider Identifier Type Code_22',
 'Other Provider Identifier State_22',
 'Other Provider Identifier Issuer_22',
 'Other Provider Identifier_23',
 'Other Provider Identifier Type Code_23',
 'Other Provider Identifier State_23',
 'Other Provider Identifier Issuer_23',
 'Other Provider Identifier_24',
 'Other Provider Identifier Type Code_24',
 'Other Provider Identifier State_24',
 'Other Provider Identifier Issuer_24',
 'Other Provider Identifier_25',
 'Other Provider Identifier Type Code_25',
 'Other Provider Identifier State_25',
 'Other Provider Identifier Issuer_25',
 'Other Provider Identifier_26',
 'Other Provider Identifier Type Code_26',
 'Other Provider Identifier State_26',
 'Other Provider Identifier Issuer_26',
 'Other Provider Identifier_27',
 'Other Provider Identifier Type Code_27',
 'Other Provider Identifier State_27',
 'Other Provider Identifier Issuer_27',
 'Other Provider Identifier_28',
 'Other Provider Identifier Type Code_28',
 'Other Provider Identifier State_28',
 'Other Provider Identifier Issuer_28',
 'Other Provider Identifier_29',
 'Other Provider Identifier Type Code_29',
 'Other Provider Identifier State_29',
 'Other Provider Identifier Issuer_29',
 'Other Provider Identifier_30',
 'Other Provider Identifier Type Code_30',
 'Other Provider Identifier State_30',
 'Other Provider Identifier Issuer_30',
 'Other Provider Identifier_31',
 'Other Provider Identifier Type Code_31',
 'Other Provider Identifier State_31',
 'Other Provider Identifier Issuer_31',
 'Other Provider Identifier_32',
 'Other Provider Identifier Type Code_32',
 'Other Provider Identifier State_32',
 'Other Provider Identifier Issuer_32',
 'Other Provider Identifier_33',
 'Other Provider Identifier Type Code_33',
 'Other Provider Identifier State_33',
 'Other Provider Identifier Issuer_33',
 'Other Provider Identifier_34',
 'Other Provider Identifier Type Code_34',
 'Other Provider Identifier State_34',
 'Other Provider Identifier Issuer_34',
 'Other Provider Identifier_35',
 'Other Provider Identifier Type Code_35',
 'Other Provider Identifier State_35',
 'Other Provider Identifier Issuer_35',
 'Other Provider Identifier_36',
 'Other Provider Identifier Type Code_36',
 'Other Provider Identifier State_36',
 'Other Provider Identifier Issuer_36',
 'Other Provider Identifier_37',
 'Other Provider Identifier Type Code_37',
 'Other Provider Identifier State_37',
 'Other Provider Identifier Issuer_37',
 'Other Provider Identifier_38',
 'Other Provider Identifier Type Code_38',
 'Other Provider Identifier State_38',
 'Other Provider Identifier Issuer_38',
 'Other Provider Identifier_39',
 'Other Provider Identifier Type Code_39',
 'Other Provider Identifier State_39',
 'Other Provider Identifier Issuer_39',
 'Other Provider Identifier_40',
 'Other Provider Identifier Type Code_40',
 'Other Provider Identifier State_40',
 'Other Provider Identifier Issuer_40',
 'Other Provider Identifier_41',
 'Other Provider Identifier Type Code_41',
 'Other Provider Identifier State_41',
 'Other Provider Identifier Issuer_41',
 'Other Provider Identifier_42',
 'Other Provider Identifier Type Code_42',
 'Other Provider Identifier State_42',
 'Other Provider Identifier Issuer_42',
 'Other Provider Identifier_43',
 'Other Provider Identifier Type Code_43',
 'Other Provider Identifier State_43',
 'Other Provider Identifier Issuer_43',
 'Other Provider Identifier_44',
 'Other Provider Identifier Type Code_44',
 'Other Provider Identifier State_44',
 'Other Provider Identifier Issuer_44',
 'Other Provider Identifier_45',
 'Other Provider Identifier Type Code_45',
 'Other Provider Identifier State_45',
 'Other Provider Identifier Issuer_45',
 'Other Provider Identifier_46',
 'Other Provider Identifier Type Code_46',
 'Other Provider Identifier State_46',
 'Other Provider Identifier Issuer_46',
 'Other Provider Identifier_47',
 'Other Provider Identifier Type Code_47',
 'Other Provider Identifier State_47',
 'Other Provider Identifier Issuer_47',
 'Other Provider Identifier_48',
 'Other Provider Identifier Type Code_48',
 'Other Provider Identifier State_48',
 'Other Provider Identifier Issuer_48',
 'Other Provider Identifier_49',
 'Other Provider Identifier Type Code_49',
 'Other Provider Identifier State_49',
 'Other Provider Identifier Issuer_49',
 'Other Provider Identifier_50',
 'Other Provider Identifier Type Code_50',
 'Other Provider Identifier State_50',
 'Other Provider Identifier Issuer_50',
 'Is Sole Proprietor',
 'Is Organization Subpart',
 'Parent Organization LBN',
 'Parent Organization TIN',
 'Authorized Official Name Prefix Text',
 'Authorized Official Name Suffix Text',
 'Authorized Official Credential Text',
 'Healthcare Provider Taxonomy Group_1',
 'Healthcare Provider Taxonomy Group_2',
 'Healthcare Provider Taxonomy Group_3',
 'Healthcare Provider Taxonomy Group_4',
 'Healthcare Provider Taxonomy Group_5',
 'Healthcare Provider Taxonomy Group_6',
 'Healthcare Provider Taxonomy Group_7',
 'Healthcare Provider Taxonomy Group_8',
 'Healthcare Provider Taxonomy Group_9',
 'Healthcare Provider Taxonomy Group_10',
 'Healthcare Provider Taxonomy Group_11',
 'Healthcare Provider Taxonomy Group_12',
 'Healthcare Provider Taxonomy Group_13',
 'Healthcare Provider Taxonomy Group_14',
 'Healthcare Provider Taxonomy Group_15']

In [57]:
count = 0
neep_list = []
for gm_chunk in pd.read_csv(npi_file, encoding='utf-8',
                                error_bad_lines=False, chunksize=50000):
    tbl = gm_chunk[gm_chunk['Entity Type Code'] == 1].drop(columns=bad_cols)
    neep_list.append(tbl)
    count += 1
    print(f'{count} chunks down')
    print(f'{len(tbl)} more rows')

1 chunks down
39190 more rows
2 chunks down
39595 more rows
3 chunks down
39891 more rows
4 chunks down
39735 more rows
5 chunks down
40830 more rows
6 chunks down
41524 more rows
7 chunks down
41605 more rows
8 chunks down
41473 more rows
9 chunks down
40634 more rows
10 chunks down
40125 more rows
11 chunks down
36314 more rows
12 chunks down
33539 more rows
13 chunks down
35787 more rows
14 chunks down
36349 more rows
15 chunks down
36960 more rows
16 chunks down
34874 more rows
17 chunks down
35069 more rows
18 chunks down
37093 more rows
19 chunks down
33232 more rows
20 chunks down
37267 more rows
21 chunks down
36281 more rows
22 chunks down
35541 more rows
23 chunks down
32549 more rows
24 chunks down
35563 more rows
25 chunks down
37129 more rows
26 chunks down
36635 more rows
27 chunks down
34930 more rows
28 chunks down
36398 more rows
29 chunks down
34979 more rows
30 chunks down
35485 more rows
31 chunks down
34865 more rows
32 chunks down
34143 more rows
33 chunks down
35499 more rows
34 chunks down
34510 more rows
35 chunks down
34416 more rows
36 chunks down
33278 more rows
37 chunks down
34666 more rows
38 chunks down
34265 more rows
39 chunks down
34949 more rows
40 chunks down
34778 more rows
41 chunks down
34824 more rows
42 chunks down
35297 more rows
43 chunks down
35369 more rows
44 chunks down
36036 more rows
45 chunks down
36654 more rows
46 chunks down
35307 more rows
47 chunks down
33012 more rows
48 chunks down
31384 more rows
49 chunks down
30906 more rows
50 chunks down
30290 more rows
51 chunks down
31446 more rows
52 chunks down
34727 more rows
53 chunks down
37915 more rows
54 chunks down
37212 more rows
55 chunks down
36402 more rows
56 chunks down
34608 more rows
57 chunks down
34108 more rows
58 chunks down
36382 more rows
59 chunks down
38415 more rows
60 chunks down
36387 more rows
61 chunks down
34441 more rows
62 chunks down
35438 more rows
63 chunks down
37655 more rows
64 chunks down
39412 more rows
65 chunks down
37049 more rows
66 chunks down
35345 more rows
67 chunks down
34229 more rows
68 chunks down
37481 more rows
69 chunks down
39591 more rows
70 chunks down
39286 more rows
71 chunks down
39977 more rows
72 chunks down
36687 more rows
73 chunks down
35258 more rows
74 chunks down
37955 more rows
75 chunks down
40169 more rows
76 chunks down
40371 more rows
77 chunks down
38200 more rows
78 chunks down
35893 more rows
79 chunks down
36485 more rows
80 chunks down
39416 more rows
81 chunks down
39811 more rows
82 chunks down
38994 more rows
83 chunks down
36329 more rows
84 chunks down
35666 more rows
85 chunks down
38207 more rows
86 chunks down
39328 more rows
87 chunks down
39808 more rows
88 chunks down
38791 more rows
89 chunks down
36935 more rows
90 chunks down
36126 more rows
91 chunks down
37737 more rows
92 chunks down
38276 more rows
93 chunks down
38633 more rows
94 chunks down
38311 more rows
95 chunks down
36934 more rows
96 chunks down
36273 more rows
97 chunks down
37982 more rows
98 chunks down
39829 more rows
99 chunks down
40729 more rows
100 chunks down
39355 more rows
101 chunks down
37530 more rows
102 chunks down
37013 more rows
103 chunks down
36729 more rows
104 chunks down
40941 more rows
105 chunks down
40755 more rows
106 chunks down
40723 more rows
107 chunks down
39134 more rows
108 chunks down
39492 more rows
109 chunks down
39402 more rows
110 chunks down
41200 more rows
111 chunks down
43201 more rows
112 chunks down
41623 more rows
113 chunks down
42881 more rows
114 chunks down
42076 more rows
115 chunks down
42281 more rows
116 chunks down
40651 more rows
117 chunks down
40338 more rows
118 chunks down
40099 more rows
119 chunks down
43224 more rows
120 chunks down
41587 more rows
121 chunks down
42245 more rows
122 chunks down
41994 more rows
123 chunks down
41735 more rows
124 chunks down
40478 more rows
125 chunks down
39906 more rows
126 chunks down
40022 more rows
127 chunks down
43301 more rows
128 chunks down
40770 more rows
129 chunks down
40345 more rows
130 chunks down
40798 more rows
131 chunks down
40664 more rows
132 chunks down
40740 more rows
133 chunks down
42555 more rows
134 chunks down
41155 more rows
135 chunks down
40066 more rows
136 chunks down
43047 more rows
137 chunks down
41455 more rows
138 chunks down
33788 more rows

In [58]:
npi = pd.concat(neep_list)

In [59]:
npi.columns = [c.upper().replace(' ', '_') for c in npi.columns.values]

In [60]:
PPD = use.get_ppd()

C:/Users/vigrose/Data/PPD\ppd_data_20210724.csv

In [61]:
PPD['ME'] = use.fix_me(PPD.ME)

In [62]:
me_npi = use.get_npi_to_me()

In [63]:
npi['NPI'] = npi.NPI.astype(str)

In [64]:
npi = pd.merge(npi, me_npi, on='NPI')

In [65]:
PPD = PPD[['ME', 'FIRST_NAME', 'MIDDLE_NAME','LAST_NAME', 'SUFFIX',
       'PRIM_SPEC_CD', 'PE_CD', 'FAX_NUMBER', 'TOP_CD', 'TELEPHONE_NUMBER', 'NO_CONTACT_IND']]

In [66]:
PPD['ME'] = use.fix_me(PPD.ME)

In [69]:
npi = pd.merge(npi, PPD[(PPD.TOP_CD==20)&(PPD.NO_CONTACT_IND!='N')], on='ME')

In [70]:
npi = npi.rename(columns = {'PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS' : 'POLO_MAILING_LINE_2' ,
       'PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS': 'POLO_MAILING_LINE_1',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME': 'POLO_CITY',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME': 'POLO_STATE',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE': 'POLO_ZIP',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER':'TELEPHONE_NUMBER',
        'TELEPHONE_NUMBER':'TELEPHONE_PPD'})

In [71]:
npi = npi.fillna('None')

In [72]:
no_phone_sample = npi[npi.TELEPHONE_PPD == 'None'].drop_duplicates('TELEPHONE_NUMBER').sample(10000)

In [73]:
with_phone_sample = npi[npi.ME.isin(no_phone_sample.ME)==False].drop_duplicates('TELEPHONE_NUMBER').sample(18000)

In [75]:
all_sample = pd.concat([no_phone_sample, with_phone_sample])

In [76]:
all_sample['TELEPHONE_NUMBER'] = [use.fix_phone(x) for x in all_sample.TELEPHONE_NUMBER]

In [78]:
present_employment_key = {
        11: 'Self-Employed Solo Practice',
        13: 'Two Physician Practice-Full Or Part Owner',
        21: 'Other-Patient Care',
        22: 'Locum Tenens',
        30: 'Group Practice',
        35: 'HMO',
        40: 'Medical School',
        50: 'Non-Government Hospital',
        63: 'City/County/State Government-Hospital',
        64: 'City/County/State Government-Other Than Hospital',
        81: 'Federal Government-Hospital/Army',
        82: 'Federal Government-Hospital/Navy',
        83: 'Federal Government-Hospital/Air Force',
        84: 'Federal Government-Hospital/Usphs',
        85: 'Federal Government-Hospital/Vet Admin',
        86: 'Federal Government-Hospital/Other Agency',
        101: 'Other/Non-Patient Care',
        110: 'No Classification'
    }

In [79]:
all_sample['DESCRIPTION'] = [present_employment_key[x] for x in all_sample.PE_CD]

In [85]:
humach_columns = [
        'ME',
        'FIRST_NAME',
        'MIDDLE_NAME',
        'LAST_NAME',
        'SUFFIX',
        'POLO_MAILING_LINE_1',
        'POLO_MAILING_LINE_2',
        'POLO_CITY',
        'POLO_STATE',
        'POLO_ZIP',
        'TELEPHONE_NUMBER',
        'PRIM_SPEC_CD',
        'DESCRIPTION',
        'PE_CD',
        'FAX_NUMBER'
    ]

In [89]:
all_sample['POLO_ZIP'] = [use.fix_zipcode(x) for x in all_sample.POLO_ZIP]

In [92]:
all_sample[humach_columns].to_excel('../../Data/NPI/NPI_Humach_Sample_21-07-27.xlsx', index=False)

In [41]:
npi = npi.fillna('None')
dpc = dpc[dpc.fillna('None')]

In [47]:
npi[['PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER','PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER']]

,PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER,PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER
0,3088652512,3.08865e+09
1,9043881820,9.04388e+09
2,2814405006,2.81441e+09
3,4198423000,4.19842e+09
4,8067810360,8.06761e+09
...,...,...
1069577,6.3148e+09,6.62378e+09
1069578,2.48702e+09,2.48652e+09
1069579,4.06861e+09,4.06861e+09
1069580,8.28407e+09,8.28407e+09
1069581,7.18354e+09,9.73972e+09

In [65]:
def fix_phone(num):
    num = str(num).strip().replace('.0', '')
    if num[0] == '1':
        num = num[1:]
    num = ''.join(filter(str.isdigit, num))
    num = num[:10]
    return num

In [66]:
npi['PHONE_PPD'] = [fix_phone(x) if x != 'None' else x for x in npi.TELEPHONE_NUMBER]
npi['PHONE_NPI'] = [fix_phone(x) if x != 'None' else x for x in npi.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER]

In [68]:
mes = []
for row in npi[(npi.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER!='None')&(npi.TELEPHONE_NUMBER!='None')].itertuples():
    if row.PHONE_PPD == row.PHONE_NPI:
        mes.append(row.ME)

In [92]:
len(mes)

344090

In [71]:
dpc[(dpc.ME.isin(mes))]

,NPI,PROVIDER_ORGANIZATION_NAME_(LEGAL_BUSINESS_NAME),PROVIDER_LAST_NAME_(LEGAL_NAME),PROVIDER_FIRST_NAME,PROVIDER_MIDDLE_NAME,PROVIDER_NAME_PREFIX_TEXT,PROVIDER_NAME_SUFFIX_TEXT,PROVIDER_CREDENTIAL_TEXT,PROVIDER_OTHER_ORGANIZATION_NAME,PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,...,CITY,STATE,ZIP,TELEPHONE_NUMBER,POLO_MAILING_LINE_1,POLO_MAILING_LINE_2,POLO_CITY,POLO_STATE,POLO_ZIP,TOP_CD
3,1932102084,None,ADUSUMILLI,RAVI,K,None,None,MD,None,None,...,TOLEDO,OH,43615,4.19842e+09,PROMEDICA NORTHWEST OHIO CARDIOLOGY CONS,2940 N MCCORD RD,TOLEDO,OH,43615,20
9,1114920261,None,THACKER,RICHARD,RANDALL,DR.,None,D.O.,None,None,...,TALLAHASSEE,FL,32309,8.50879e+09,None,2770 CAPITAL MEDICAL BLVD STE 200,TALLAHASSEE,FL,32308,20
12,1750384707,None,MARKMAN,ALAN,WILLIAM,DR.,None,M.D.,None,None,...,MINNEAPOLIS,MN,55431,9.52832e+09,CREDENTIALING,8100 NORTHLAND DR,BLOOMINGTON,MN,55431,20
16,1114920162,None,DUBOSE,JON,None,DR.,None,MD,None,None,...,FARMVILLE,NC,27828,2.52642e+09,HERITAGE HOSPITAL,111 HOSPITAL DR,TARBORO,NC,27886,20
21,1073516027,None,CHANG,JOHN,CHU-HONG,DR.,None,M.D.,None,None,...,MONTEBELLO,NY,10901,8.45736e+09,None,169 N MIDDLETOWN RD,PEARL RIVER,NY,10965,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067844,1780290734,None,LU,DOANH,None,DR.,None,MD,None,None,...,HONOLULU,HI,96821,8.08692e+09,None,None,None,None,None,20
1067878,1811597586,None,MATTHEWS,MARY,KATHLEEN,None,None,MD,None,None,...,DENVER,CO,80220,3.03378e+09,None,1305 KRAMERIA ST STE H-145,DENVER,CO,80220,20
1067923,1417543240,None,EVANGELISTA,FRANK,None,None,None,None,None,None,...,BOSTON,MA,02215,8.60679e+09,None,11 SHUTTLE RD,FARMINGTON,CT,6032,20
1067965,1992394548,None,PLUCER,MARK,GERRY,None,None,None,None,None,...,GRAND BLANC,MI,48439,8.10636e+09,None,None,None,None,None,20
1069450,1629642673,None,NOBLE,SAMUEL,ROSS,None,None,M.D,None,None,...,WEST READING,PA,19611,6.10479e+09,None,200 READING AVE STE 102,WEST READING,PA,19611,20

In [77]:
npi[['MAILING_NAME','POLO_MAILING_LINE_2', 'PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS', 'PHONE_PPD','PHONE_NPI']]

,MAILING_NAME,POLO_MAILING_LINE_2,PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,PHONE_PPD,PHONE_NPI
0,DAVID A WIEBE MD,102 E HOLME ST,3500 CENTRAL AVE,3088652500,3088652512
1,WILLIAM C PILCHER MD,2300 PARK AVE STE 101B,1824 KING STREET,9042640088,9043881820
2,LAURENT GRESSOT MD,17323 RED OAK DR,17323 RED OAK DR,8326784888,2814405006
3,RAVI K ADUSUMILLI MD,2940 N MCCORD RD,2940 N MCCORD RD,4198423000,4198423000
4,ROBERT J BISBEE MD,3601 4TH ST STOP 9410,808 JOLIET AVE UNIT 120,None,8067610540
...,...,...,...,...,...
1069577,CHRISTINA M JOY MD,None,300 S WASHINGTON AVE,None,6623783783
1069578,OSAMA TARIQ MD,None,1101 W UNIVERSITY DR,None,2486525000
1069579,AARON M MAUS MD,None,620 SHADOW LN,None,4068612625
1069580,JESSE CHASTEEN MD,None,301 FISHER ST,None,8284065876
1069581,KYROLLOS G SAAD MD,None,150 BERGEN ST,None,9739724300

In [73]:
dpc.columns

Index(['NPI', 'PROVIDER_ORGANIZATION_NAME_(LEGAL_BUSINESS_NAME)',
       'PROVIDER_LAST_NAME_(LEGAL_NAME)', 'PROVIDER_FIRST_NAME',
       'PROVIDER_MIDDLE_NAME', 'PROVIDER_NAME_PREFIX_TEXT',
       'PROVIDER_NAME_SUFFIX_TEXT', 'PROVIDER_CREDENTIAL_TEXT',
       'PROVIDER_OTHER_ORGANIZATION_NAME',
       'PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE',
       'PROVIDER_OTHER_LAST_NAME', 'PROVIDER_OTHER_FIRST_NAME',
       'PROVIDER_OTHER_MIDDLE_NAME', 'PROVIDER_OTHER_NAME_PREFIX_TEXT',
       'PROVIDER_OTHER_NAME_SUFFIX_TEXT', 'PROVIDER_OTHER_CREDENTIAL_TEXT',
       'PROVIDER_OTHER_LAST_NAME_TYPE_CODE',
       'PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS',
       'PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_(IF_OUTSIDE_U.S.)',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER',
       'PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS',
       'PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_(IF_OUTSIDE_U.S.)',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER',
       'PROVIDER_ENUMERATION_DATE', 'LAST_UPDATE_DATE', 'PROVIDER_GENDER_CODE',
       'AUTHORIZED_OFFICIAL_LAST_NAME', 'AUTHORIZED_OFFICIAL_FIRST_NAME',
       'AUTHORIZED_OFFICIAL_MIDDLE_NAME',
       'AUTHORIZED_OFFICIAL_TITLE_OR_POSITION',
       'AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER', 'CERTIFICATION_DATE', 'ME',
       'MAILING_NAME', 'MAILING_LINE_1', 'MAILING_LINE_2', 'CITY', 'STATE',
       'ZIP', 'TELEPHONE_NUMBER', 'POLO_MAILING_LINE_1', 'POLO_MAILING_LINE_2',
       'POLO_CITY', 'POLO_STATE', 'POLO_ZIP', 'TOP_CD'],
      dtype='object')

In [ ]:
(npi.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER!='None')&(npi.TELEPHONE_NUMBER!='None')&

In [109]:
others = []
for row in npi[(npi.POLO_MAILING_LINE_2!='None')].itertuples():
    if is_a_match(row.POLO_MAILING_LINE_2, row.PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS, 85):
        others.append(row.ME)

In [108]:
len(npi[(npi.POLO_MAILING_LINE_2!='None')&(npi.TOP_CD==20)])

705957

In [111]:
npi[npi.ME.isin(others)][['POLO_MAILING_LINE_2', 'PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS']]

,POLO_MAILING_LINE_2,PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS
2,17323 RED OAK DR,17323 RED OAK DR
3,2940 N MCCORD RD,2940 N MCCORD RD
5,7629 TIKI DR,7629 TIKI DR
6,1205 S 7TH AVE,1205 S 7TH AVE
9,2770 CAPITAL MEDICAL BLVD STE 200,2770 CAPITAL MEDICAL BLVD
...,...,...
1069405,501 E HAMPDEN AVE,501 E HAMPDEN AVE
1069409,1051 RIVERSIDE DR UNIT 15,1051 RIVERSIDE DR UNIT 15
1069410,4400 EMILE ST,4400 EMILE ST
1069450,200 READING AVE STE 102,200 READING AVE
1069566,301 UNIVERSITY BLVD DEPT OTO,301 UNIVERSITY BLVD

In [110]:
len(others)

473937

In [88]:
dpc[dpc.ME.isin(others)]

,NPI,PROVIDER_ORGANIZATION_NAME_(LEGAL_BUSINESS_NAME),PROVIDER_LAST_NAME_(LEGAL_NAME),PROVIDER_FIRST_NAME,PROVIDER_MIDDLE_NAME,PROVIDER_NAME_PREFIX_TEXT,PROVIDER_NAME_SUFFIX_TEXT,PROVIDER_CREDENTIAL_TEXT,PROVIDER_OTHER_ORGANIZATION_NAME,PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,...,CITY,STATE,ZIP,TELEPHONE_NUMBER,POLO_MAILING_LINE_1,POLO_MAILING_LINE_2,POLO_CITY,POLO_STATE,POLO_ZIP,TOP_CD
2,1215930367,None,GRESSOT,LAURENT,None,DR.,None,M.D.,None,None,...,BELLAIRE,TX,77401,8.32678e+09,None,17323 RED OAK DR,HOUSTON,TX,77090,20
3,1932102084,None,ADUSUMILLI,RAVI,K,None,None,MD,None,None,...,TOLEDO,OH,43615,4.19842e+09,PROMEDICA NORTHWEST OHIO CARDIOLOGY CONS,2940 N MCCORD RD,TOLEDO,OH,43615,20
6,1578566626,None,KUIPERS,WARREN,D.,None,None,MD,None,None,...,PHOENIX,AZ,85007,5.20836e+09,None,1205 S 7TH AVE,PHOENIX,AZ,85007,20
9,1114920261,None,THACKER,RICHARD,RANDALL,DR.,None,D.O.,None,None,...,TALLAHASSEE,FL,32309,8.50879e+09,None,2770 CAPITAL MEDICAL BLVD STE 200,TALLAHASSEE,FL,32308,20
12,1750384707,None,MARKMAN,ALAN,WILLIAM,DR.,None,M.D.,None,None,...,MINNEAPOLIS,MN,55431,9.52832e+09,CREDENTIALING,8100 NORTHLAND DR,BLOOMINGTON,MN,55431,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067973,1982295564,None,KHALID,MOHAMMAD,None,DR.,None,MD,None,None,...,ST AUGUSTINE,FL,32086,3.01933e+09,None,300 HEALTH PARK BLVD STE 1000,ST AUGUSTINE,FL,32086,20
1067994,1184217838,None,SCHWARTZ,JEFFREY,M.,DR.,None,MD,None,None,...,LOS ANGELES,CA,90025,3.10392e+09,None,12304 SANTA MONICA BLVD STE 210,LOS ANGELES,CA,90025,20
1068033,1972188746,None,FARCUS,GERALD,L,DR.,None,MD,None,None,...,W LAKE HILLS,TX,78746,2.12356e+09,None,309 WESTLAKE DR,W LAKE HILLS,TX,78746,20
1069409,1558945261,None,KLITZMAN,ROBERT,None,None,None,None,None,None,...,NEW YORK,NY,10032,2.12662e+09,None,1051 RIVERSIDE DR UNIT 15,NEW YORK,NY,10032,20
1069450,1629642673,None,NOBLE,SAMUEL,ROSS,None,None,M.D,None,None,...,WEST READING,PA,19611,6.10479e+09,None,200 READING AVE STE 102,WEST READING,PA,19611,20

In [91]:
dpc[(dpc.ME.isin(others))&(dpc.ME.isin(mes))][['POLO_MAILING_LINE_2', 'PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS']]

,POLO_MAILING_LINE_2,PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS
3,2940 N MCCORD RD,2940 N MCCORD RD
9,2770 CAPITAL MEDICAL BLVD STE 200,2770 CAPITAL MEDICAL BLVD
12,8100 NORTHLAND DR,8100 NORTHLAND DR
16,111 HOSPITAL DR,111 HOSPITAL DR
21,169 N MIDDLETOWN RD,169 N MIDDLETOWN RD
...,...,...
1067768,725 HAMLINE ST,725 HAMLINE STREET
1067805,4524 SAN PEDRO PL,4524 SAN PEDRO PL
1067843,533 W NORTH AVE STE 206,533 W NORTH AVE
1067923,11 SHUTTLE RD,11 SHUTTLE RD
1069450,200 READING AVE STE 102,200 READING AVE

In [97]:
ppd[ppd.ME.isin(mes)][['ME','TELEPHONE_NUMBER']].to_csv('../../Data/NPI/npi_phone_match.csv', index=False)

In [99]:
npi[npi.TOP_CD==20]

,NPI,PROVIDER_ORGANIZATION_NAME_(LEGAL_BUSINESS_NAME),PROVIDER_LAST_NAME_(LEGAL_NAME),PROVIDER_FIRST_NAME,PROVIDER_MIDDLE_NAME,PROVIDER_NAME_PREFIX_TEXT,PROVIDER_NAME_SUFFIX_TEXT,PROVIDER_CREDENTIAL_TEXT,PROVIDER_OTHER_ORGANIZATION_NAME,PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,...,ZIP,TELEPHONE_NUMBER,POLO_MAILING_LINE_1,POLO_MAILING_LINE_2,POLO_CITY,POLO_STATE,POLO_ZIP,TOP_CD,PHONE_PPD,PHONE_NPI
1,1588667638,None,PILCHER,WILLIAM,C,DR.,None,MD,None,None,...,32210,9.04264e+09,None,2300 PARK AVE STE 101B,ORANGE PARK,FL,32073,20,9042640088,9043881820
2,1215930367,None,GRESSOT,LAURENT,None,DR.,None,M.D.,None,None,...,77401,8.32678e+09,None,17323 RED OAK DR,HOUSTON,TX,77090,20,8326784888,2814405006
3,1932102084,None,ADUSUMILLI,RAVI,K,None,None,MD,None,None,...,43615,4.19842e+09,PROMEDICA NORTHWEST OHIO CARDIOLOGY CONS,2940 N MCCORD RD,TOLEDO,OH,43615,20,4198423000,4198423000
4,1750384806,None,BISBEE,ROBERT,None,DR.,None,MD,None,None,...,79416,None,TEXAS TECH UNIVERSITY,3601 4TH ST STOP 9410,LUBBOCK,TX,79430,20,None,8067610540
5,1669475711,None,SUNG,BIN,SHENG,None,None,M. D.,None,None,...,77479,None,FULSHEAR FAMILY MEDICINE,7629 TIKI DR,FULSHEAR,TX,77441,20,None,2813460018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069170,1912588237,None,ASKHETA,MAZEN,None,None,None,None,None,None,...,20172,None,None,None,None,None,None,20,None,3045984890
1069284,1841872231,None,DEMBIN,HOWARD,None,None,None,None,None,None,...,06468,5.16531e+09,None,None,None,None,None,20,5165308095,2034458313
1069292,1194307439,None,BRUNO,JANET,None,DR.,None,MD,None,None,...,85268,None,None,950 W ELLIOT RD STE 220,TEMPE,AZ,85284,20,None,6028854333
1069409,1558945261,None,KLITZMAN,ROBERT,None,None,None,None,None,None,...,10032,2.12662e+09,None,1051 RIVERSIDE DR UNIT 15,NEW YORK,NY,10032,20,2126624445,6467746912
1069450,1629642673,None,NOBLE,SAMUEL,ROSS,None,None,M.D,None,None,...,19611,6.10479e+09,None,200 READING AVE STE 102,WEST READING,PA,19611,20,6104788662,6104788662

In [100]:
npi.columns

Index(['NPI', 'PROVIDER_ORGANIZATION_NAME_(LEGAL_BUSINESS_NAME)',
       'PROVIDER_LAST_NAME_(LEGAL_NAME)', 'PROVIDER_FIRST_NAME',
       'PROVIDER_MIDDLE_NAME', 'PROVIDER_NAME_PREFIX_TEXT',
       'PROVIDER_NAME_SUFFIX_TEXT', 'PROVIDER_CREDENTIAL_TEXT',
       'PROVIDER_OTHER_ORGANIZATION_NAME',
       'PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE',
       'PROVIDER_OTHER_LAST_NAME', 'PROVIDER_OTHER_FIRST_NAME',
       'PROVIDER_OTHER_MIDDLE_NAME', 'PROVIDER_OTHER_NAME_PREFIX_TEXT',
       'PROVIDER_OTHER_NAME_SUFFIX_TEXT', 'PROVIDER_OTHER_CREDENTIAL_TEXT',
       'PROVIDER_OTHER_LAST_NAME_TYPE_CODE',
       'PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS',
       'PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_(IF_OUTSIDE_U.S.)',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER',
       'PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER',
       'PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS',
       'PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_(IF_OUTSIDE_U.S.)',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER',
       'PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER',
       'PROVIDER_ENUMERATION_DATE', 'LAST_UPDATE_DATE', 'PROVIDER_GENDER_CODE',
       'AUTHORIZED_OFFICIAL_LAST_NAME', 'AUTHORIZED_OFFICIAL_FIRST_NAME',
       'AUTHORIZED_OFFICIAL_MIDDLE_NAME',
       'AUTHORIZED_OFFICIAL_TITLE_OR_POSITION',
       'AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER', 'CERTIFICATION_DATE', 'ME',
       'MAILING_NAME', 'MAILING_LINE_1', 'MAILING_LINE_2', 'CITY', 'STATE',
       'ZIP', 'TELEPHONE_NUMBER', 'POLO_MAILING_LINE_1', 'POLO_MAILING_LINE_2',
       'POLO_CITY', 'POLO_STATE', 'POLO_ZIP', 'TOP_CD', 'PHONE_PPD',
       'PHONE_NPI'],
      dtype='object')

In [101]:
npi[['NPI', 'ME', 'TOP_CD', 'PHONE_PPD','PHONE_NPI']].to_csv('../../Data/NPI/NPI_PHONES.csv', index=False)

In [102]:
npi[['NPI', 'ME', 'TOP_CD', 'PHONE_PPD','PHONE_NPI']]

                NPI           ME  TOP_CD   PHONE_PPD   PHONE_NPI
0        1679576722  01902640980      71  3088652500  3088652512
1        1588667638  01201861256      20  9042640088  9043881820
2        1215930367  86904850022      20  8326784888  2814405006
3        1932102084  49558830041      20  4198423000  4198423000
4        1750384806  04815940089      20        None  8067610540
...             ...          ...     ...         ...         ...
1069577  1316515984  79601210016     100        None  6623783783
1069578  1659949238  02512211324      12        None  2486525000
1069579  1083282669  05404191791      12        None  4068612625
1069580  1932777554  02312211303      12        None  8284065876
1069581  1801464417  03305210918      12        None  9739724300

[1069582 rows x 5 columns]

In [113]:
adds = []
nums = []
for row in npi.itertuples():
    if row.PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS == row.PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS:
        adds.append(row.ME)
    if row.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER == row.PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER:
        nums.append(row.ME)

In [114]:
len(adds)

552937

In [115]:
len(nums)

593471

In [118]:
npi[(npi.TOP_CD==20)]

,NPI,PROVIDER_ORGANIZATION_NAME_(LEGAL_BUSINESS_NAME),PROVIDER_LAST_NAME_(LEGAL_NAME),PROVIDER_FIRST_NAME,PROVIDER_MIDDLE_NAME,PROVIDER_NAME_PREFIX_TEXT,PROVIDER_NAME_SUFFIX_TEXT,PROVIDER_CREDENTIAL_TEXT,PROVIDER_OTHER_ORGANIZATION_NAME,PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE,...,ZIP,TELEPHONE_NUMBER,POLO_MAILING_LINE_1,POLO_MAILING_LINE_2,POLO_CITY,POLO_STATE,POLO_ZIP,TOP_CD,PHONE_PPD,PHONE_NPI
1,1588667638,None,PILCHER,WILLIAM,C,DR.,None,MD,None,None,...,32210,9.04264e+09,None,2300 PARK AVE STE 101B,ORANGE PARK,FL,32073,20,9042640088,9043881820
2,1215930367,None,GRESSOT,LAURENT,None,DR.,None,M.D.,None,None,...,77401,8.32678e+09,None,17323 RED OAK DR,HOUSTON,TX,77090,20,8326784888,2814405006
3,1932102084,None,ADUSUMILLI,RAVI,K,None,None,MD,None,None,...,43615,4.19842e+09,PROMEDICA NORTHWEST OHIO CARDIOLOGY CONS,2940 N MCCORD RD,TOLEDO,OH,43615,20,4198423000,4198423000
4,1750384806,None,BISBEE,ROBERT,None,DR.,None,MD,None,None,...,79416,None,TEXAS TECH UNIVERSITY,3601 4TH ST STOP 9410,LUBBOCK,TX,79430,20,None,8067610540
5,1669475711,None,SUNG,BIN,SHENG,None,None,M. D.,None,None,...,77479,None,FULSHEAR FAMILY MEDICINE,7629 TIKI DR,FULSHEAR,TX,77441,20,None,2813460018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069170,1912588237,None,ASKHETA,MAZEN,None,None,None,None,None,None,...,20172,None,None,None,None,None,None,20,None,3045984890
1069284,1841872231,None,DEMBIN,HOWARD,None,None,None,None,None,None,...,06468,5.16531e+09,None,None,None,None,None,20,5165308095,2034458313
1069292,1194307439,None,BRUNO,JANET,None,DR.,None,MD,None,None,...,85268,None,None,950 W ELLIOT RD STE 220,TEMPE,AZ,85284,20,None,6028854333
1069409,1558945261,None,KLITZMAN,ROBERT,None,None,None,None,None,None,...,10032,2.12662e+09,None,1051 RIVERSIDE DR UNIT 15,NEW YORK,NY,10032,20,2126624445,6467746912
1069450,1629642673,None,NOBLE,SAMUEL,ROSS,None,None,M.D,None,None,...,19611,6.10479e+09,None,200 READING AVE STE 102,WEST READING,PA,19611,20,6104788662,6104788662

In [119]:
400164/790203

0.506406581599918

In [120]:
440921/790203

0.5579844672824578

In [121]:
ppd[ppd.TOP_CD==20]

,ME,MAILING_NAME,MAILING_LINE_1,MAILING_LINE_2,CITY,STATE,ZIP,TELEPHONE_NUMBER,POLO_MAILING_LINE_1,POLO_MAILING_LINE_2,POLO_CITY,POLO_STATE,POLO_ZIP,TOP_CD
0,00102000013,MICHAEL J STANFORD MD,NaN,4899 REYNOLDS LN,VESTAVIA,AL,35242,NaN,NaN,NaN,NaN,NaN,NaN,20
2,00102000030,MARK T JACKSON MD,NaN,1000 BLYTHE BLVD,CHARLOTTE,NC,28203,8.282544e+09,MOUNTAIN AREA PEDIATRIC ASSOC,500 CENTREPARK DR,ASHEVILLE,NC,28805,20
3,00102000048,NADHIWAN S MAISIAK MD,NaN,8275 E BELL RD APT 2161,SCOTTSDALE,AZ,85260,3.138732e+09,NaN,14502 W MEEKER BLVD,SUN CITY WEST,AZ,85375,20
4,00102000056,RAJIV B GALA MD,NaN,44 WREN ST,NEW ORLEANS,LA,70124,5.048430e+09,OCHSNER MEDICAL CENTER,4429 CLARA ST STE 400,NEW ORLEANS,LA,70115,20
5,00102000064,CAROL L ADAMS MD,NaN,608 WOODLAND TRACE WAY,JASPER,AL,35504,2.052217e+09,NaN,300 N AIRPORT RD STE 2,JASPER,AL,35504,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302789,96501940019,MUKUL GUPTA MD,NaN,317 W PUEBLO ST,SANTA BARBARA,CA,93105,8.058983e+09,SANSUM CLINIC,540 W PUEBLO ST,SANTA BARBARA,CA,93105,20
1302790,96501950014,DINESH BHASKARAN MD,NaN,116 ARCHBERRY DR,WEXFORD,PA,15090,7.247738e+09,NaN,1000 DUTCH RIDGE RD,BEAVER,PA,15009,20
1302794,96501960036,KAMISHELE MAILA MD,NaN,300 JUBILEE DR,PEABODY,MA,01960,4.199966e+09,ST RITA'S MEDICAL CENTER,730 W MARKET ST,LIMA,OH,45801,20
1302795,96501960044,MWIZA GAUSI MD,NaN,4705 JEFFERSON WOOD CT,GREENSBORO,NC,27410,4.347992e+09,DANVILLE REGIONAL MEDICAL,142 S MAIN ST,DANVILLE,VA,24541,20
1302796,96501960052,MASIKU A MDALA-GAUSI MD,NaN,4705 JEFFERSON WOOD CT,GREENSBORO,NC,27410,3.367135e+09,NaN,1 MEDICAL CENTER BLVD,WINSTON SALEM,NC,27157,20

In [123]:
201487/818742

0.24609339694311516

In [125]:
ppd.columns

Index(['ME', 'MAILING_NAME', 'MAILING_LINE_1', 'MAILING_LINE_2', 'CITY',
       'STATE', 'ZIP', 'TELEPHONE_NUMBER', 'POLO_MAILING_LINE_1',
       'POLO_MAILING_LINE_2', 'POLO_CITY', 'POLO_STATE', 'POLO_ZIP', 'TOP_CD'],
      dtype='object')

In [ ]:
phone missing