In [1]:
import pandas as pd

In [21]:
cities = pd.read_excel('../../Data/Measurement/area_codes.xlsx', sheet_name='Sheet2')
states = pd.read_excel('../../Data/Measurement/area_codes.xlsx', sheet_name='state_area_codes')

In [25]:
state_codes = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming',
    'AB': 'Alberta',
  'BC': 'British Columbia',
  'MB': 'Manitoba',
  'NB': 'New Brunswick',
  'NL': 'Newfoundland and Labrador',
  'NS': 'Nova Scotia',
  'NT': 'Northwest Territories',
  'NU': 'Nunavut',
  'ON': 'Ontario',
  'PE': 'Prince Edward Island',
  'QC': 'Quebec',
  'SK': 'Saskatchewan',
  'YT': 'Yukon'
}

In [26]:
dict_list = []
for row in cities.itertuples():
    spliz = row.Code.split('-')
    area_code = spliz[0].strip()
    location = spliz[1].split(',')
    if len(location)==2:
        city = location[0].strip()
        state = state_codes[location[1].strip()]
    else:
        state = spliz[1].strip()
        city = None
    new_dict = {
        'area_code':area_code,
        'state':state,
        'city':city
    }
    dict_list.append(new_dict)

In [28]:
dict_list = []
for row in states.itertuples():
    spliz = row.Code.split(',')
    area_code = spliz[0].strip()
    location = spliz[1].split(',')
    if len(location)==2:
        city = location[0].strip()
        state = state_codes[location[1].strip()]
    else:
        state = spliz[1].strip()
        city = None
    new_dict = {
        'area_code':area_code,
        'state':state,
        'city':city
    }
    dict_list.append(new_dict)

,State,Code
0,Alabama,"205, 251, 256, 334, 938"
1,Alaska,907
2,Arizona,"480, 520, 602, 623, 928"
3,Arkansas,"479, 501, 870"
4,California,"209, 213, 279, 310, 323, 408, 415, 424, 442, 5..."
5,Colorado,"303, 719, 720, 970"
6,Connecticut,"203, 475, 860, 959"
7,Delaware,302
8,Florida,"239, 305, 321, 352, 386, 407, 561, 727, 754, 7..."
9,Georgia,"229, 404, 470, 478, 678, 706, 762, 770, 912"
10,Hawaii,808
11,Idaho,"208, 986"
12,Illinois,"217, 224, 309, 312, 331, 618, 630, 708, 773, 7..."
13,Indiana,"219, 260, 317, 463, 574, 765, 812, 930"
14,Iowa,"319, 515, 563, 641, 712"
15,Kansas,"316, 620, 785, 913"
16,Kentucky,"270, 364, 502, 606, 859"
17,Louisiana,"225, 318, 337, 504, 985"
18,Maine,207
19,Maryland,"240, 301, 410, 443, 667"
20,Massachusetts,"339, 351, 413, 508, 617, 774, 781, 857, 978"
21,Michigan,"231, 248, 269, 313, 517, 586, 616, 734, 810, 9..."
22,Minnesota,"218, 320, 507, 612, 651, 763, 952"
23,Mississippi,"228, 601, 662, 769"
24,Missouri,"314, 417, 573, 636, 660, 816"
25,Montana,406
26,Nebraska,"308, 402, 531"
27,Nevada,"702, 725, 775"
28,New Hampshire,603
29,New Jersey,"201, 551, 609, 640, 732, 848, 856, 862, 908, 973"
30,New Mexico,"505, 575"
31,New York,"212, 315, 332, 347, 516, 518, 585, 607, 631, 6..."
32,North Carolina,"252, 336, 704, 743, 828, 910, 919, 980, 984"
33,North Dakota,701
34,Ohio,"216, 220, 234, 330, 380, 419, 440, 513, 567, 6..."
35,Oklahoma,"405, 539, 580, 918"
36,Oregon,"458, 503, 541, 971"
37,Pennsylvania,"215, 223, 267, 272, 412, 445, 484, 570, 610, 7..."
38,Rhode Island,401
39,South Carolina,"803, 843, 854, 864"
40,South Dakota,605
41,Tennessee,"423, 615, 629, 731, 865, 901, 931"
42,Texas,"210, 214, 254, 281, 325, 346, 361, 409, 430, 4..."
43,Utah,"385, 435, 801"
44,Vermont,802
45,Virginia,"276, 434, 540, 571, 703, 757, 804"
46,Washington,"206, 253, 360, 425, 509, 564"
47,"Washington, DC",202
48,West Virginia,"304, 681"
49,Wisconsin,"262, 414, 534, 608, 715, 920"
50,Wyoming,307
51,American Samoa,684
52,Guam,671
53,Northern Mariana Islands,670
54,Puerto Rico,"787, 939"
55,Virgin Islands,340

In [31]:
pd.DataFrame(dict_list).to_csv('../../Data/Measurement/PhoneAreaCode.csv', index=False)