In [1]:
import pandas as pd

In [3]:
ppd = pd.read_csv('../../Data/Scorecard/ppd_data_20211106.csv')

C:\Users\vigrose\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (9,13,14,16,20,21,38,42,49,56,57,64,65,66,72,78,79,80) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
dpc = ppd[ppd.TOP_CD==20]

In [7]:
polo_columns = ['POLO_MAILING_LINE_1', 'POLO_MAILING_LINE_2','POLO_CITY', 'POLO_STATE', 'POLO_ZIP']

In [12]:
dpc = dpc.fillna('None')

In [14]:
this_dict_list = []
for column in polo_columns:
    count = len(dpc[dpc[column]!='None'])
    this_dict = {
        'COLUMN':column,
        'COUNT':count
    }
    this_dict_list.append(this_dict)

In [18]:
pd.DataFrame(this_dict_list).to_csv('../../Data/Scorecard/POLO_Count_Options.csv', index=False)

In [19]:
dpc[(dpc.POLO_MAILING_LINE_1!='None')|(dpc.POLO_MAILING_LINE_2!='None')|(dpc.POLO_CITY!='None')|(dpc.POLO_STATE!='None')|(dpc.POLO_ZIP!='None')]

,ME,RECORD_ID,UPDATE_TYPE,ADDRESS_TYPE,MAILING_NAME,LAST_NAME,FIRST_NAME,MIDDLE_NAME,SUFFIX,MAILING_LINE_1,...,POLO_STATE,POLO_ZIP,POLO_SECTOR,POLO_CARRIER_ROUTE,MOST_RECENT_FORMER_LAST_NAME,MOST_RECENT_FORMER_MIDDLE_NAME,MOST_RECENT_FORMER_FIRST_NAME,NEXT_MOST_RECENT_FORMER_LAST,NEXT_MOST_RECENT_FORMER_MIDDLE,NEXT_MOST_RECENT_FORMER_FIRST
2,102000030,A,1,1,MARK T JACKSON MD,JACKSON,MARK,THOMAS,None,None,...,NC,28805,1262,C082,None,None,None,None,None,None
3,102000048,A,1,2,NADHIWAN S MAISIAK MD,MAISIAK,NADHIWAN,SAKARIN,None,None,...,AZ,85375,5282,C045,None,None,None,None,None,None
4,102000056,A,1,2,RAJIV B GALA MD,GALA,RAJIV,BABULAL,None,None,...,LA,70115,6949,C003,None,None,None,None,None,None
5,102000064,A,1,2,CAROL L ADAMS MD,ADAMS,CAROL,LYNN,None,None,...,AL,35504,2516,C009,DANIELS,LYNN,CAROL,None,None,None
6,102000072,A,1,2,JAMES H BANKSTON JR MD,BANKSTON,JAMES,HAROLD,2,None,...,AL,35406,1800,C057,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302528,96501930013,A,1,2,ANANT K SHAH MD,SHAH,ANANT,KUMAR,None,None,...,FL,33542,3501,C069,SHAH,M,ANANTKUMAR,None,None,None
1302529,96501930021,A,1,2,RAJIV JETLY MD,JETLY,RAJIV,None,None,None,...,AZ,86314,1222,H079,None,None,None,None,None,None
1302530,96501940019,A,1,1,MUKUL GUPTA MD,GUPTA,MUKUL,None,None,None,...,CA,93105,4365,C013,None,None,None,None,None,None
1302531,96501950014,A,1,2,DINESH BHASKARAN MD,BHASKARAN,DINESH,None,None,None,...,PA,15009,9727,R001,None,None,None,None,None,None
1302537,96501960052,A,1,2,MASIKU A MDALA-GAUSI MD,MDALA-GAUSI,MASIKU,AGATHA,None,None,...,NC,27157,1,C000,None,None,None,None,None,None

In [21]:
len('606556789')

9