In [1]:
# import dependencies
import pandas as pd

In [2]:
#Read csvs:
disconnected_df = pd.read_csv('disconnected_final.csv')
connected_df = pd.read_csv('connected_final.csv')

In [6]:
#Get matches 
address_match = 0
city_match = 0
zipcode_match = 0
for row in disconnected_df.itertuples():
    if row.Address == row.OFFICE_ADDRESS_LINE_2:
        address_match += 1
    if row.City == row.OFFICE_ADDRESS_CITY:
        city_match += 1
    if row.Zipcode == row.OFFICE_ADDRESS_ZIP:
        zipcode_match += 1
print (f'{address_match} addresses match  {city_match} cities match  {zipcode_match} zipcodes match')

8 addresses match  37 cities match  0 zipcodes match

In [7]:
#Get matches 2
address_match = 0
city_match = 0
zipcode_match = 0
for row in connected_df.itertuples():
    if row.Address == row.OFFICE_ADDRESS_LINE_2:
        address_match += 1
    if row.City == row.OFFICE_ADDRESS_CITY:
        city_match += 1
    if row.Zipcode == row.OFFICE_ADDRESS_ZIP:
        zipcode_match += 1
print (f'{address_match} addresses match  {city_match} cities match  {zipcode_match} zipcodes match')

41 addresses match  77 cities match  74 zipcodes match

In [5]:
#def med words

med_words = ['cancer', 'cardiology', 'neurology', 'family care', 'pulmonary', 'anesthesia', 'orthope', 'urgent care', 'allergy', 'kidney', 'surgery', 'hosp', 'mri', 'throat', 'dentist', 'med', 'clinic', 'health', 'gastroenter','anesthesiologist','patient','physician','surgeon','doctor','hospital', 'md', 'medical']

In [26]:
#How many names contain med words?

healthcount = 0
false_neg=[]
for row in connected_df.itertuples():
    healthy = False
    for word in med_words:
        if word in row.Name.lower():
            healthy = True
    if healthy == True:    
        healthcount += 1
    else:
        false_neg.append(row.Name)

print(f'TP:{healthcount}  FN:{100 - healthcount} ')

TP:79  FN:21

In [15]:
#Checking to see if algoorithm missed any medical words
false_neg

['BRUCE TRONIC',
 'DREW LAYNE',
 'TIME FACTOR MANAGEMENT',
 'CIGNA CORP',
 'BRUCE D BULLOCK',
 'ARTHUR L GLAZE',
 'ACHYUTHA S PUJARI',
 'GEISINGER',
 'GRAND STRAND RE',
 'MANUEL MACAPINLAC',
 'UNIVERSITY OF MN',
 'MIHS MAIN',
 'HEATHER BOXERMAN',
 'CHRISTIANA CARE',
 'ROLAND A HESTER',
 'RADI ASSOC TARR',
 'GREGORY PETERSON',
 'FRANCISCAN ALLI',
 'G NIE',
 'NORMAN MINARS',
 'ST MARY MERCY']

In [27]:
#Medical word count for disconnnected numbers

healthcount = 0
false_pos=[]
neg =[]
for row in disconnected_df.itertuples():
    healthy = False
    for word in med_words:
        if word in str(row.Name).lower():
            healthy = True
    if healthy == True:    
        healthcount += 1
        false_pos.append(row.Name)
    else:
        neg.append(row.Name)

print(f'FP:{healthcount}  TN:{100 - healthcount} ')

FP:44  TN:56

In [28]:
#Checking for fakers:
neg

[nan,
 'NY PRESBYTERIAN',
 'UNIV OF TN HSC',
 'SAINT LUKES WOMENS CENTER',
 'L BHATTACHARJEE',
 'MOBILE INFIRMAR',
 'PRESTIGE INTERNATIONAL',
 'PAOLI MEMORIAL',
 nan,
 'LARRY BOWLING',
 'BROWN EMMA CARRIE',
 'OCEAN PARK CAFE RESTAURANTS ALL',
 nan,
 'S GIRLY',
 'DEPAUL M HOPE',
 'ALLISON FLEMING',
 'GSA DEPT OF VA',
 'FAREMOUTH JAMES J JR DO FP OMT JUNIOR DR',
 'VENTURA COUNTY OF',
 'ANGELA EMMONS',
 'G SRVS',
 'KAISER PERMANEN',
 'KWIK SHOP MARKET',
 'JOHN OLINDE',
 'IKEJIANI TOCHUKWU',
 'EDWARD BALDWIN',
 nan,
 'VA 4 VISN 1 VETERAN VETERANS SERVICE',
 'HACKENSACK UNIV',
 'NICHOLAS LAMBROU',
 'C GLAUCOMA',
 'UAB',
 'IUPUI ENROLLMENT CENTER UNDERGRADUATE ADMISSIONS',
 nan,
 'LA CTY OF',
 'CONTINUCARE',
 'ARCH WIRELESS',
 nan,
 'JUSTIN A ROBERTS',
 'HITCH DARTMOUTH',
 'ELSA RAMOS',
 nan,
 nan,
 'JOHN L CIEPLY',
 'MONICA RODRIGUEZ',
 'CROFT ROOFING',
 'PAUL W WELCH',
 'KAISER PERMANEN',
 'ERICKSON RETIREMENT COMMUNITIES REST HOMES',
 'HQ GLOBAL WORKPLACES',
 'S VANGALA',
 'LIFE KEY VENTURES',
 nan,
 'UNIV OF KY',
 'AMERIPATH',
 'ZIAULHAQ ZIA',
 nan,
 nan]

In [34]:
mailcount = 0
connectcount = 0
portcount = 0
novalidcount = 0
unknowncount = 0
disconnectedcount = 0
voipcount = 0
wirelesscount = 0

for row in connected_df.itertuples():
        if 'IsMailable' in str(row.Notes):
            mailcount += 1
        if 'IsConnected' in str(row.Notes):
            connectcount += 1
        if 'IsPorted' in str(row.Notes):
            portcount += 1
        if 'NotValid' in str(row.Notes):
            novalidcount += 1
        if 'IsUnknownContact' in str(row.Notes):
            unknowncount += 1
        if 'IsPossibleDisconnected' in str(row.Notes):
            disconnectedcount += 1
        if 'IsPossiblePortableVOIP' in str(row.Notes):
            voipcount += 1
        if 'IsWireless' in str(row.Notes):
            wirelesscount += 1
            
print(f'{mailcount} {connectcount} {portcount} {novalidcount} {unknowncount} {disconnectedcount} {voipcount} {wirelesscount}')

86 75 74 0 0 4 8 1

In [55]:
from analyzee_numbers import analyze_numbers

In [57]:
connected_dict = analyze_numbers(connected_df, med_words)

In [58]:
disconnected_dict = analyze_numbers(disconnected_df, med_words)

In [64]:
listicle = [connected_dict, disconnected_dict]
complete_df = pd.DataFrame(listicle, index = ('Connected','Disconnected'))

In [70]:
complete_df.to_csv('one_day.csv')

In [4]:
from variable_breakdown import variable_breakdown

In [6]:
connected_breakdwon_df = variable_breakdown(connected_df, med_words)

In [8]:
pd.DataFrame(connected_breakdwon_df)

,Address Match,Business Phone,City Match,Connected,High Quality,Low Quality,Mailable,Medium Quality,No Address,No Date,Not Valid,OFFICE_TELEPHONE,Ported,Possibly Disconnected,Possibly Portable VOIP,Relevant Name,Residential Phone,Unknown Contact,Wireless,ZipCode Match
0,0,1,0,1,0,0,0,1,0,0,0,6147884440,1,0,1,1,0,0,0,0
1,0,1,1,1,0,0,0,1,0,0,0,4052309435,1,0,0,1,0,0,0,0
2,1,1,1,1,1,0,1,0,0,0,0,3105562020,1,0,1,1,0,0,0,1
3,0,1,1,1,1,0,1,0,0,0,0,8648499555,1,0,0,1,0,0,0,1
4,1,1,1,1,1,0,1,0,0,0,0,8305383550,1,0,0,1,0,0,0,1
5,0,0,1,0,0,1,0,0,0,0,0,7817448046,0,0,0,0,1,0,0,0
6,1,1,1,1,1,0,1,0,0,0,0,3154712646,1,0,0,1,0,0,0,1
7,0,1,0,1,1,0,1,0,0,0,0,2014883131,1,0,0,1,0,0,0,1
8,0,1,0,1,1,0,1,0,0,0,0,6106702277,1,0,0,1,0,0,0,1
9,1,0,1,1,1,0,1,0,0,0,0,7404543273,1,0,0,0,1,0,0,1
10,0,1,1,1,1,0,1,0,0,0,0,6158898802,1,0,0,1,0,0,0,1
11,1,1,1,0,0,1,1,0,0,0,0,6128238001,1,0,0,1,0,0,0,1
12,1,1,1,1,1,0,1,0,0,0,0,8066772002,1,0,0,1,0,0,0,1
13,0,1,1,1,1,0,0,0,0,0,0,4173357222,0,0,0,1,0,0,0,1
14,0,1,1,0,0,1,1,0,0,0,0,7033856870,1,0,1,1,0,0,0,1
15,0,1,0,1,1,0,1,0,0,0,0,9147691600,1,0,0,1,0,0,0,0
16,1,1,1,1,1,0,1,0,0,0,0,7275448300,1,0,0,1,0,0,0,1
17,1,1,1,1,1,0,1,0,0,0,0,9164894400,1,0,0,1,0,0,0,1
18,0,1,1,1,1,0,1,0,0,0,0,3193393917,0,0,0,1,0,0,0,1
19,0,1,0,0,0,1,0,0,0,0,0,7024876510,1,0,0,0,0,0,0,0
20,1,1,1,0,0,1,1,0,0,0,0,4803455200,1,0,0,0,0,0,0,1
21,0,1,0,0,0,1,0,0,0,0,0,4403124569,0,1,0,1,0,0,0,1
22,0,0,1,1,1,0,1,0,0,0,0,8027701805,1,0,0,0,1,0,0,1
23,1,1,1,0,0,1,1,0,0,0,0,6097485380,1,0,0,1,0,0,0,1
24,1,1,1,0,0,1,1,0,0,0,0,7342422022,1,0,0,1,0,0,0,1
25,1,1,1,1,1,0,1,0,0,0,0,4069614661,1,0,0,1,0,0,0,1
26,0,1,1,1,1,0,1,0,0,0,0,9496448722,1,0,0,1,0,0,0,1
27,0,0,1,1,1,0,1,0,0,0,0,6012685640,1,0,0,0,1,0,0,1
28,0,1,1,1,1,0,1,0,0,0,0,7182654454,1,0,0,1,0,0,0,0
29,0,1,0,1,1,0,1,0,0,0,0,7659833427,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1,1,1,1,1,0,1,0,0,0,0,5755213025,1,0,0,1,0,0,0,1
71,0,1,0,1,0,0,0,1,0,0,0,3108298101,0,0,0,1,0,0,0,0
72,0,1,1,0,0,1,1,0,0,0,0,8173210499,0,0,0,0,0,0,0,0
73,0,1,1,1,0,0,0,1,0,0,0,4253941680,1,0,1,1,0,0,0,1
74,1,1,1,1,1,0,1,0,0,0,0,7062262142,1,0,0,1,0,0,0,0
75,0,1,1,1,1,0,1,0,0,0,0,4239683713,0,0,0,1,0,0,0,1
76,0,1,1,1,1,0,0,0,0,0,0,7158473339,1,0,0,1,0,0,0,1
77,1,0,1,1,1,0,1,0,0,0,0,7013238030,0,0,0,0,1,0,0,1
78,0,1,1,1,1,0,1,0,0,0,0,5596733000,1,0,0,1,0,0,0,1
79,0,1,1,0,0,1,0,0,0,0,0,2032767298,1,0,0,1,0,0,0,0
80,0,1,0,0,0,1,1,0,0,0,0,5137213200,1,1,0,1,0,0,0,0
81,0,1,1,1,1,0,1,0,0,0,0,3186883350,1,0,0,1,0,0,0,1
82,0,1,1,1,1,0,1,0,0,0,0,7878590446,1,0,0,1,0,0,0,1
83,0,1,0,0,0,1,1,0,0,0,0,3175284800,0,0,0,0,0,0,0,0
84,0,0,0,1,1,0,1,0,0,0,0,7187089611,0,0,0,0,1,0,1,0
85,0,1,0,1,1,0,1,0,0,0,0,4805432000,0,0,0,1,0,0,0,0
86,0,1,1,1,1,0,1,0,0,0,0,3303317207,1,0,0,1,0,0,0,1
87,0,1,1,1,1,0,1,0,0,0,0,2076261000,0,0,0,1,0,0,0,1
88,0,0,1,1,1,0,1,0,0,0,0,9549877512,1,0,0,0,1,0,0,1
89,1,1,1,1,1,0,1,0,0,0,0,7177951819,1,0,0,1,0,0,0,1
90,0,1,1,1,1,0,1,0,0,0,0,7704382942,1,0,0,1,0,0,0,0
91,1,1,0,0,0,1,1,0,0,0,0,3104231682,1,0,0,1,0,0,0,1
92,0,1,0,0,0,1,0,0,0,0,0,7608343545,1,0,0,1,0,0,0,0
93,0,1,0,0,0,1,1,0,0,0,0,3104236143,1,0,0,1,0,0,0,1
94,1,1,1,0,0,1,1,0,0,0,0,6035245151,0,0,0,1,0,0,0,1
95,0,1,0,1,0,0,0,1,0,0,0,7347434430,1,0,0,0,0,0,0,0
96,1,1,1,1,1,0,1,0,0,0,0,7146268630,0,0,0,1,0,0,0,1
97,0,1,1,0,0,1,1,0,0,0,0,8567577799,1,0,0,1,0,0,0,1
98,1,1,1,0,0,1,1,0,0,0,0,4193945851,1,1,0,1,0,0,0,1
99,1,1,1,1,1,0,1,0,0,0,0,9107214000,0,0,0,1,0,0,0,1

In [9]:
connected_breakdown_dict = variable_breakdown(connected_df, med_words)
connected_breakdown_df = pd.DataFrame(connected_breakdown_dict)
connected_breakdown_df.to_csv('connected_breakdown.csv')

In [10]:
disconnected_breakdown_dict = variable_breakdown(disconnected_df, med_words)
disconnected_breakdown_df = pd.DataFrame(disconnected_breakdown_dict)
disconnected_breakdown_df.to_csv('disconnected_breakdown.csv')