In [28]:
import pandas as pd
import getphone_functions10 as g

In [25]:
all_data = pd.read_csv('infinite_csvs.csv')

In [6]:
all_data = all_data[all_data['COMMENTS'].isin(['COMPLETE','NOT IN SERVICE'])]
all_data = all_data[all_data['Errors']!='GeoPhonePlus2 error: Phone Number is not valid.']
all_data = all_data.drop(columns='Errors')

KeyError: 'Errors'

In [7]:
all_data.groupby(['COMMENTS']).count()

,phone,ProviderNameOut,ProviderCityOut,ProviderStateOut,LineTypeOut,ContactNameOut,ContactAddressOut,ContactCityOut,ContactStateOut,ContactZipOut,...,PHYSICIAN_ME_NUMBER,PHYSICIAN_FIRST_NAME,PHYSICIAN_MIDDLE_NAME,PHYSICIAN_LAST_NAME,OFFICE_ADDRESS_LINE_1,OFFICE_ADDRESS_LINE_2,OFFICE_ADDRESS_CITY,OFFICE_ADDRESS_STATE,OFFICE_ADDRESS_ZIP,status
COMMENTS,,,,,,,,,,,,,,,,,,,,,
COMPLETE,445,445,445,445,445,439,357,423,423,423,...,445,445,369,445,180,445,445,445,445,445
NOT IN SERVICE,588,588,587,587,587,549,405,522,522,522,...,588,588,491,588,202,586,586,586,586,588

In [30]:
# all_data = all_data.fillna('None')
connect = all_data[all_data['COMMENTS'].isin(['COMPLETE'])]
connect=connect.fillna('None')

disconnect = all_data[all_data['COMMENTS'].isin(['NOT IN SERVICE'])]
disconnect=disconnect.fillna('None')
conn = g.analyze_numbers(connect)
dis = g.analyze_numbers(disconnect)
working = pd.DataFrame({'Connected':conn, 'Disconnected': dis})
working['Connected %']=(working['Connected']/445)*100
working['Disonnected %']=(working['Disconnected']/588)*100
working

KEITH W FACS
ANGELA MCGREW
BURT FAIBISOFF MD
BURT FAIBISOFF MD
LOWE DENEAL
LOWE DENEAL
ERICA ORREGO
ERICA ORREGO
UNIVERSITY OF MICHIGAN CREDIT UNION
RAMESH KANDALLU R MD FACS
RAMESH KANDALLU R MD FACS
GEORGE LYMAN
GEORGE LYMAN
COSERIU MICHAEL V MD
COSERIU MICHAEL V MD
DENNIS L WARNER
DENNIS L WARNER
CENTERSTONE
CENTERSTONE
SOMERA S GLINN
SOMERA S GLINN
BOBBY L BOX
BOBBY L BOX
NAZRE MAWLA MD
BUILDING YANGCO MD PA
GROUP INSIGNIA
REDDY ACHUTHA N MD
A RODE
A YEH
ABRAHAM F SYRQUIN
PEREZ MARTINEZ
MARI YANCEY
G H ZUCKERMAN
REGINA SEK
GRACIELA HERNANDEZ MD
DCMH
BENZIA DEAN MD
V FERNANDEZ
JARED A ACOBA
RAPPAPORT HOWARD R PSY D
JAMES GAZZAWAY
BEED ELAINE MD
OSVALDO RIVERA
UNIV SUBURBAN H
ALAN GIANNETTI
DAMIAN B KIM
EMERGINET
LEE PRCHAL MD
GREGORY POLLACK
TX TECH UNIV HE
MCKINNEY F PIERRE
UNIVERSITY OF MIAMI
ALTMAN DAVID ELLIOT MD
VINCE BESAW
AA OF SOUTHEAST
KAISER PERMANENTE
KELSEY WALLACE
IRSHAD ALI MD
JEFF HARRIS
LINDA BIGELOW
SARA A VELEZ
ROXIE DAVIS
WASHINGTON MUTUAL
LA ADVERTISING
KARINA LUGO
BCBS
VISIONARY MARKETING & SALES
GONZALES G TORRES
JOHN J CASSEL
T ROSELLINI
LA CTY
ERNEST MUSGRAVE
LUH HENRY H Y MD
MELINDA MERRY
KARLA J JOHNS
NARAYANAN KRISHNA MD
DONALD A MCEACHERN
ADAPT OF TEXAS
SAEED M AWAN
GILBREATH & PARK
HERBERT NORTON
LEE JULIANNE O MD
ARIZONA SPORT MEDICINE CONSULTANTS
SHAIKLEY MD INC
MCREYNOLDS EDWA
BRAUD MARIA MD
LARRY BRUNO
ROBBIE BRAND
ERIKA MILES

                        Connected  Disconnected  Connected %  Disonnected %
Address Matches               225           131    50.561798      22.278912
Business Phone                372           404    83.595506      68.707483
City Matches                  351           296    78.876404      50.340136
Connected                     311           232    69.887640      39.455782
First Name Match               74           100    16.629213      17.006803
High Quality                  277           175    62.247191      29.761905
Last Name Match                74           139    16.629213      23.639456
Low Quality                   119           310    26.741573      52.721088
Mailable                      347           401    77.977528      68.197279
Medium Quality                 43            64     9.662921      10.884354
No Address                     88           191    19.775281      32.482993
No Date                       166           385    37.303371      65.476190
No Name                         6            47     1.348315       7.993197
Ported                        279           211    62.696629      35.884354
Possibly Disconnected          14           147     3.146067      25.000000
Possibly Portable VOIP         19            12     4.269663       2.040816
Relevant Name                 313           263    70.337079      44.727891
Relevant SIC                   91            69    20.449438      11.734694
Residential Phone              56           134    12.584270      22.789116
State Match                   422           477    94.831461      81.122449
Tiny Count                      1            88     0.224719      14.965986
Unknown Contact                 6            39     1.348315       6.632653
Wireless                        1             6     0.224719       1.020408
Workplace Match                16            36     3.595506       6.122449
ZipCode Matches               319           215    71.685393      36.564626
disconnected                    0             0     0.000000       0.000000
disconnected-70                 0             0     0.000000       0.000000

In [9]:
var_dict = g.variable_breakdown(all_data)

In [10]:
var_Df = pd.DataFrame(var_dict)

In [46]:
var_Df.to_csv('all_numbers.csv')

In [47]:
all_data.to_csv('meep.csv')

In [8]:
all_data=all_data.fillna('None')

In [14]:
var_Df.groupby(['No Provider']).count()

,Address Match,Business Phone,City Match,Connected,Disconnected,First Name Match,High Quality,INF,Landline,Last Name Match,...,Residential Phone,State Match,Toll free,Unknown Contact,Unknown phone type,VOIP,Wireless note,Wireless type,Workplace Match,ZipCode Match
No Provider,,,,,,,,,,,,,,,,,,,,,
0,1033,1033,1033,1033,1033,1033,1033,1033,1033,1033,...,1033,1033,1033,1033,1033,1033,1033,1033,1033,1033

In [17]:
all_data = all_data.fillna('None')
g.analyze_numbers(all_data)

# disconnect = all_data[all_data['COMMENTS'].isin(['NOT IN SERVICE'])]
# disconnect = disconnect.fillna('None')
# conn = g.analyze_numbers(connect)
# dis = g.analyze_numbers(disconnect)
# working = pd.DataFrame({'Connected':conn, 'Disconnected': dis})
# working['Connected %']=(working['Connected']/445)*100
# working['Disonnected %']=(working['Disconnected']/588)*100
# working

COBB WELLSTAR
ZUNIGA STEPHEN I NONE
ASCENSION WI
UNIVERSITY OF FLORIDA
None
None
PROVIDENT BANK
PROVIDENT BANK
ADVANCED GASTRO
LAKESHORE INTERNAL MEDICINE
M FERDINANDO
M FERDINANDO
EDDY D BARTH
EDDY D BARTH
A ADEWUYI
A ADEWUYI
None
None
ANGELA MCGREW
BURT FAIBISOFF MD
BURT FAIBISOFF MD
ARTHUR J SOUNDY
ARTHUR J SOUNDY
None
V DUKE
BETSY L KURTEN
BETSY L KURTEN
JONATHAN HARRIS
JONATHAN HARRIS
BRUCE FASSOLD
BRUCE FASSOLD
LOWE DENEAL
LOWE DENEAL
DIST SCHL BRD O
DIST SCHL BRD O
KIM PAUL D
EMORY UNIVERSITY
EMORY UNIVERSITY
KEITH W FACS
DAVID G JASKEY MD
EYE CONSULTANTS
ERICA ORREGO
ERICA ORREGO
None
None
SHAUN WASON
SHAUN WASON
UNIVERSITY OF MICHIGAN CREDIT UNION
None
None
RAMESH KANDALLU R MD FACS
RAMESH KANDALLU R MD FACS
WALTER W SEAY
WALTER W SEAY
BROOKLINE ASSOCIATES IN INTERNAL MEDICINE
JOSEPHINE SWANSON
GEORGE LYMAN
GEORGE LYMAN
LISA MILES
M MILTON
M MILTON
JOHNS HOPKINS H
JOHNS HOPKINS H
JOW SHONE LEE
SARAVANAN KASTH
WILSON TIFFANY D MD
WILSON TIFFANY D MD
COSERIU MICHAEL V MD
COSERIU MICHAEL V MD
DENNIS L WARNER
DENNIS L WARNER
CENTERSTONE
CENTERSTONE
LA CNTY OLIV VW
LA CNTY OLIV VW
ALHAID N S MD
HORTON PAUL C MD
HORTON PAUL C MD
JAFA AND CO
JAFA AND CO
SOMERA S GLINN
SOMERA S GLINN
BOBBY L BOX
BOBBY L BOX
NAZRE MAWLA MD
NEENA TRIPATHY
M HP RAD ONC COMPUTER MANUFACTURERS
ARNOLD RAVDEL ASSOCIATES
AUGUSTA UNIVERSITY AUGUSTA
REDMOND ANGELA MD
RGHS
UPMC ALTOONA PARTNERING FOR DENTAL SERVICES
AHMAD ANWAR
BONNIE ZERBE
MCLEOD REG MED
KIM A RICH
M AARON
PROVIDENCE TORRANCE
PHILIP C THOMPSON
ASIAN HUMAN SERVICES HUMAN SERVICES ORGANIZATIONS
KREMER LASER CTR
UNITED STATES GOVERNMENT DEFENSE DEPT OF AIR
BUILDING YANGCO MD PA
SCANFORMS INC
SILVER MINE SUBS
CONSULTANTS IN PAIN MANAGEMENT
FROEDTERT MEMOR
KAISER PERMANEN
GROUP INSIGNIA
DAVIS ANDY MD FAAFP
GA PED PULMONOL
AIG COMPANIES
VUKASIN PETAR MD
JESSICA D LUCAS
SALVATION ARMY
GWU
JORGE BENITO MDPA
BARRY N JONES
TONKA TRANSMISSION
None
KAISER PERMANEN
MUMTAZ JUNAGADHWALLA
IUPUI ENROLLMENT CENTER UNDERGRADUATE ADMISSIONS
ALEXANDER WEINSTEIN
GLENN JOHNSON
KAISER PERMANEN
EMSC
GEISINGER SYSTE
YEON SOONG AHN
REDDY ACHUTHA N MD
JESSICA WALDMAN
BORNEMANN INTERNAL MEDICINE OPTOMETRISTS OD
JACKSON MEMORIA
None
MOTION PICT TV
DUKE UNIVERSITY
None
CARONDELET LABORATORY SVC
WILLIAM FISCHIO
WESTSIDE P, FL
A RODE
A YEH
None
TIMOTHY J GAYOWSKI
None
HEARTLAND REGIO
None
AHC SYKES
ABRAHAM F SYRQUIN
LOS ANGELES COUNTY OF SUBDIVISIONPLAN CHECKING
ENG CALVIN T MD
None
PEREZ MARTINEZ
MARI YANCEY
LOMBANA, ISABELL
N MANHATTAN
RENE BARBAREE
DAVID W AIKEN
DEBRA'S PERSONAL TOUCH CLEANING SERVICE
WHIPPLE DANIEL R MD
P THOMPSON
C K ALEXANDER
SCHWARTZ RICHARD G MD FACS
PREMIEREPLAST
THOMAS S KALUZYNSKI
A PLACE FOR WOMEN
RICHARD L SHAFFER
AMERICAN PAIN AND WELLNESS
CORNERSTONE PRI
GALL SARAH MD
GESHKE TERRY E MD
PAUL L FAIRVIEW
O DECATUR
PHYMED
D HERMANN
TEXAS TECH UNIVERSITY
JOHN W HENDERSON
P DAVID
ESTHER LEVIN MD
BITAR GEORGE J MD
NY PRESBYTERIAN
DENNIS MOSS
STEPHANIE L VANDERVELDT
CAMPS JUAN I MD
DAVID V RHODES
NORTH STVINCENT
R BOPPANA
STEVEN W HARTMAN
BAYLOR COLLEGE OF MEDICINE
EMPOWER U INC
THOMAS JEFFERSON UNIVERSITY
WILLIAM R SMITH
G H ZUCKERMAN
CTY OF SONOMA
J2 GLOBAL COMMU
H VASSAR
REGINA SEK
DONALD S CHAMBERS
GRACIELA HERNANDEZ MD
VANTAGE POINT OF NORTHWEST ARKANSAS NW NORTH WEST
HERNANDEZ GABRIEL MD
IUPUI ENROLLMENT CENTER UNDERGRADUATE ADMISSIONS
MCLAREN
GARY K SELLMAN
DCMH
BENZIA DEAN MD
CARL P CRICCO
CHONGIN KWON
SIDHU HARJIT S
None
None
V FERNANDEZ
KAREN WENTZ
None
ST OF TX HHSC
JARED A ACOBA
RAPPAPORT HOWARD R PSY D
JAMES GAZZAWAY
NANCY HUERTAS
MYFIRSTCAREPED
None
DOUG DIEHL
SULLIVANS IS SC
BEED ELAINE MD
ST OF CALIF VET
OSVALDO RIVERA
UNIV SUBURBAN H
None
M M P INC TOLEDO TEL NO
NORTHSHORE
LEE EUGENE H MD & ASSOCIATES PA
None
P KEYSTONE
DALENE KHAN
None
None
S SOUTH
ALAN GIANNETTI
DAMIAN B KIM
P MILLER
SARAH NASH
CHRISTINA TROK
WELLSOURCE
YEXT, INC.
EAST OAHU COUNSELING CENTER LLC COUNSELING SERVICES
CA PTC
AMER INTL ASST
LGMDAMB FAMILY
AVELINO T GARCIA
EMERGINET
KAISER FOUNDATI
DOIM
S HOYT
NATIONWIDE CHIL
LOYOLA UNIV MED
EDGARDO CRUZ
ARLENE E HOARD
LOS ANGELES COUNTY OF
U S GOVERNMENT
DAYTOP VILLAGE INC CITY
B C B S M
LEE PRCHAL MD
OU TULSA
NYPRES
AVILES GONZALEZ CARLOS A MD
NYU
NO COUNTRY COMM
None
None
DONALD MUKULAK
GREGORY POLLACK
A PROP
TX TECH UNIV HE
CY L SALT
GAB MAQUEZ
VALLEY BEHAVIORAL
MCKINNEY F PIERRE
CAMERON M MCFARLAND
LETICIA MENDEZ
UNIVERSITY OF MIAMI
None
VNSNY
ALTMAN DAVID ELLIOT MD
CHARLES B REIMAN
VINCE BESAW
None
AA OF SOUTHEAST
KING OF PRU, PA
KAISER PERMANENTE
QUAD GRAPHICS INCORPORATED
DEVINDERJIT SINGH
KELSEY WALLACE
None
V QUIROZ
JONATHAN COLE
CONNIE MOSIER CRNP NURSES
K GUERIN
FLO WELCH
LAURA SCHWINDT
DENNIS M SMALL
OCALA REGIONAL
DEPARTMENT OF V
UNIV OF FL
JOHN SPINE DO
STEPHEN FERRARO
JEREMY KROCK
CORESMART
N MMP
GEOFFREY GILSON JEFF
OHIO DEPARTMENT OF TRANSPORTATION
JOHN B KRIBBS
HOLADAY HOWARD R MD
M D ANDERSON
HARVARD VANGUAR
CHERYL L BUCHWALTER
LILLIAM C VALDES
JERRY A SANCHEZ
TIMOTHY J DAVERN
SCHIANODICOLA
INTERNAL MEDICINE OF ARIZONA
ANU BHAT
AMY K HAYES
L JAMES
WESLY GRIFFIT
None
None
JEFFREY M NIIZAWA MD MD
IRSHAD ALI MD
JEFF HARRIS
SCOTT P HOOPES
LINDA BIGELOW
None
HOWARD BLUE
TRILLIUM DENTAL PC
J LARRY BARR MD
TRAVIS REICHLING
KOJI OKAMOTO
JEFFRY ANDERSON
SARA A VELEZ
ENVISION
JAMES LOEHR
ARTHRITIS OST
JEWELL JAMES R MD
ROXIE DAVIS
WASHINGTON MUTUAL
FRANCES C CHAIPRAKOB
DIWAN KANTA
LA ADVERTISING
JAIME A SOTERAS MD
REID GRAHAM M MD PA
KARINA LUGO
HERSCHEL C MARCUS
BCBS
None
KARE KID
ENG BART DO
None
VISIONARY MARKETING & SALES
KOLAHIFAR JAFAR MD
GONZALES G TORRES
JOHN J CASSEL
None
UMA REDDY
GOLDSTEIN LAUREN T MD
ANGEL R GARCIA
JESSIE BURTS
UND
SHARP LABORATORY
DOROTHY F BROWN
None
None
JENNIFER B PEDICANO MD
NORTHWESTERN MEDICINE NW
T ROSELLINI
LUKE DORF INC
U S GOVERNMENT
UNIVERSITY OF UT
LA CTY
PREMIER PRACTICE MANAGEMENT INC
GREATER BOSTON ACADEMY
RESOLUTIONS
ERNEST MUSGRAVE
MARISOL SEGUNDO
IUPUI ENROLLMENT CENTER UNDERGRADUATE ADMISSIONS
MEREDITH CORPOR
THOMAS WIEBER
THE HANOVER INN
None
LUH HENRY H Y MD
MELINDA MERRY
KAISER PERMANEN
UNIV OF CA IRVI
JOSE C COSMETIC
HOGGATT JUDY P SUSON  2300 N MAYFAIR RD  ROAD
JESSIE SINGH
BRECHER AND KNAPP
KARLA J JOHNS
None
MIKA SINANAN
None
RANDOLPH R FACS EVANS
JOHNS HOPKINS H
PENN MEDICINE WOODBURY
FAISON, SARAH
NEW ENGLAND EYE
CAROLINA N CALL
THE ANGELES CLI
P RIO
HARRY H POTE
THE VILLA AT MIDDLETON VILLAGE NURSING HOMES LIFE
HOWARD UNIV
SMITH BRUCE W MD
ESTHETICA OF NEWPORT BEACH
None
TAYYAB DIWAN
DUKE UNIVERSITY
JARED LEWIS
STOFMAN GUY MD FACS
GRECO GIAMPAOLO
NARAYANAN KRISHNA MD
MATTHEW TROUARD
DONALD A MCEACHERN
ADAPT OF TEXAS
SAEED M AWAN
LEE STRATTON
GILBREATH & PARK
SUSAN NAKAMURA
None
STEVEN Y PARK
TAT S RITHAPORN
TWIN CITIES,MN
HERBERT NORTON
LEE JULIANNE O MD
JOSE IGLESIAS
None
SANDOVAL JAIME DAVID
DIEGUEZ EDWARD MD PA
ARIZONA SPORT MEDICINE CONSULTANTS
SHAIKLEY MD INC
KOOTENAI MEDICA
MCREYNOLDS EDWA
BRAUD MARIA MD
ALDO J SURACI
LARRY BRUNO
MARY LEE
NEVADA STATE BANK
ROBBIE BRAND
None
ASSOCIATED CHES
MARIA PEREZ
JOHNS HOPKINS H
PARADISE MASSAGE AND SKIN CARE MASSAGE THERAPISTS
ERIKA MILES
KEITH D LOBEL
E SW
None
FLORIDA STATE OF

NameError: name 'connect' is not defined

In [29]:
g.analyze_numbers(connect)

KEITH W FACS

{'Address Matches': 225,
 'City Matches': 351,
 'ZipCode Matches': 319,
 'No Address': 88,
 'No Date': 166,
 'Relevant Name': 313,
 'Business Phone': 372,
 'Residential Phone': 56,
 'Low Quality': 119,
 'Medium Quality': 43,
 'High Quality': 277,
 'Mailable': 347,
 'Connected': 311,
 'Ported': 279,
 'Unknown Contact': 6,
 'Possibly Disconnected': 14,
 'Possibly Portable VOIP': 19,
 'Wireless': 1,
 'First Name Match': 74,
 'Last Name Match': 74,
 'Workplace Match': 16,
 'State Match': 422,
 'No Name': 6,
 'Relevant SIC': 91,
 'Tiny Count': 1,
 'disconnected-70': 0,
 'disconnected': 0}

In [32]:
all_data['status']

0          disconnected
1          disconnected
2          disconnected
3       disconnected-70
4       disconnected-70
5       disconnected-70
6       disconnected-70
7          disconnected
8          disconnected
9          disconnected
10         disconnected
11      disconnected-70
12      disconnected-70
13      disconnected-70
14      disconnected-70
15      disconnected-70
16      disconnected-70
17         disconnected
18         disconnected
19      disconnected-70
20      disconnected-70
21      disconnected-70
22         disconnected
23      disconnected-70
24         disconnected
25         disconnected
26         disconnected
27      disconnected-70
28      disconnected-70
29         disconnected
             ...
1083    disconnected-70
1084    disconnected-70
1085       disconnected
1086       disconnected
1087    disconnected-70
1088    disconnected-70
1089       disconnected
1090       disconnected
1091       disconnected
1092    disconnected-70
1093    disconnected-70
1094       disconnected
1095    disconnected-70
1096    disconnected-70
1097    disconnected-70
1098       disconnected
1099       disconnected
1100    disconnected-70
1101       disconnected
1102       disconnected
1103       disconnected
1104       disconnected
1105       disconnected
1106       disconnected
1107       disconnected
1108       disconnected
1109       disconnected
1110    disconnected-70
1111       disconnected
1112       disconnected
Name: status, Length: 1113, dtype: object